# API - Finance

Visit https://www.alphavantage.co/ and get your free API key

# 1) Stock Price Data
```
OHLC data (Open, High, Low, Close)
Volume
Time series analysis
Returns calculation

In [3]:
!pip install python-dotenv

Collecting python-dotenv
  Downloading python_dotenv-1.2.2-py3-none-any.whl.metadata (27 kB)
Downloading python_dotenv-1.2.2-py3-none-any.whl (22 kB)
Installing collected packages: python-dotenv
Successfully installed python-dotenv-1.2.2

[notice] A new release of pip is available: 25.0.1 -> 26.1.2
[notice] To update, run: python.exe -m pip install --upgrade pip

In [4]:
# Always read from .env file: Good practice
import os
from dotenv import load_dotenv

# 1. Load the environment variables from the .env file
load_dotenv()

# 2. Retrieve the variables using standard os.environ
database_host = os.environ.get("DB_SECRET")
secret_api_key = os.getenv("ALPHAADVANTAGE_API_KEY")

# 3. Use your variables safely
print(f"Database Host: {database_host}")
# print(f"secret_api_key: {secret_api_key}")

print(f"API Key Length: {len(secret_api_key) if secret_api_key else 0} characters")

Database Host: fjkfskds
API Key Length: 14 characters

In [5]:
import requests

# replace the "demo" apikey below with your own key from https://www.alphavantage.co/support/#api-key
# ALPHAADVANTAGE_API_KEY="" # see .env file for the key
ALPHAADVANTAGE_API_KEY=os.getenv("ALPHAADVANTAGE_API_KEY")

# This is premium. You have to pay for this.
# url = f"https://www.alphavantage.co/query?function=TIME_SERIES_INTRADAY&symbol=IBM&interval=5min&apikey={ALPHAADVANTAGE_API_KEY}" 

# This is free.

# The following would give you weekly stocks data
TICKER='IBM'
url = f"https://www.alphavantage.co/query?function=TIME_SERIES_WEEKLY&symbol={TICKER}&apikey={ALPHAADVANTAGE_API_KEY}"


data = requests.get(url).json()

print(data)

{'Meta Data': {'1. Information': 'Weekly Prices (open, high, low, close) and Volumes', '2. Symbol': 'IBM', '3. Last Refreshed': '2026-06-05', '4. Time Zone': 'US/Eastern'}, 'Weekly Time Series': {'2026-06-05': {'1. open': '322.5500', '2. high': '332.4600', '3. low': '281.0701', '4. close': '284.8400', '5. volume': '86135011'}, '2026-05-29': {'1. open': '254.5500', '2. high': '300.9999', '3. low': '245.4500', '4. close': '297.8000', '5. volume': '59445527'}, '2026-05-22': {'1. open': '218.5500', '2. high': '264.3800', '3. low': '216.7800', '4. close': '253.8400', '5. volume': '61523775'}, '2026-05-15': {'1. open': '228.6600', '2. high': '230.2300', '3. low': '212.3400', '4. close': '219.3000', '5. volume': '33144274'}, '2026-05-08': {'1. open': '232.0000', '2. high': '234.0900', '3. low': '224.3800', '4. close': '229.7600', '5. volume': '26716501'}, '2026-05-01': {'1. open': '229.9500', '2. high': '235.9500', '3. low': '224.9000', '4. close': '232.2000', '5. volume': '29532709'}, '2026-04-24': {'1. open': '255.0000', '2. high': '258.5000', '3. low': '221.7300', '4. close': '231.9800', '5. volume': '55047502'}, '2026-04-17': {'1. open': '233.6300', '2. high': '255.6500', '3. low': '231.7000', '4. close': '253.4700', '5. volume': '23495380'}, '2026-04-10': {'1. open': '248.1400', '2. high': '250.0000', '3. low': '230.5100', '4. close': '230.7600', '5. volume': '21451523'}, '2026-04-02': {'1. open': '237.8000', '2. high': '248.2103', '3. low': '236.1310', '4. close': '248.1600', '5. volume': '16212406'}, '2026-03-27': {'1. open': '246.5000', '2. high': '251.3500', '3. low': '233.7500', '4. close': '236.3400', '5. volume': '21791992'}, '2026-03-20': {'1. open': '247.8700', '2. high': '258.2800', '3. low': '241.7700', '4. close': '241.7700', '5. volume': '32254965'}, '2026-03-13': {'1. open': '255.3800', '2. high': '258.0800', '3. low': '244.7100', '4. close': '246.2800', '5. volume': '24962921'}, '2026-03-06': {'1. open': '235.7000', '2. high': '260.3800', '3. low': '233.7800', '4. close': '258.8500', '5. volume': '35400015'}, '2026-02-27': {'1. open': '254.3700', '2. high': '255.1900', '3. low': '220.7200', '4. close': '240.2100', '5. volume': '55457688'}, '2026-02-20': {'1. open': '259.2000', '2. high': '261.1100', '3. low': '253.5110', '4. close': '257.1600', '5. volume': '18536212'}, '2026-02-13': {'1. open': '295.9100', '2. high': '297.7200', '3. low': '256.6400', '4. close': '262.3800', '5. volume': '35501402'}, '2026-02-06': {'1. open': '307.5100', '2. high': '316.6400', '3. low': '278.9600', '4. close': '298.9300', '5. volume': '33862352'}, '2026-01-30': {'1. open': '293.1600', '2. high': '319.9000', '3. low': '291.2601', '4. close': '306.7000', '5. volume': '28527557'}, '2026-01-23': {'1. open': '301.3500', '2. high': '301.6000', '3. low': '289.7900', '4. close': '292.4400', '5. volume': '19365305'}, '2026-01-16': {'1. open': '302.6200', '2. high': '312.8100', '3. low': '297.0400', '4. close': '305.6700', '5. volume': '23314117'}, '2026-01-09': {'1. open': '295.7700', '2. high': '307.0000', '3. low': '294.2500', '4. close': '304.2200', '5. volume': '17232650'}, '2026-01-02': {'1. open': '304.6500', '2. high': '310.0000', '3. low': '289.0000', '4. close': '291.5000', '5. volume': '14641299'}, '2025-12-26': {'1. open': '301.0300', '2. high': '305.7500', '3. low': '298.3200', '4. close': '305.0900', '5. volume': '9560511'}, '2025-12-19': {'1. open': '308.9850', '2. high': '311.3629', '3. low': '295.7000', '4. close': '300.9800', '5. volume': '26507574'}, '2025-12-12': {'1. open': '309.6200', '2. high': '315.3454', '3. low': '303.3300', '4. close': '309.2400', '5. volume': '15650716'}, '2025-12-05': {'1. open': '306.5050', '2. high': '311.8300', '3. low': '298.9050', '4. close': '307.9400', '5. volume': '16688175'}, '2025-11-28': {'1. open': '299.1800', '2. high': '309.1800', '3. low': '297.0600', '4. close': '308.5800', '5. volume': '12761439'}, '2025-11-21': {'1. open': '305.5900', '2. high': '306.0000', '3. low': '288.0700', '4. close': '297.4400', '5. volume': '23675512'}, '2025-11-14': {'1. open': '306.8200', '2. high': '324.9000', '3. low': '297.5900', '4. close': '305.6900', '5. volume': '22302392'}, '2025-11-07': {'1. open': '308.0000', '2. high': '315.4400', '3. low': '296.0000', '4. close': '306.3800', '5. volume': '27157777'}, '2025-10-31': {'1. open': '307.8000', '2. high': '319.3500', '3. low': '301.6300', '4. close': '307.4100', '5. volume': '32440643'}, '2025-10-24': {'1. open': '281.2500', '2. high': '310.7500', '3. low': '263.5623', '4. close': '307.4600', '5. volume': '51704434'}, '2025-10-17': {'1. open': '279.7900', '2. high': '285.4500', '3. low': '272.5469', '4. close': '281.2800', '5. volume': '19005226'}, '2025-10-10': {'1. open': '288.6100', '2. high': '301.0425', '3. low': '277.5000', '4. close': '277.8200', '5. volume': '24789984'}, '2025-10-03': {'1. open': '286.0000', '2. high': '293.3200', '3. low': '279.6600', '4. close': '288.3700', '5. volume': '24519701'}, '2025-09-26': {'1. open': '266.6200', '2. high': '288.8500', '3. low': '266.0000', '4. close': '284.3100', '5. volume': '34154715'}, '2025-09-19': {'1. open': '254.0200', '2. high': '267.8700', '3. low': '254.0000', '4. close': '266.4000', '5. volume': '25569601'}, '2025-09-12': {'1. open': '248.6300', '2. high': '260.6600', '3. low': '247.0200', '4. close': '253.4400', '5. volume': '24066143'}, '2025-09-05': {'1. open': '240.9000', '2. high': '249.2800', '3. low': '238.2500', '4. close': '248.5300', '5. volume': '14538355'}, '2025-08-29': {'1. open': '242.5650', '2. high': '245.9600', '3. low': '239.4300', '4. close': '243.4900', '5. volume': '18386656'}, '2025-08-22': {'1. open': '239.5700', '2. high': '243.6800', '3. low': '238.6500', '4. close': '242.0900', '5. volume': '16264747'}, '2025-08-15': {'1. open': '242.2400', '2. high': '243.1500', '3. low': '233.3600', '4. close': '239.7200', '5. volume': '32747166'}, '2025-08-08': {'1. open': '251.0500', '2. high': '255.0000', '3. low': '241.6500', '4. close': '242.2700', '5. volume': '27875384'}, '2025-08-01': {'1. open': '260.3000', '2. high': '265.7999', '3. low': '245.6100', '4. close': '250.0500', '5. volume': '29960567'}, '2025-07-25': {'1. open': '286.2900', '2. high': '288.0800', '3. low': '252.7500', '4. close': '259.7200', '5. volume': '46388289'}, '2025-07-18': {'1. open': '282.8300', '2. high': '287.1600', '3. low': '279.8700', '4. close': '285.8700', '5. volume': '16341671'}, '2025-07-11': {'1. open': '292.5000', '2. high': '295.6100', '3. low': '282.2100', '4. close': '283.5900', '5. volume': '17664449'}, '2025-07-03': {'1. open': '290.9300', '2. high': '295.1081', '3. low': '286.9000', '4. close': '291.9700', '5. volume': '11878987'}, '2025-06-27': {'1. open': '281.6500', '2. high': '296.1600', '3. low': '280.2100', '4. close': '289.7000', '5. volume': '19051199'}, '2025-06-20': {'1. open': '279.3050', '2. high': '286.9100', '3. low': '277.2000', '4. close': '280.9700', '5. volume': '17965949'}, '2025-06-13': {'1. open': '268.1000', '2. high': '283.0600', '3. low': '266.7100', '4. close': '277.2200', '5. volume': '20812836'}, '2025-06-06': {'1. open': '257.8500', '2. high': '270.1700', '3. low': '257.2200', '4. close': '268.8700', '5. volume': '13070565'}, '2025-05-30': {'1. open': '261.0000', '2. high': '265.0000', '3. low': '256.7700', '4. close': '259.0600', '5. volume': '17566804'}, '2025-05-23': {'1. open': '265.4500', '2. high': '269.2800', '3. low': '255.7900', '4. close': '258.6300', '5. volume': '15204641'}, '2025-05-16': {'1. open': '252.5000', '2. high': '267.9800', '3. low': '244.6500', '4. close': '266.7600', '5. volume': '20440246'}, '2025-05-09': {'1. open': '243.7400', '2. high': '256.5200', '3. low': '243.6400', '4. close': '249.2000', '5. volume': '16977083'}, '2025-05-02': {'1. open': '232.8600', '2. high': '245.6900', '3. low': '232.0700', '4. close': '245.5500', '5. volume': '20198202'}, '2025-04-25': {'1. open': '238.0650', '2. high': '249.3400', '3. low': '224.4401', '4. close': '232.4100', '5. volume': '39218052'}, '2025-04-17': {'1. open': '239.7700', '2. high': '243.2999', '3. low': '235.8900', '4. close': '238.8100', '5. volume': '16190928'}, '2025-04-11': {'1. open': '219.2400', '2. high': '237.5800', '3. low': '214.5000', '4. close': '235.4800', '5. volume': '31932696'}, '2025-04-04': {'1. open': '242.7400', '2. high': '252.7900', '3. low': '226.8800', '4. close': '227.4800', '5. volume': '28005665'}, '2025-03-28': {'1. open': '247.3100', '2. high': '254.3200', '3. low': '242.0700', '4. close': '244.0000', '5. volume': '18354282'}, '2025-03-21': {'1. open': '249.2500', '2. high': '254.6300', '3. low': '237.2240', '4. close': '243.8700', '5. volume': '27866866'}, '2025-03-14': {'1. open': '261.5600', '2. high': '266.4500', '3. low': '241.6800', '4. close': '248.3500', '5. volume': '25513710'}, '2025-03-07': {'1. open': '254.7350', '2. high': '261.9600', '3. low': '245.1823', '4. close': '261.5400', '5. volume': '22284160'}, '2025-02-28': {'1. open': '261.5000', '2. high': '263.8450', '3. low': '246.5400', '4. close': '252.4400', '5. volume': '25541761'}, '2025-02-21': {'1. open': '261.9300', '2. high': '265.0900', '3. low': '259.8300', '4. close': '261.4800', '5. volume': '18534169'}, '2025-02-14': {'1. open': '250.8600', '2. high': '261.9400', '3. low': '246.8700', '4. close': '261.2800', '5. volume': '19898073'}, '2025-02-07': {'1. open': '252.4000', '2. high': '265.7200', '3. low': '251.8400', '4. close': '252.3400', '5. volume': '30149848'}, '2025-01-31': {'1. open': '222.1900', '2. high': '261.8000', '3. low': '219.8400', '4. close': '255.7000', '5. volume': '39048997'}, '2025-01-24': {'1. open': '224.9900', '2. high': '227.4500', '3. low': '220.3500', '4. close': '224.8000', '5. volume': '15594637'}, '2025-01-17': {'1. open': '217.8900', '2. high': '225.9550', '3. low': '214.6100', '4. close': '224.7900', '5. volume': '18990367'}, '2025-01-10': {'1. open': '223.0000', '2. high': '226.7110', '3. low': '216.8000', '4. close': '219.7500', '5. volume': '12337094'}, '2025-01-03': {'1. open': '220.5400', '2. high': '223.6600', '3. low': '217.6000', '4. close': '222.6500', '5. volume': '10819153'}, '2024-12-27': {'1. open': '222.8100', '2. high': '225.4000', '3. low': '221.0800', '4. close': '222.7800', '5. volume': '9272351'}, '2024-12-20': {'1. open': '230.7300', '2. high': '231.0300', '3. low': '220.0300', '4. close': '223.3600', '5. volume': '28267440'}, '2024-12-13': {'1. open': '238.0000', '2. high': '239.3500', '3. low': '227.8000', '4. close': '230.8200', '5. volume': '20886084'}, '2024-12-06': {'1. open': '227.5000', '2. high': '238.3800', '3. low': '225.5100', '4. close': '238.0400', '5. volume': '18743737'}, '2024-11-29': {'1. open': '223.3500', '2. high': '230.3600', '3. low': '222.6500', '4. close': '227.4100', '5. volume': '17274177'}, '2024-11-22': {'1. open': '207.0000', '2. high': '227.2000', '3. low': '205.3701', '4. close': '222.9700', '5. volume': '21386866'}, '2024-11-15': {'1. open': '214.4000', '2. high': '215.4100', '3. low': '204.0700', '4. close': '204.9900', '5. volume': '19438346'}, '2024-11-08': {'1. open': '207.6500', '2. high': '216.7000', '3. low': '205.5700', '4. close': '213.7200', '5. volume': '15846890'}, '2024-11-01': {'1. open': '215.5000', '2. high': '216.2500', '3. low': '203.5100', '4. close': '208.2500', '5. volume': '26467891'}, '2024-10-25': {'1. open': '231.2100', '2. high': '233.3400', '3. low': '214.3850', '4. close': '214.6700', '5. volume': '31380820'}, '2024-10-18': {'1. open': '233.5700', '2. high': '237.3700', '3. low': '230.1700', '4. close': '232.2000', '5. volume': '18477394'}, '2024-10-11': {'1. open': '225.3800', '2. high': '235.8300', '3. low': '225.0200', '4. close': '233.2600', '5. volume': '18398213'}, '2024-10-04': {'1. open': '220.6500', '2. high': '226.0800', '3. low': '215.7980', '4. close': '226.0000', '5. volume': '17778630'}, '2024-09-27': {'1. open': '218.0000', '2. high': '224.1500', '3. low': '217.2700', '4. close': '220.8400', '5. volume': '16300165'}, '2024-09-20': {'1. open': '215.8800', '2. high': '218.8400', '3. low': '210.3700', '4. close': '217.7000', '5. volume': '28532770'}, '2024-09-13': {'1. open': '201.9400', '2. high': '216.0900', '3. low': '201.4300', '4. close': '214.7900', '5. volume': '21518747'}, '2024-09-06': {'1. open': '201.9100', '2. high': '205.9500', '3. low': '199.3350', '4. close': '200.7400', '5. volume': '13519865'}, '2024-08-30': {'1. open': '196.0000', '2. high': '202.1700', '3. low': '195.9000', '4. close': '202.1300', '5. volume': '15570283'}, '2024-08-23': {'1. open': '193.8400', '2. high': '197.9200', '3. low': '193.7150', '4. close': '196.1000', '5. volume': '11022549'}, '2024-08-16': {'1. open': '191.2500', '2. high': '194.3500', '3. low': '189.0001', '4. close': '193.7800', '5. volume': '11330854'}, '2024-08-09': {'1. open': '184.5500', '2. high': '192.8800', '3. low': '181.8100', '4. close': '191.4500', '5. volume': '18895865'}, '2024-08-02': {'1. open': '193.1800', '2. high': '194.5499', '3. low': '185.7000', '4. close': '189.1200', '5. volume': '20594367'}, '2024-07-26': {'1. open': '183.4000', '2. high': '196.2600', '3. low': '182.8600', '4. close': '191.7500', '5. volume': '25458498'}, '2024-07-19': {'1. open': '183.3800', '2. high': '189.4700', '3. low': '181.9500', '4. close': '183.2500', '5. volume': '17829469'}, '2024-07-12': {'1. open': '176.4100', '2. high': '184.1600', '3. low': '174.4500', '4. close': '182.8300', '5. volume': '16071235'}, '2024-07-05': {'1. open': '173.4500', '2. high': '177.9800', '3. low': '173.3800', '4. close': '176.0200', '5. volume': '9939255'}, '2024-06-28': {'1. open': '175.0000', '2. high': '178.4599', '3. low': '170.4100', '4. close': '172.9500', '5. volume': '18850478'}, '2024-06-21': {'1. open': '168.7600', '2. high': '174.9600', '3. low': '167.5000', '4. close': '172.4600', '5. volume': '21531360'}, '2024-06-14': {'1. open': '169.5500', '2. high': '172.4700', '3. low': '166.8100', '4. close': '169.2100', '5. volume': '16222067'}, '2024-06-07': {'1. open': '166.5400', '2. high': '171.3050', '3. low': '163.5300', '4. close': '170.0100', '5. volume': '14102396'}, '2024-05-31': {'1. open': '170.4400', '2. high': '171.0850', '3. low': '163.8400', '4. close': '166.8500', '5. volume': '15594186'}, '2024-05-24': {'1. open': '169.0000', '2. high': '175.4600', '3. low': '168.3800', '4. close': '170.8900', '5. volume': '18410125'}, '2024-05-17': {'1. open': '167.5000', '2. high': '169.6300', '3. low': '166.4800', '4. close': '169.0300', '5. volume': '15933303'}, '2024-05-10': {'1. open': '166.5000', '2. high': '170.2600', '3. low': '165.8800', '4. close': '167.1500', '5. volume': '17421523'}, '2024-05-03': {'1. open': '167.4000', '2. high': '168.2200', '3. low': '162.6200', '4. close': '165.7100', '5. volume': '22536194'}, '2024-04-26': {'1. open': '182.4500', '2. high': '184.6800', '3. low': '165.6600', '4. close': '167.1300', '5. volume': '42329269'}, '2024-04-19': {'1. open': '185.5700', '2. high': '187.4800', '3. low': '180.1700', '4. close': '181.5800', '5. volume': '16929550'}, '2024-04-12': {'1. open': '189.2400', '2. high': '191.2500', '3. low': '181.6850', '4. close': '182.2700', '5. volume': '14955313'}, '2024-04-05': {'1. open': '190.0000', '2. high': '193.2800', '3. low': '187.3400', '4. close': '189.1400', '5. volume': '12808073'}, '2024-03-28': {'1. open': '190.2600', '2. high': '191.9299', '3. low': '188.5000', '4. close': '190.9600', '5. volume': '15383298'}, '2024-03-22': {'1. open': '191.7000', '2. high': '193.9800', '3. low': '190.0100', '4. close': '190.8400', '5. volume': '23968505'}, '2024-03-15': {'1. open': '195.0900', '2. high': '199.1800', '3. low': '190.7000', '4. close': '191.0700', '5. volume': '27466323'}, '2024-03-08': {'1. open': '187.7600', '2. high': '198.7300', '3. low': '187.6000', '4. close': '195.9500', '5. volume': '29085296'}, '2024-03-01': {'1. open': '185.6000', '2. high': '188.3800', '3. low': '182.6200', '4. close': '188.2000', '5. volume': '21955379'}, '2024-02-23': {'1. open': '187.6400', '2. high': '188.7700', '3. low': '178.7500', '4. close': '185.7200', '5. volume': '17487852'}, '2024-02-16': {'1. open': '185.9000', '2. high': '188.9500', '3. low': '182.2600', '4. close': '187.6400', '5. volume': '21745006'}, '2024-02-09': {'1. open': '185.5100', '2. high': '187.1800', '3. low': '181.4900', '4. close': '186.3400', '5. volume': '22784812'}, '2024-02-02': {'1. open': '187.4600', '2. high': '189.4600', '3. low': '182.7100', '4. close': '185.7900', '5. volume': '28283876'}, '2024-01-26': {'1. open': '172.8200', '2. high': '196.9000', '3. low': '172.4000', '4. close': '187.4200', '5. volume': '56232762'}, '2024-01-19': {'1. open': '165.8000', '2. high': '171.5791', '3. low': '165.0400', '4. close': '171.4800', '5. volume': '19864308'}, '2024-01-12': {'1. open': '158.6900', '2. high': '165.9800', '3. low': '157.8850', '4. close': '165.8000', '5. volume': '17643392'}, '2024-01-05': {'1. open': '162.8300', '2. high': '163.2900', '3. low': '158.6700', '4. close': '159.1600', '5. volume': '14822074'}, '2023-12-29': {'1. open': '162.2300', '2. high': '164.1800', '3. low': '162.0500', '4. close': '163.5500', '5. volume': '9376537'}, '2023-12-22': {'1. open': '162.2300', '2. high': '163.3300', '3. low': '159.5300', '4. close': '162.1400', '5. volume': '17686398'}, '2023-12-15': {'1. open': '162.6800', '2. high': '166.3400', '3. low': '160.1490', '4. close': '162.2300', '5. volume': '33504550'}, '2023-12-08': {'1. open': '160.2900', '2. high': '162.7900', '3. low': '159.9700', '4. close': '161.9600', '5. volume': '21918957'}, '2023-12-01': {'1. open': '154.9900', '2. high': '160.5900', '3. low': '154.7500', '4. close': '160.5500', '5. volume': '21900644'}, '2023-11-24': {'1. open': '152.5100', '2. high': '155.7050', '3. low': '152.3500', '4. close': '155.1800', '5. volume': '11362696'}, '2023-11-17': {'1. open': '148.4600', '2. high': '153.5000', '3. low': '147.3500', '4. close': '152.8900', '5. volume': '19547595'}, '2023-11-10': {'1. open': '147.8900', '2. high': '149.6800', '3. low': '145.2800', '4. close': '149.0200', '5. volume': '18357944'}, '2023-11-03': {'1. open': '143.1900', '2. high': '148.4450', '3. low': '142.5800', '4. close': '147.9000', '5. volume': '22959464'}, '2023-10-27': {'1. open': '136.6300', '2. high': '144.7000', '3. low': '135.8700', '4. close': '142.5200', '5. volume': '30227448'}, '2023-10-20': {'1. open': '139.2800', '2. high': '140.6200', '3. low': '136.3100', '4. close': '137.1600', '5. volume': '21044049'}, '2023-10-13': {'1. open': '142.3000', '2. high': '143.4150', '3. low': '138.2700', '4. close': '138.4600', '5. volume': '16386334'}, '2023-10-06': {'1. open': '140.0400', '2. high': '142.9400', '3. low': '139.8600', '4. close': '142.0300', '5. volume': '15932918'}, '2023-09-29': {'1. open': '146.5700', '2. high': '147.4300', '3. low': '139.6100', '4. close': '140.3000', '5. volume': '23445425'}, '2023-09-22': {'1. open': '145.7700', '2. high': '151.9299', '3. low': '144.6600', '4. close': '146.9100', '5. volume': '23597168'}, '2023-09-15': {'1. open': '148.5700', '2. high': '148.7800', '3. low': '145.5300', '4. close': '145.9900', '5. volume': '19316647'}, '2023-09-08': {'1. open': '147.9100', '2. high': '149.0000', '3. low': '147.1200', '4. close': '147.6800', '5. volume': '13719451'}, '2023-09-01': {'1. open': '145.4100', '2. high': '148.1000', '3. low': '145.2100', '4. close': '147.9400', '5. volume': '15198607'}, '2023-08-25': {'1. open': '141.4200', '2. high': '145.4700', '3. low': '141.1100', '4. close': '145.3500', '5. volume': '15614989'}, '2023-08-18': {'1. open': '143.0500', '2. high': '143.3650', '3. low': '139.7600', '4. close': '141.4100', '5. volume': '18826007'}, '2023-08-11': {'1. open': '145.0000', '2. high': '146.5000', '3. low': '142.2050', '4. close': '143.1200', '5. volume': '19428470'}, '2023-08-04': {'1. open': '143.8100', '2. high': '146.0900', '3. low': '142.1700', '4. close': '144.2400', '5. volume': '240

In [19]:
# Lets see the keys

data.keys()

dict_keys(['Meta Data', 'Weekly Time Series'])

In [6]:
data["Meta Data"]

{'1. Information': 'Weekly Prices (open, high, low, close) and Volumes',
 '2. Symbol': 'IBM',
 '3. Last Refreshed': '2026-06-05',
 '4. Time Zone': 'US/Eastern'}

In [7]:
data["Weekly Time Series"]

{'2026-06-05': {'1. open': '322.5500',
  '2. high': '332.4600',
  '3. low': '281.0701',
  '4. close': '284.8400',
  '5. volume': '86135011'},
 '2026-05-29': {'1. open': '254.5500',
  '2. high': '300.9999',
  '3. low': '245.4500',
  '4. close': '297.8000',
  '5. volume': '59445527'},
 '2026-05-22': {'1. open': '218.5500',
  '2. high': '264.3800',
  '3. low': '216.7800',
  '4. close': '253.8400',
  '5. volume': '61523775'},
 '2026-05-15': {'1. open': '228.6600',
  '2. high': '230.2300',
  '3. low': '212.3400',
  '4. close': '219.3000',
  '5. volume': '33144274'},
 '2026-05-08': {'1. open': '232.0000',
  '2. high': '234.0900',
  '3. low': '224.3800',
  '4. close': '229.7600',
  '5. volume': '26716501'},
 '2026-05-01': {'1. open': '229.9500',
  '2. high': '235.9500',
  '3. low': '224.9000',
  '4. close': '232.2000',
  '5. volume': '29532709'},
 '2026-04-24': {'1. open': '255.0000',
  '2. high': '258.5000',
  '3. low': '221.7300',
  '4. close': '231.9800',
  '5. volume': '55047502'},
 '2026-04-17': {'1. open': '233.6300',
  '2. high': '255.6500',
  '3. low': '231.7000',
  '4. close': '253.4700',
  '5. volume': '23495380'},
 '2026-04-10': {'1. open': '248.1400',
  '2. high': '250.0000',
  '3. low': '230.5100',
  '4. close': '230.7600',
  '5. volume': '21451523'},
 '2026-04-02': {'1. open': '237.8000',
  '2. high': '248.2103',
  '3. low': '236.1310',
  '4. close': '248.1600',
  '5. volume': '16212406'},
 '2026-03-27': {'1. open': '246.5000',
  '2. high': '251.3500',
  '3. low': '233.7500',
  '4. close': '236.3400',
  '5. volume': '21791992'},
 '2026-03-20': {'1. open': '247.8700',
  '2. high': '258.2800',
  '3. low': '241.7700',
  '4. close': '241.7700',
  '5. volume': '32254965'},
 '2026-03-13': {'1. open': '255.3800',
  '2. high': '258.0800',
  '3. low': '244.7100',
  '4. close': '246.2800',
  '5. volume': '24962921'},
 '2026-03-06': {'1. open': '235.7000',
  '2. high': '260.3800',
  '3. low': '233.7800',
  '4. close': '258.8500',
  '5. volume': '35400015'},
 '2026-02-27': {'1. open': '254.3700',
  '2. high': '255.1900',
  '3. low': '220.7200',
  '4. close': '240.2100',
  '5. volume': '55457688'},
 '2026-02-20': {'1. open': '259.2000',
  '2. high': '261.1100',
  '3. low': '253.5110',
  '4. close': '257.1600',
  '5. volume': '18536212'},
 '2026-02-13': {'1. open': '295.9100',
  '2. high': '297.7200',
  '3. low': '256.6400',
  '4. close': '262.3800',
  '5. volume': '35501402'},
 '2026-02-06': {'1. open': '307.5100',
  '2. high': '316.6400',
  '3. low': '278.9600',
  '4. close': '298.9300',
  '5. volume': '33862352'},
 '2026-01-30': {'1. open': '293.1600',
  '2. high': '319.9000',
  '3. low': '291.2601',
  '4. close': '306.7000',
  '5. volume': '28527557'},
 '2026-01-23': {'1. open': '301.3500',
  '2. high': '301.6000',
  '3. low': '289.7900',
  '4. close': '292.4400',
  '5. volume': '19365305'},
 '2026-01-16': {'1. open': '302.6200',
  '2. high': '312.8100',
  '3. low': '297.0400',
  '4. close': '305.6700',
  '5. volume': '23314117'},
 '2026-01-09': {'1. open': '295.7700',
  '2. high': '307.0000',
  '3. low': '294.2500',
  '4. close': '304.2200',
  '5. volume': '17232650'},
 '2026-01-02': {'1. open': '304.6500',
  '2. high': '310.0000',
  '3. low': '289.0000',
  '4. close': '291.5000',
  '5. volume': '14641299'},
 '2025-12-26': {'1. open': '301.0300',
  '2. high': '305.7500',
  '3. low': '298.3200',
  '4. close': '305.0900',
  '5. volume': '9560511'},
 '2025-12-19': {'1. open': '308.9850',
  '2. high': '311.3629',
  '3. low': '295.7000',
  '4. close': '300.9800',
  '5. volume': '26507574'},
 '2025-12-12': {'1. open': '309.6200',
  '2. high': '315.3454',
  '3. low': '303.3300',
  '4. close': '309.2400',
  '5. volume': '15650716'},
 '2025-12-05': {'1. open': '306.5050',
  '2. high': '311.8300',
  '3. low': '298.9050',
  '4. close': '307.9400',
  '5. volume': '16688175'},
 '2025-11-28': {'1. open': '299.1800',
  '2. high': '309.1800',
  '3. low': '297.0600',
  '4. close': '308.5800',
  '5. volume': '12761439'},
 '2025-11-21': {'1. open': '305.5900',
  '2. high': '306.0000',
  '3. low': '288.0700',
  '4. close': '297.4400',
  '5. volume': '23675512'},
 '2025-11-14': {'1. open': '306.8200',
  '2. high': '324.9000',
  '3. low': '297.5900',
  '4. close': '305.6900',
  '5. volume': '22302392'},
 '2025-11-07': {'1. open': '308.0000',
  '2. high': '315.4400',
  '3. low': '296.0000',
  '4. close': '306.3800',
  '5. volume': '27157777'},
 '2025-10-31': {'1. open': '307.8000',
  '2. high': '319.3500',
  '3. low': '301.6300',
  '4. close': '307.4100',
  '5. volume': '32440643'},
 '2025-10-24': {'1. open': '281.2500',
  '2. high': '310.7500',
  '3. low': '263.5623',
  '4. close': '307.4600',
  '5. volume': '51704434'},
 '2025-10-17': {'1. open': '279.7900',
  '2. high': '285.4500',
  '3. low': '272.5469',
  '4. close': '281.2800',
  '5. volume': '19005226'},
 '2025-10-10': {'1. open': '288.6100',
  '2. high': '301.0425',
  '3. low': '277.5000',
  '4. close': '277.8200',
  '5. volume': '24789984'},
 '2025-10-03': {'1. open': '286.0000',
  '2. high': '293.3200',
  '3. low': '279.6600',
  '4. close': '288.3700',
  '5. volume': '24519701'},
 '2025-09-26': {'1. open': '266.6200',
  '2. high': '288.8500',
  '3. low': '266.0000',
  '4. close': '284.3100',
  '5. volume': '34154715'},
 '2025-09-19': {'1. open': '254.0200',
  '2. high': '267.8700',
  '3. low': '254.0000',
  '4. close': '266.4000',
  '5. volume': '25569601'},
 '2025-09-12': {'1. open': '248.6300',
  '2. high': '260.6600',
  '3. low': '247.0200',
  '4. close': '253.4400',
  '5. volume': '24066143'},
 '2025-09-05': {'1. open': '240.9000',
  '2. high': '249.2800',
  '3. low': '238.2500',
  '4. close': '248.5300',
  '5. volume': '14538355'},
 '2025-08-29': {'1. open': '242.5650',
  '2. high': '245.9600',
  '3. low': '239.4300',
  '4. close': '243.4900',
  '5. volume': '18386656'},
 '2025-08-22': {'1. open': '239.5700',
  '2. high': '243.6800',
  '3. low': '238.6500',
  '4. close': '242.0900',
  '5. volume': '16264747'},
 '2025-08-15': {'1. open': '242.2400',
  '2. high': '243.1500',
  '3. low': '233.3600',
  '4. close': '239.7200',
  '5. volume': '32747166'},
 '2025-08-08': {'1. open': '251.0500',
  '2. high': '255.0000',
  '3. low': '241.6500',
  '4. close': '242.2700',
  '5. volume': '27875384'},
 '2025-08-01': {'1. open': '260.3000',
  '2. high': '265.7999',
  '3. low': '245.6100',
  '4. close': '250.0500',
  '5. volume': '29960567'},
 '2025-07-25': {'1. open': '286.2900',
  '2. high': '288.0800',
  '3. low': '252.7500',
  '4. close': '259.7200',
  '5. volume': '46388289'},
 '2025-07-18': {'1. open': '282.8300',
  '2. high': '287.1600',
  '3. low': '279.8700',
  '4. close': '285.8700',
  '5. volume': '16341671'},
 '2025-07-11': {'1. open': '292.5000',
  '2. high': '295.6100',
  '3. low': '282.2100',
  '4. close': '283.5900',
  '5. volume': '17664449'},
 '2025-07-03': {'1. open': '290.9300',
  '2. high': '295.1081',
  '3. low': '286.9000',
  '4. close': '291.9700',
  '5. volume': '11878987'},
 '2025-06-27': {'1. open': '281.6500',
  '2. high': '296.1600',
  '3. low': '280.2100',
  '4. close': '289.7000',
  '5. volume': '19051199'},
 '2025-06-20': {'1. open': '279.3050',
  '2. high': '286.9100',
  '3. low': '277.2000',
  '4. close': '280.9700',
  '5. volume': '17965949'},
 '2025-06-13': {'1. open': '268.1000',
  '2. high': '283.0600',
  '3. low': '266.7100',
  '4. close': '277.2200',
  '5. volume': '20812836'},
 '2025-06-06': {'1. open': '257.8500',
  '2. high': '270.1700',
  '3. low': '257.2200',
  '4. close': '268.8700',
  '5. volume': '13070565'},
 '2025-05-30': {'1. open': '261.0000',
  '2. high': '265.0000',
  '3. low': '256.7700',
  '4. close': '259.0600',
  '5. volume': '17566804'},
 '2025-05-23': {'1. open': '265.4500',
  '2. high': '269.2800',
  '3. low': '255.7900',
  '4. close': '258.6300',
  '5. volume': '15204641'},
 '2025-05-16': {'1. open': '252.5000',
  '2. high': '267.9800',
  '3. low': '244.6500',
  '4. close': '266.7600',
  '5. volume': '20440246'},
 '2025-05-09': {'1. open': '243.7400',
  '2. high': '256.5200',
  '3. low': '243.6400',
  '4. close': '249.2000',
  '5. volume': '16977083'},
 '2025-05-02': {'1. open': '232.8600',
  '2. high': '245.6900',
  '3. low': '232.0700',
  '4. close': '245.5500',
  '5. volume': '20198202'},
 '2025-04-25': {'1. open': '238.0650',
  '2. high': '249.3400',
  '3. low': '224.4401',
  '4. close': '232.4100',
  '5. volume': '39218052'},
 '2025-04-17': {'1. open': '239.7700',
  '2. high': '243.2999',
  '3. low': '235.8900',
  '4. close': '238.8100',
  '5. volume': '16190928'},
 '2025-04-11': {'1. open': '219.2400',
  '2. high': '237.5800',
  '3. low': '214.5000',
  '4. close': '235.4800',
  '5. volume': '31932696'},
 '2025-04-04': {'1. open': '242.7400',
  '2. high': '252.7900',
  '3. low': '226.8800',
  '4. close': '227.4800',
  '5. volume': '28005665'},
 '2025-03-28': {'1. open': '247.3100',
  '2. high': '254.3200',
  '3. low': '242.0700',
  '4. close': '244.0000',
  '5. volume': '18354282'},
 '2025-03-21': {'1. open': '249.2500',
  '2. high': '254.6300',
  '3. low': '237.2240',
  '4. close': '243.8700',
  '5. volume': '27866866'},
 '2025-03-14': {'1. open': '261.5600',
  '2. high': '266.4500',
  '3. low': '241.6800',
  '4. close': '248.3500',
  '5. volume': '25513710'},
 '2025-03-07': {'1. open': '254.7350',
  '2. high': '261.9600',
  '3. low': '245.1823',
  '4. close': '261.5400',
  '5. volume': '22284160'},
 '2025-02-28': {'1. open': '261.5000',
  '2. high': '263.8450',
  '3. low': '246.5400',
  '4. close': '252.4400',
  '5. volume': '25541761'},
 '2025-02-21': {'1. open': '261.9300',
  '2. high': '265.0900',
  '3. low': '259.8300',
  '4. close': '261.4800',
  '5. volume': '18534169'},
 '2025-02-14': {'1. open': '250.8600',
  '2. high': '261.9400',
  '3. low': '246.8700',
  '4. close': '261.2800',
  '5. volume': '19898073'},
 '2025-02-07': {'1. open': '252.4000',
  '2. high': '265.7200',
  '3. low': '251.8400',
  '4. close': '252.3400',
  '5. volume': '30149848'},
 '2025-01-31': {'1. open': '222.1900',
  '2. high': '261.8000',
  '3. low': '219.8400',
  '4. close': '255.7000',
  '5. volume': '39048997'},
 '2025-01-24': {'1. open': '224.9900',
  '2. high': '227.4500',
  '3. low': '220.3500',
  '4. close': '224.8000',
  '5. volume': '15594637'},
 '2025-01-17': {'1. open': '217.8900',
  '2. high': '225.9550',
  '3. low': '214.6100',
  '4. close': '224.7900',
  '5. volume': '18990367'},
 '2025-01-10': {'1. open': '223.0000',
  '2. high': '226.7110',
  '3. low': '216.8000',
  '4. close': '219.7500',
  '5. volume': '12337094'},
 '2025-01-03': {'1. open': '220.5400',
  '2. high': '223.6600',
  '3. low': '217.6000',
  '4. close': '222.6500',
  '5. volume': '10819153'},
 '2024-12-27': {'1. open': '222.8100',
  '2. high': '225.4000',
  '3. low': '221.0800',
  '4. close': '222.7800',
  '5. volume': '9272351'},
 '2024-12-20': {'1. open': '230.7300',
  '2. high': '231.0300',
  '3. low': '220.0300',
  '4. close': '223.3600',
  '5. volume': '28267440'},
 '2024-12-13': {'1. open': '238.0000',
  '2. high': '239.3500',
  '3. low': '227.8000',
  '4. close': '230.8200',
  '5. volume': '20886084'},
 '2024-12-06': {'1. open': '227.5000',
  '2. high': '238.3800',
  '3. low': '225.5100',
  '4. close': '238.0400',
  '5. volume': '18743737'},
 '2024-11-29': {'1. open': '223.3500',
  '2. high': '230.3600',
  '3. low': '222.6500',
  '4. close': '227.4100',
  '5. volume': '17274177'},
 '2024-11-22': {'1. open': '207.0000',
  '2. high': '227.2000',
  '3. low': '205.3701',
  '4. close': '222.9700',
  '5. volume': '21386866'},
 '2024-11-15': {'1. open': '214.4000',
  '2. high': '215.4100',
  '3. low': '204.0700',
  '4. close': '204.9900',
  '5. volume': '19438346'},
 '2024-11-08': {'1. open': '207.6500',
  '2. high': '216.7000',
  '3. low': '205.5700',
  '4. close': '213.7200',
  '5. volume': '15846890'},
 '2024-11-01': {'1. open': '215.5000',
  '2. high': '216.2500',
  '3. low': '203.5100',
  '4. close': '208.2500',
  '5. volume': '26467891'},
 '2024-10-25': {'1. open': '231.2100',
  '2. high': '233.3400',
  '3. low': '214.3850',
  '4. close': '214.6700',
  '5. volume': '31380820'},
 '2024-10-18': {'1. open': '233.5700',
  '2. high': '237.3700',
  '3. low': '230.1700',
  '4. close': '232.2000',
  '5. volume': '18477394'},
 '2024-10-11': {'1. open': '225.3800',
  '2. high': '235.8300',
  '3. low': '225.0200',
  '4. close': '233.2600',
  '5. volume': '18398213'},
 '2024-10-04': {'1. open': '220.6500',
  '2. high': '226.0800',
  '3. low': '215.7980',
  '4. close': '226.0000',
  '5. volume': '17778630'},
 '2024-09-27': {'1. open': '218.0000',
  '2. high': '224.1500',
  '3. low': '217.2700',
  '4. close': '220.8400',
  '5. volume': '16300165'},
 '2024-09-20': {'1. open': '215.8800',
  '2. high': '218.8400',
  '3. low': '210.3700',
  '4. close': '217.7000',
  '5. volume': '28532770'},
 '2024-09-13': {'1. open': '201.9400',
  '2. high': '216.0900',
  '3. low': '201.4300',
  '4. close': '214.7900',
  '5. volume': '21518747'},
 '2024-09-06': {'1. open': '201.9100',
  '2. high': '205.9500',
  '3. low': '199.3350',
  '4. close': '200.7400',
  '5. volume': '13519865'},
 '2024-08-30': {'1. open': '196.0000',
  '2. high': '202.1700',
  '3. low': '195.9000',
  '4. close': '202.1300',
  '5. volume': '15570283'},
 '2024-08-23': {'1. open': '193.8400',
  '2. high': '197.9200',
  '3. low': '193.7150',
  '4. close': '196.1000',
  '5. volume': '11022549'},
 '2024-08-16': {'1. open': '191.2500',
  '2. high': '194.3500',
  '3. low': '189.0001',
  '4. close': '193.7800',
  '5. volume': '11330854'},
 '2024-08-09': {'1. open': '184.5500',
  '2. high': '192.8800',
  '3. low': '181.8100',
  '4. close': '191.4500',
  '5. volume': '18895865'},
 '2024-08-02': {'1. open': '193.1800',
  '2. high': '194.5499',
  '3. low': '185.7000',
  '4. close': '189.1200',
  '5. volume': '20594367'},
 '2024-07-26': {'1. open': '183.4000',
  '2. high': '196.2600',
  '3. low': '182.8600',
  '4. close': '191.7500',
  '5. volume': '25458498'},
 '2024-07-19': {'1. open': '183.3800',
  '2. high': '189.4700',
  '3. low': '181.9500',
  '4. close': '183.2500',
  '5. volume': '17829469'},
 '2024-07-12': {'1. open': '176.4100',
  '2. high': '184.1600',
  '3. low': '174.4500',
  '4. close': '182.8300',
  '5. volume': '16071235'},
 '2024-07-05': {'1. open': '173.4500',
  '2. high': '177.9800',
  '3. low': '173.3800',
  '4. close': '176.0200',
  '5. volume': '9939255'},
 '2024-06-28': {'1. open': '175.0000',
  '2. high': '178.4599',
  '3. low': '170.4100',
  '4. close': '172.9500',
  '5. volume': '18850478'},
 '2024-06-21': {'1. open': '168.7600',
  '2. high': '174.9600',
  '3. low': '167.5000',
  '4. close': '172.4600',
  '5. volume': '21531360'},
 '2024-06-14': {'1. open': '169.5500',
  '2. high': '172.4700',
  '3. low': '166.8100',
  '4. close': '169.2100',
  '5. volume': '16222067'},
 '2024-06-07': {'1. open': '166.5400',
  '2. high': '171.3050',
  '3. low': '163.5300',
  '4. close': '170.0100',
  '5. volume': '14102396'},
 '2024-05-31': {'1. open': '170.4400',
  '2. high': '171.0850',
  '3. low': '163.8400',
  '4. close': '166.8500',
  '5. volume': '15594186'},
 '2024-05-24': {'1. open': '169.0000',
  '2. high': '175.4600',
  '3. low': '168.3800',
  '4. close': '170.8900',
  '5. volume': '18410125'},
 '2024-05-17': {'1. open': '167.5000',
  '2. high': '169.6300',
  '3. low': '166.4800',
  '4. close': '169.0300',
  '5. volume': '15933303'},
 '2024-05-10': {'1. open': '166.5000',
  '2. high': '170.2600',
  '3. low': '165.8800',
  '4. close': '167.1500',
  '5. volume': '17421523'},
 '2024-05-03': {'1. open': '167.4000',
  '2. high': '168.2200',
  '3. low': '162.6200',
  '4. close': '165.7100',
  '5. volume': '22536194'},
 '2024-04-26': {'1. open': '182.4500',
  '2. high': '184.6800',
  '3. low': '165.6600',
  '4. close': '167.1300',
  '5. volume': '42329269'},
 '2024-04-19': {'1. open': '185.5700',
  '2. high': '187.4800',
  '3. low': '180.1700',
  '4. close': '181.5800',
  '5. volume': '16929550'},
 '2024-04-12': {'1. open': '189.2400',
  '2. high': '191.2500',
  '3. low': '181.6850',
  '4. close': '182.2700',
  '5. volume': '14955313'},
 '2024-04-05': {'1. open': '190.0000',
  '2. high': '193.2800',
  '3. low': '187.3400',
  '4. close': '189.1400',
  '5. volume': '12808073'},
 '2024-03-28': {'1. open': '190.2600',
  '2. high': '191.9299',
  '3. low': '188.5000',
  '4. close': '190.9600',
  '5. volume': '15383298'},
 '2024-03-22': {'1. open': '191.7000',
  '2. high': '193.9800',
  '3. low': '190.0100',
  '4. close': '190.8400',
  '5. volume': '23968505'},
 '2024-03-15': {'1. open': '195.0900',
  '2. high': '199.1800',
  '3. low': '190.7000',
  '4. close': '191.0700',
  '5. volume': '27466323'},
 '2024-03-08': {'1. open': '187.7600',
  '2. high': '198.7300',
  '3. low': '187.6000',
  '4. close': '195.9500',
  '5. volume': '29085296'},
 '2024-03-01': {'1. open': '185.6000',
  '2. high': '188.3800',
  '3. low': '182.6200',
  '4. close': '188.2000',
  '5. volume': '21955379'},
 '2024-02-23': {'1. open': '187.6400',
  '2. high': '188.7700',
  '3. low': '178.7500',
  '4. close': '185.7200',
  '5. volume': '17487852'},
 '2024-02-16': {'1. open': '185.9000',
  '2. high': '188.9500',
  '3. low': '182.2600',
  '4. close': '187.6400',
  '5. volume': '21745006'},
 '2024-02-09': {'1. open': '185.5100',
  '2. high': '187.1800',
  '3. low': '181.4900',
  '4. close': '186.3400',
  '5. volume': '22784812'},
 '2024-02-02': {'1. open': '187.4600',
  '2. high': '189.4600',
  '3. low': '182.7100',
  '4. close': '185.7900',
  '5. volume': '28283876'},
 '2024-01-26': {'1. open': '172.8200',
  '2. high': '196.9000',
  '3. low': '172.4000',
  '4. close': '187.4200',
  '5. volume': '56232762'},
 '2024-01-19': {'1. open': '165.8000',
  '2. high': '171.5791',
  '3. low': '165.0400',
  '4. close': '171.4800',
  '5. volume': '19864308'},
 '2024-01-12': {'1. open': '158.6900',
  '2. high': '165.9800',
  '3. low': '157.8850',
  '4. close': '165.8000',
  '5. volume': '17643392'},
 '2024-01-05': {'1. open': '162.8300',
  '2. high': '163.2900',
  '3. low': '158.6700',
  '4. close': '159.1600',
  '5. volume': '14822074'},
 '2023-12-29': {'1. open': '162.2300',
  '2. high': '164.1800',
  '3. low': '162.0500',
  '4. close': '163.5500',
  '5. volume': '9376537'},
 '2023-12-22': {'1. open': '162.2300',
  '2. high': '163.3300',
  '3. low': '159.5300',
  '4. close': '162.1400',
  '5. volume': '17686398'},
 '2023-12-15': {'1. open': '162.6800',
  '2. high': '166.3400',
  '3. low': '160.1490',
  '4. close': '162.2300',
  '5. volume': '33504550'},
 '2023-12-08': {'1. open': '160.2900',
  '2. high': '162.7900',
  '3. low': '159.9700',
  '4. close': '161.9600',
  '5. volume': '21918957'},
 '2023-12-01': {'1. open': '154.9900',
  '2. high': '160.5900',
  '3. low': '154.7500',
  '4. close': '160.5500',
  '5. volume': '21900644'},
 '2023-11-24': {'1. open': '152.5100',
  '2. high': '155.7050',
  '3. low': '152.3500',
  '4. close': '155.1800',
  '5. volume': '11362696'},
 '2023-11-17': {'1. open': '148.4600',
  '2. high': '153.5000',
  '3. low': '147.3500',
  '4. close': '152.8900',
  '5. volume': '19547595'},
 '2023-11-10': {'1. open': '147.8900',
  '2. high': '149.6800',
  '3. low': '145.2800',
  '4. close': '149.0200',
  '5. volume': '18357944'},
 '2023-11-03': {'1. open': '143.1900',
  '2. high': '148.4450',
  '3. low': '142.5800',
  '4. close': '147.9000',
  '5. volume': '22959464'},
 '2023-10-27': {'1. open': '136.6300',
  '2. high': '144.7000',
  '3. low': '135.8700',
  '4. close': '142.5200',
  '5. volume': '30227448'},
 '2023-10-20': {'1. open': '139.2800',
  '2. high': '140.6200',
  '3. low': '136.3100',
  '4. close': '137.1600',
  '5. volume': '21044049'},
 '2023-10-13': {'1. open': '142.3000',
  '2. high': '143.4150',
  '3. low': '138.2700',
  '4. close': '138.4600',
  '5. volume': '16386334'},
 '2023-10-06': {'1. open': '140.0400',
  '2. high': '142.9400',
  '3. low': '139.8600',
  '4. close': '142.0300',
  '5. volume': '15932918'},
 '2023-09-29': {'1. open': '146.5700',
  '2. high': '147.4300',
  '3. low': '139.6100',
  '4. close': '140.3000',

In [8]:
# Prompt: Convert the above into pandas dataframe

import pandas as pd

# 1. Load the data into a DataFrame with dates as rows
df = pd.DataFrame.from_dict(data["Weekly Time Series"], orient="index")
df

             1. open   2. high    3. low  4. close 5. volume
2026-06-05  322.5500  332.4600  281.0701  284.8400  86135011
2026-05-29  254.5500  300.9999  245.4500  297.8000  59445527
2026-05-22  218.5500  264.3800  216.7800  253.8400  61523775
2026-05-15  228.6600  230.2300  212.3400  219.3000  33144274
2026-05-08  232.0000  234.0900  224.3800  229.7600  26716501
...              ...       ...       ...       ...       ...
1999-12-10  113.0000  122.1200  107.5600  109.0000  58626000
1999-12-03  104.9400  112.8700  102.1200  111.8700  37670000
1999-11-26  105.5000  109.8700  101.8100  105.0000  37165600
1999-11-19   96.0000  105.1200   92.6200  103.9400  61550800
1999-11-12   90.5000   97.5000   90.5000   95.8700  43569700

[1387 rows x 5 columns]

In [9]:

# 2. Optional clean-up steps for better usability

# Convert the index to Datetime objects
df.index = pd.to_datetime(df.index)    

# Convert string values to numeric numbers
df = df.astype(float)

# Strip "1. ", "2. " prefixes from headers
df.columns = [col.split('. ')[1] for col in df.columns]

In [10]:
df.head()

              open      high       low   close      volume
2026-06-05  322.55  332.4600  281.0701  284.84  86135011.0
2026-05-29  254.55  300.9999  245.4500  297.80  59445527.0
2026-05-22  218.55  264.3800  216.7800  253.84  61523775.0
2026-05-15  228.66  230.2300  212.3400  219.30  33144274.0
2026-05-08  232.00  234.0900  224.3800  229.76  26716501.0

# 2) Company Fundamentals
```
Market Capitalization
PE Ratio
EPS
Revenue
Profit Margins
Dividend Yield

In [11]:
TICKER='MSFT'
url = f"https://www.alphavantage.co/query?function=OVERVIEW&symbol={TICKER}&apikey={ALPHAADVANTAGE_API_KEY}"

data = requests.get(url).json()

In [12]:
data

{'Symbol': 'MSFT',
 'AssetType': 'Common Stock',
 'Name': 'Microsoft Corporation',
 'Description': "Microsoft Corporation is an American multinational technology company which produces computer software, consumer electronics, personal computers, and related services. Its best known software products are the Microsoft Windows line of operating systems, the Microsoft Office suite, and the Internet Explorer and Edge web browsers. Its flagship hardware products are the Xbox video game consoles and the Microsoft Surface lineup of touchscreen personal computers. Microsoft ranked No. 21 in the 2020 Fortune 500 rankings of the largest United States corporations by total revenue; it was the world's largest software maker by revenue as of 2016. It is considered one of the Big Five companies in the U.S. information technology industry, along with Google, Apple, Amazon, and Facebook.",
 'CIK': '789019',
 'Exchange': 'NASDAQ',
 'Currency': 'USD',
 'Country': 'USA',
 'Sector': 'TECHNOLOGY',
 'Industry': 'SOFTWARE - INFRASTRUCTURE',
 'Address': 'ONE MICROSOFT WAY, REDMOND, WA, UNITED STATES, 98052-6399',
 'OfficialSite': 'https://www.microsoft.com',
 'FiscalYearEnd': 'June',
 'LatestQuarter': '2026-03-31',
 'MarketCapitalization': '3095206035000',
 'EBITDA': '184457003000',
 'PERatio': '24.82',
 'PEGRatio': '1.284',
 'BookValue': '55.78',
 'DividendPerShare': '3.56',
 'DividendYield': '0.0083',
 'EPS': '16.79',
 'RevenuePerShareTTM': '42.84',
 'ProfitMargin': '0.393',
 'OperatingMarginTTM': '0.463',
 'ReturnOnAssetsTTM': '0.148',
 'ReturnOnEquityTTM': '0.34',
 'RevenueTTM': '318272995000',
 'GrossProfitTTM': '217409995000',
 'DilutedEPSTTM': '16.79',
 'QuarterlyEarningsGrowthYOY': '0.234',
 'QuarterlyRevenueGrowthYOY': '0.183',
 'AnalystTargetPrice': '560.95',
 'AnalystRatingStrongBuy': '12',
 'AnalystRatingBuy': '40',
 'AnalystRatingHold': '3',
 'AnalystRatingSell': '0',
 'AnalystRatingStrongSell': '0',
 'TrailingPE': '24.82',
 'ForwardPE': '21.46',
 'PriceToSalesRatioTTM': '9.72',
 'PriceToBookRatio': '7.47',
 'EVToRevenue': '9.66',
 'EVToEBITDA': '15.46',
 'Beta': '1.103',
 '52WeekHigh': '551.05',
 '52WeekLow': '355.51',
 '50DayMovingAverage': '406.33',
 '200DayMovingAverage': '457.29',
 'SharesOutstanding': '7428435000',
 'SharesFloat': '7417515000',
 'PercentInsiders': '0.080',
 'PercentInstitutions': '75.767',
 'DividendDate': '2026-06-11',
 'ExDividendDate': '2026-05-21'}

In [13]:
# Lets see the keys

data.keys()

dict_keys(['Symbol', 'AssetType', 'Name', 'Description', 'CIK', 'Exchange', 'Currency', 'Country', 'Sector', 'Industry', 'Address', 'OfficialSite', 'FiscalYearEnd', 'LatestQuarter', 'MarketCapitalization', 'EBITDA', 'PERatio', 'PEGRatio', 'BookValue', 'DividendPerShare', 'DividendYield', 'EPS', 'RevenuePerShareTTM', 'ProfitMargin', 'OperatingMarginTTM', 'ReturnOnAssetsTTM', 'ReturnOnEquityTTM', 'RevenueTTM', 'GrossProfitTTM', 'DilutedEPSTTM', 'QuarterlyEarningsGrowthYOY', 'QuarterlyRevenueGrowthYOY', 'AnalystTargetPrice', 'AnalystRatingStrongBuy', 'AnalystRatingBuy', 'AnalystRatingHold', 'AnalystRatingSell', 'AnalystRatingStrongSell', 'TrailingPE', 'ForwardPE', 'PriceToSalesRatioTTM', 'PriceToBookRatio', 'EVToRevenue', 'EVToEBITDA', 'Beta', '52WeekHigh', '52WeekLow', '50DayMovingAverage', '200DayMovingAverage', 'SharesOutstanding', 'SharesFloat', 'PercentInsiders', 'PercentInstitutions', 'DividendDate', 'ExDividendDate'])

In [14]:
# Lets access few keys

print(data["Name"])
print(data["PERatio"])
print(data["ProfitMargin"])
print(data["MarketCapitalization"])

Microsoft Corporation
24.82
0.393
3095206035000

In [15]:
# prettify

formatted_value = f"${int(data['MarketCapitalization']):,}  Trillion"
# formatted_value = f"${int(data['MarketCapitalization']):,} (${int(data['MarketCapitalization']) / 1e12:.2f} Trillion)"

print(formatted_value)

$3,095,206,035,000  Trillion

# 3) Income Statement Analysis
```
Real company financial statements:

Revenue
Operating Income
Net Income

In [16]:
TICKER='MSFT'

url = f"https://www.alphavantage.co/query?function=INCOME_STATEMENT&symbol={TICKER}&apikey={ALPHAADVANTAGE_API_KEY}"

data = requests.get(url).json()

In [17]:
data

{'symbol': 'MSFT',
 'annualReports': [{'fiscalDateEnding': '2025-06-30',
   'reportedCurrency': 'USD',
   'grossProfit': '193893000000',
   'totalRevenue': '281724000000',
   'costOfRevenue': '87831000000',
   'costofGoodsAndServicesSold': '87831000000',
   'operatingIncome': '128528000000',
   'sellingGeneralAndAdministrative': '7223000000',
   'researchAndDevelopment': '32488000000',
   'operatingExpenses': '65365000000',
   'investmentIncomeNet': 'None',
   'netInterestIncome': '262000000',
   'interestIncome': '767000000',
   'interestExpense': '2385000000',
   'nonInterestIncome': 'None',
   'otherNonOperatingIncome': 'None',
   'depreciation': 'None',
   'depreciationAndAmortization': '34153000000',
   'incomeBeforeTax': '123627000000',
   'incomeTaxExpense': '21795000000',
   'interestAndDebtExpense': 'None',
   'netIncomeFromContinuingOperations': '101832000000',
   'comprehensiveIncomeNetOfTax': 'None',
   'ebit': '126012000000',
   'ebitda': '160165000000',
   'netIncome': '101832000000'},
  {'fiscalDateEnding': '2024-06-30',
   'reportedCurrency': 'USD',
   'grossProfit': '171008000000',
   'totalRevenue': '245122000000',
   'costOfRevenue': '74114000000',
   'costofGoodsAndServicesSold': '74114000000',
   'operatingIncome': '109433000000',
   'sellingGeneralAndAdministrative': '7609000000',
   'researchAndDevelopment': '29510000000',
   'operatingExpenses': '61575000000',
   'investmentIncomeNet': 'None',
   'netInterestIncome': '222000000',
   'interestIncome': '3157000000',
   'interestExpense': '2935000000',
   'nonInterestIncome': 'None',
   'otherNonOperatingIncome': 'None',
   'depreciation': 'None',
   'depreciationAndAmortization': '22287000000',
   'incomeBeforeTax': '107787000000',
   'incomeTaxExpense': '19651000000',
   'interestAndDebtExpense': 'None',
   'netIncomeFromContinuingOperations': '88136000000',
   'comprehensiveIncomeNetOfTax': 'None',
   'ebit': '110722000000',
   'ebitda': '133009000000',
   'netIncome': '88136000000'},
  {'fiscalDateEnding': '2023-06-30',
   'reportedCurrency': 'USD',
   'grossProfit': '146052000000',
   'totalRevenue': '211915000000',
   'costOfRevenue': '65863000000',
   'costofGoodsAndServicesSold': '65863000000',
   'operatingIncome': '88523000000',
   'sellingGeneralAndAdministrative': '7575000000',
   'researchAndDevelopment': '27195000000',
   'operatingExpenses': '57529000000',
   'investmentIncomeNet': 'None',
   'netInterestIncome': '1026000000',
   'interestIncome': '1041000000',
   'interestExpense': '1968000000',
   'nonInterestIncome': 'None',
   'otherNonOperatingIncome': 'None',
   'depreciation': 'None',
   'depreciationAndAmortization': '13861000000',
   'incomeBeforeTax': '89311000000',
   'incomeTaxExpense': '16950000000',
   'interestAndDebtExpense': 'None',
   'netIncomeFromContinuingOperations': '72361000000',
   'comprehensiveIncomeNetOfTax': 'None',
   'ebit': '91279000000',
   'ebitda': '105140000000',
   'netIncome': '72361000000'},
  {'fiscalDateEnding': '2022-06-30',
   'reportedCurrency': 'USD',
   'grossProfit': '135620000000',
   'totalRevenue': '198270000000',
   'costOfRevenue': '62650000000',
   'costofGoodsAndServicesSold': '62650000000',
   'operatingIncome': '83383000000',
   'sellingGeneralAndAdministrative': '5900000000',
   'researchAndDevelopment': '24512000000',
   'operatingExpenses': '52237000000',
   'investmentIncomeNet': 'None',
   'netInterestIncome': '31000000',
   'interestIncome': '2094000000',
   'interestExpense': '2063000000',
   'nonInterestIncome': 'None',
   'otherNonOperatingIncome': '333000000',
   'depreciation': 'None',
   'depreciationAndAmortization': '14460000000',
   'incomeBeforeTax': '83716000000',
   'incomeTaxExpense': '10978000000',
   'interestAndDebtExpense': 'None',
   'netIncomeFromContinuingOperations': '72738000000',
   'comprehensiveIncomeNetOfTax': 'None',
   'ebit': '85779000000',
   'ebitda': '100239000000',
   'netIncome': '72738000000'},
  {'fiscalDateEnding': '2021-06-30',
   'reportedCurrency': 'USD',
   'grossProfit': '115856000000',
   'totalRevenue': '168088000000',
   'costOfRevenue': '52232000000',
   'costofGoodsAndServicesSold': '52232000000',
   'operatingIncome': '69916000000',
   'sellingGeneralAndAdministrative': '5107000000',
   'researchAndDevelopment': '20716000000',
   'operatingExpenses': '45940000000',
   'investmentIncomeNet': 'None',
   'netInterestIncome': '-215000000',
   'interestIncome': '2131000000',
   'interestExpense': '2346000000',
   'nonInterestIncome': 'None',
   'otherNonOperatingIncome': '1186000000',
   'depreciation': 'None',
   'depreciationAndAmortization': '11686000000',
   'incomeBeforeTax': '71102000000',
   'incomeTaxExpense': '9831000000',
   'interestAndDebtExpense': 'None',
   'netIncomeFromContinuingOperations': '61271000000',
   'comprehensiveIncomeNetOfTax': 'None',
   'ebit': '73448000000',
   'ebitda': '85134000000',
   'netIncome': '61271000000'},
  {'fiscalDateEnding': '2020-06-30',
   'reportedCurrency': 'USD',
   'grossProfit': '96937000000',
   'totalRevenue': '143015000000',
   'costOfRevenue': '46078000000',
   'costofGoodsAndServicesSold': '46078000000',
   'operatingIncome': '52959000000',
   'sellingGeneralAndAdministrative': '5111000000',
   'researchAndDevelopment': '19269000000',
   'operatingExpenses': '43978000000',
   'investmentIncomeNet': 'None',
   'netInterestIncome': '-2591000000',
   'interestIncome': '2680000000',
   'interestExpense': '2591000000',
   'nonInterestIncome': 'None',
   'otherNonOperatingIncome': '77000000',
   'depreciation': 'None',
   'depreciationAndAmortization': '12796000000',
   'incomeBeforeTax': '53036000000',
   'incomeTaxExpense': '8755000000',
   'interestAndDebtExpense': 'None',
   'netIncomeFromContinuingOperations': '44281000000',
   'comprehensiveIncomeNetOfTax': 'None',
   'ebit': '55627000000',
   'ebitda': '68423000000',
   'netIncome': '44281000000'},
  {'fiscalDateEnding': '2019-06-30',
   'reportedCurrency': 'USD',
   'grossProfit': '82933000000',
   'totalRevenue': '125843000000',
   'costOfRevenue': '42910000000',
   'costofGoodsAndServicesSold': '42910000000',
   'operatingIncome': '42959000000',
   'sellingGeneralAndAdministrative': '4885000000',
   'researchAndDevelopment': '16876000000',
   'operatingExpenses': '39974000000',
   'investmentIncomeNet': 'None',
   'netInterestIncome': '-2686000000',
   'interestIncome': '812000000',
   'interestExpense': '2686000000',
   'nonInterestIncome': 'None',
   'otherNonOperatingIncome': '729000000',
   'depreciation': 'None',
   'depreciationAndAmortization': '11682000000',
   'incomeBeforeTax': '43688000000',
   'incomeTaxExpense': '4448000000',
   'interestAndDebtExpense': 'None',
   'netIncomeFromContinuingOperations': '39240000000',
   'comprehensiveIncomeNetOfTax': 'None',
   'ebit': '46374000000',
   'ebitda': '58056000000',
   'netIncome': '39240000000'},
  {'fiscalDateEnding': '2018-06-30',
   'reportedCurrency': 'USD',
   'grossProfit': '72007000000',
   'totalRevenue': '110360000000',
   'costOfRevenue': '38353000000',
   'costofGoodsAndServicesSold': '38353000000',
   'operatingIncome': '35058000000',
   'sellingGeneralAndAdministrative': '4754000000',
   'researchAndDevelopment': '14726000000',
   'operatingExpenses': '36949000000',
   'investmentIncomeNet': 'None',
   'netInterestIncome': '-2733000000',
   'interestIncome': '1522000000',
   'interestExpense': '2733000000',
   'nonInterestIncome': 'None',
   'otherNonOperatingIncome': '1416000000',
   'depreciation': 'None',
   'depreciationAndAmortization': '10261000000',
   'incomeBeforeTax': '36474000000',
   'incomeTaxExpense': '19903000000',
   'interestAndDebtExpense': 'None',
   'netIncomeFromContinuingOperations': '16571000000',
   'comprehensiveIncomeNetOfTax': 'None',
   'ebit': '39207000000',
   'ebitda': '49468000000',
   'netIncome': '16571000000'},
  {'fiscalDateEnding': '2017-06-30',
   'reportedCurrency': 'USD',
   'grossProfit': '62310000000',
   'totalRevenue': '96571000000',
   'costOfRevenue': '34261000000',
   'costofGoodsAndServicesSold': '34261000000',
   'operatingIncome': '29025000000',
   'sellingGeneralAndAdministrative': '4481000000',
   'researchAndDevelopment': '13037000000',
   'operatingExpenses': '32979000000',
   'investmentIncomeNet': 'None',
   'netInterestIncome': '-2222000000',
   'interestIncome': '1182000000',
   'interestExpense': '2222000000',
   'nonInterestIncome': 'None',
   'otherNonOperatingIncome': '823000000',
   'depreciation': 'None',
   'depreciationAndAmortization': '8778000000',
   'incomeBeforeTax': '29901000000',
   'incomeTaxExpense': '4412000000',
   'interestAndDebtExpense': 'None',
   'netIncomeFromContinuingOperations': '21204000000',
   'comprehensiveIncomeNetOfTax': 'None',
   'ebit': '32123000000',
   'ebitda': '40901000000',
   'netIncome': '25489000000'},
  {'fiscalDateEnding': '2016-06-30',
   'reportedCurrency': 'USD',
   'grossProfit': '58374000000',
   'totalRevenue': '91154000000',
   'costOfRevenue': '32780000000',
   'costofGoodsAndServicesSold': '32780000000',
   'operatingIncome': '26078000000',
   'sellingGeneralAndAdministrative': '4563000000',
   'researchAndDevelopment': '11988000000',
   'operatingExpenses': '32296000000',
   'investmentIncomeNet': 'None',
   'netInterestIncome': '-1243000000',
   'interestIncome': '78000000',
   'interestExpense': '1243000000',
   'nonInterestIncome': 'None',
   'otherNonOperatingIncome': '-431000000',
   'depreciation': 'None',
   'depreciationAndAmortization': '6622000000',
   'incomeBeforeTax': '25639000000',
   'incomeTaxExpense': '5100000000',
   'interestAndDebtExpense': 'None',
   'netIncomeFromContinuingOperations': '16798000000',
   'comprehensiveIncomeNetOfTax': 'None',
   'ebit': '26882000000',
   'ebitda': '33504000000',
   'netIncome': '20539000000'},
  {'fiscalDateEnding': '2015-06-30',
   'reportedCurrency': 'USD',
   'grossProfit': '60542000000',
   'totalRevenue': '93580000000',
   'costOfRevenue': '33038000000',
   'costofGoodsAndServicesSold': '33038000000',
   'operatingIncome': '18161000000',
   'sellingGeneralAndAdministrative': '4611000000',
   'researchAndDevelopment': '12046000000',
   'operatingExpenses': '42381000000',
   'investmentIncomeNet': 'None',
   'netInterestIncome': 'None',
   'interestIncome': 'None',
   'interestExpense': '781000000',
   'nonInterestIncome': 'None',
   'otherNonOperatingIncome': '346000000',
   'depreciation': 'None',
   'depreciationAndAmortization': '5957000000',
   'incomeBeforeTax': '18507000000',
   'incomeTaxExpense': '6314000000',
   'interestAndDebtExpense': 'None',
   'netIncomeFromContinuingOperations': '12193000000',
   'comprehensiveIncomeNetOfTax': 'None',
   'ebit': '19288000000',
   'ebitda': '25245000000',
   'netIncome': '12193000000'},
  {'fiscalDateEnding': '2014-06-30',
   'reportedCurrency': 'USD',
   'grossProfit': '59755000000',
   'totalRevenue': '86833000000',
   'costOfRevenue': '27078000000',
   'costofGoodsAndServicesSold': '27078000000',
   'operatingIncome': '27759000000',
   'sellingGeneralAndAdministrative': '4677000000',
   'researchAndDevelopment': '11381000000',
   'operatingExpenses': '31869000000',
   'investmentIncomeNet': 'None',
   'netInterestIncome': 'None',
   'interestIncome': 'None',
   'interestExpense': '597000000',
   'nonInterestIncome': 'None',
   'otherNonOperatingIncome': '61000000',
   'depreciation': 'None',
   'depreciationAndAmortization': '5212000000',
   'incomeBeforeTax': '27820000000',
   'incomeTaxExpense': '5746000000',
   'interestAndDebtExpense': 'None',
   'netIncomeFromContinuingOperations': '22074000000',
   'comprehensiveIncomeNetOfTax': 'None',
   'ebit': '28417000000',
   'ebitda': '33629000000',
   'netIncome': '22074000000'},
  {'fiscalDateEnding': '2013-06-30',
   'reportedCurrency': 'USD',
   'grossProfit': '57464000000',
   'totalRevenue': '77849000000',
   'costOfRevenue': '20385000000',
   'costofGoodsAndServicesSold': '20385000000',
   'operatingIncome': '26764000000',
   'sellingGeneralAndAdministrative': '5013000000',
   'researchAndDevelopment': '10411000000',
   'operatingExpenses': '30700000000',
   'investmentIncomeNet': 'None',
   'netInterestIncome': 'None',
   'interestIncome': 'None',
   'interestExpense': '429000000',
   'nonInterestIncome': 'None',
   'otherNonOperatingIncome': '288000000',
   'depreciation': 'None',
   'depreciationAndAmortization': '3755000000',
   'incomeBeforeTax': '27052000000',
   'incomeTaxExpense': '5189000000',
   'interestAndDebtExpense': 'None',
   'netIncomeFromContinuingOperations': '21863000000',
   'comprehensiveIncomeNetOfTax': 'None',
   'ebit': '27481000000',
   'ebitda': '31236000000',
   'netIncome': '21863000000'},
  {'fiscalDateEnding': '2012-06-30',
   'reportedCurrency': 'USD',
   'grossProfit': '56193000000',
   'totalRevenue': '73723000000',
   'costOfRevenue': '17530000000',
   'costofGoodsAndServicesSold': '17530000000',
   'operatingIncome': '21763000000',
   'sellingGeneralAndAdministrative': '4569000000',
   'researchAndDevelopment': '9811000000',
   'operatingExpenses': '28237000000',
   'investmentIncomeNet': 'None',
   'netInterestIncome': 'None',
   'interestIncome': 'None',
   'interestExpense': '380000000',
   'nonInterestIncome': 'None',
   'otherNonOperatingIncome': '504000000',
   'depreciation': 'None',
   'depreciationAndAmortization': '2967000000',
   'incomeBeforeTax': '22267000000',
   'incomeTaxExpense': '5289000000',
   'interestAndDebtExpense': 'None',
   'netIncomeFromContinuingOperations': '16978000000',
   'comprehensiveIncomeNetOfTax': 'None',
   'ebit': '22647000000',
   'ebitda': '25614000000',
   'netIncome': '16978000000'},
  {'fiscalDateEnding': '2011-06-30',
   'reportedCurrency': 'USD',
   'grossProfit': '54366000000',
   'totalRevenue': '69943000000',
   'costOfRevenue': '15577000000',
   'costofGoodsAndServicesSold': '15577000000',
   'operatingIncome': '27161000000',
   'sellingGeneralAndAdministrative': '4222000000',
   'researchAndDevelopment': '9043000000',
   'operatingExpenses': '27205000000',
   'investmentIncomeNet': 'None',
   'netInterestIncome': 'None',
   'interestIncome': 'None',
   'interestExpense': '295000000',
   'nonInterestIncome': 'None',
   'otherNonOperatingIncome': '910000000',
   'depreciation': 'None',
   'depreciationAndAmortization': '2766000000',
   'incomeBeforeTax': '28071000000',
   'incomeTaxExpense': '4921000000',
   'interestAndDebtExpense': 'None',
   'netIncomeFromContinuingOperations': '23150000000',
   'comprehensiveIncomeNetOfTax': 'None',
   'ebit': '28366000000',
   'ebitda': '31132000000',
   'netIncome': '23150000000'},
  {'fiscalDateEnding': '2010-06-30',
   'reportedCurrency': 'USD',
   'grossProfit': '50089000000',
   'totalRevenue': '62484000000',
   'costOfRevenue': '12395000000',
   'costofGoodsAndServicesSold': '12395000000',
   'operatingIncome': '24098000000',
   'sellingGeneralAndAdministrative': '4063000000',
   'researchAndDevelopment': '8714000000',
   'operatingExpenses': '25991000000',
   'investmentIncomeNet': 'None',
   'netInterestIncome': 'None',
   'interestIncome': 'None',
   'interestExpense': '151000000',
   'nonInterestIncome': 'None',
   'otherNonOperatingIncome': '915000000',
   'depreciation': 'None',
   'depreciationAndAmortization': '2673000000',
   'incomeBeforeTax': '25013000000',
   'incomeTaxExpense': '6253000000',
   'interestAndDebtExpense': 'None',
   'netIncomeFromContinuingOperations': '18760000000',
   'comprehensiveIncomeNetOfTax': 'None',
   'ebit': '25164000000',
   'ebitda': '27837000000',
   'netIncome': '18760000000'},
  {'fiscalDateEnding': '2009-06-30',
   'reportedCurrency': 'USD',
   'grossProfit': '46282000000',
   'totalRevenue': '58437000000',
   'costOfRevenue': '12155000000',
   'costofGoodsAndServicesSold': '12155000000',
   'operatingIncome': '20363000000',
   'sellingGeneralAndAdministrative': '4030000000',
   'researchAndDevelopment': '9010000000',
   'operatingExpenses': '25919000000',
   'investmentIncomeNet': 'None',
   'netInterestIncome': 'None',
   'interestIncome': 'None',
   'interestExpense': '38000000',
   'nonInterestIncome': 'None',
   'otherNonOperatingIncome': 'None',
   'depreciation': 'None',
   'depreciationAndAmortization': '2562000000',
   'incomeBeforeTax': '19821000000',
   'incomeTaxExpense': '5252000000',
   'interestAndDebtExpense': 'None',
   'netIncomeFromContinuingOperations': 'None',
   'comprehensiveIncomeNetOfTax': 'None',
   'ebit': '19859000000',
   'ebitda': '22421000000',
   'netIncome': '14569000000'},
  {'fiscalDateEnding': '2008-06-30',
   'reportedCurrency': 'USD',
   'grossProfit': '48822000000',
   'totalRevenue': '60420000000',
   'costOfRevenue': '11598000000',
   'costofGoodsAndServicesSold': '11598000000',
   'operatingIncome': '22271000000',
   'sellingGeneralAndAdministrative': '5127000000',
   'researchAndDevelopment': '8164000000',
   'operatingExpenses': '26551000000',
   'investmentIncomeNet': 'None',
   'netInterestIncome': 'None',
   'interestIncome': 'None',
   'interestExpense': '106000000',
   'nonInterestIncome': 'None',
   'otherNonOperatingIncome': 'None',
   'depreciation': 'None',
   'depreciationAndAmortization': '2056000000',
   'incomeBeforeTax': '23814000000',
   'incomeTaxExpense': '6133000000',
   'interestAndDebtExpense': 'None',
   'netIncomeFromContinuingOperations': 'None',
   'comprehensiveIncomeNetOfTax': 'None',
   'ebit': '23920000000',
   'ebitda': '25976000000',
   'netIncome': '17681000000'},
  {'fiscalDateEnding': '2007-06-30',
   'reportedCurrency': 'USD',
   'grossProfit': '40429000000',
   'totalRevenue': '51122000000',
   'costOfRevenue': '10693000000',
   'costofGoodsAndServicesSold': '10693000000',
   'operatingIncome': '18438000000',
   'sellingGeneralAndAdministrative': '3329000000',
   'researchAndDevelopment': '7121000000',
   'operatingExpenses': '21991000000',
   'investmentIncomeNet': 'None',
   'netInterestIncome': 'None',
   'interestIncome': 'None',
   'interestExpense': '0',
   'nonInterestIncome': 'None',
   'otherNonOperatingIncome': 'None',
   'depreciation': 'None',
   'depreciationAndAmortization': '1440000000',
   'incomeBeforeTax': '20101000000',
   'incomeTaxExpense': '6036000000',
   'interestAndDebtExpense': 'None',
   'netIncomeFromContinuingOperations': 'None',
   'comprehensiveIncomeNetOfTax': 'None',
   'ebit': '18438000000',
   'ebitda': '19878000000',
   'netIncome': '14065000000'},
  {'fiscalDateEnding': '2006-06-30',
   'reportedCurrency': 'USD',
   'grossProfit': '36632000000',
   'totalRevenue': '44282000000',
   'costOfRevenue': '7650000000',
   'costofGoodsAndServicesSold': '7650000000',
   'operatingIncome': '16472000000',
   'sellingGeneralAndAdministrative': '3758000000',
   'researchAndDevelopment': '6584000000',
   'operatingExpenses': '20160000000',
   'investmentIncomeNet': 'None',
   'netInterestIncome': 'None',
   'interestIncome': 'None',
   'interestExpense': '0',
   'nonInterestIncome': 'None',
   'otherNonOperatingIncome': 'None',
   'depreciation': 'None',
   'depreciationAndAmortization': '903000000',
   'incomeBeforeTax': '18262000000',
   'incomeTaxExpense': '5663000000',
   'interestAndDebtExpense': 'None',
   'netIncomeFromContinuingOperations': 'None',
   'comprehensiveIncomeNetOfTax': 'None',
   'ebit': '16472000000',
   'ebitda': '17375000000',
   'netIncome': '12599000000'}],
 'quarterlyReports': [{'fiscalDateEnding': '2026-03-31',
   'reportedCurrency': 'USD',
   'grossProfit': '56058000000',
   'totalRevenue': '82886000000',
   'costOfRevenue': '26828000000',
   'costofGoodsAndServicesSold': '26828000000',
   'operatingIncome': '38398000000',
   'sellingGeneralAndAdministrative': '1931000000',
   'researchAndDevelopment': '8915000000',
   'operatingExpenses': '17660000000',
   'investmentIncomeNet': 'None',
   'netInterestIncome': '-48000000',
   'interestIncome': '730000000',
   'interestExpense': '778000000',
   'nonInterestIncome': 'None',
   'otherNonOperatingIncome': 'None',

In [18]:
# Lets see the keys

data.keys()

dict_keys(['symbol', 'annualReports', 'quarterlyReports'])

In [19]:
data['symbol']

'MSFT'

In [20]:
data['annualReports']

[{'fiscalDateEnding': '2025-06-30',
  'reportedCurrency': 'USD',
  'grossProfit': '193893000000',
  'totalRevenue': '281724000000',
  'costOfRevenue': '87831000000',
  'costofGoodsAndServicesSold': '87831000000',
  'operatingIncome': '128528000000',
  'sellingGeneralAndAdministrative': '7223000000',
  'researchAndDevelopment': '32488000000',
  'operatingExpenses': '65365000000',
  'investmentIncomeNet': 'None',
  'netInterestIncome': '262000000',
  'interestIncome': '767000000',
  'interestExpense': '2385000000',
  'nonInterestIncome': 'None',
  'otherNonOperatingIncome': 'None',
  'depreciation': 'None',
  'depreciationAndAmortization': '34153000000',
  'incomeBeforeTax': '123627000000',
  'incomeTaxExpense': '21795000000',
  'interestAndDebtExpense': 'None',
  'netIncomeFromContinuingOperations': '101832000000',
  'comprehensiveIncomeNetOfTax': 'None',
  'ebit': '126012000000',
  'ebitda': '160165000000',
  'netIncome': '101832000000'},
 {'fiscalDateEnding': '2024-06-30',
  'reportedCurrency': 'USD',
  'grossProfit': '171008000000',
  'totalRevenue': '245122000000',
  'costOfRevenue': '74114000000',
  'costofGoodsAndServicesSold': '74114000000',
  'operatingIncome': '109433000000',
  'sellingGeneralAndAdministrative': '7609000000',
  'researchAndDevelopment': '29510000000',
  'operatingExpenses': '61575000000',
  'investmentIncomeNet': 'None',
  'netInterestIncome': '222000000',
  'interestIncome': '3157000000',
  'interestExpense': '2935000000',
  'nonInterestIncome': 'None',
  'otherNonOperatingIncome': 'None',
  'depreciation': 'None',
  'depreciationAndAmortization': '22287000000',
  'incomeBeforeTax': '107787000000',
  'incomeTaxExpense': '19651000000',
  'interestAndDebtExpense': 'None',
  'netIncomeFromContinuingOperations': '88136000000',
  'comprehensiveIncomeNetOfTax': 'None',
  'ebit': '110722000000',
  'ebitda': '133009000000',
  'netIncome': '88136000000'},
 {'fiscalDateEnding': '2023-06-30',
  'reportedCurrency': 'USD',
  'grossProfit': '146052000000',
  'totalRevenue': '211915000000',
  'costOfRevenue': '65863000000',
  'costofGoodsAndServicesSold': '65863000000',
  'operatingIncome': '88523000000',
  'sellingGeneralAndAdministrative': '7575000000',
  'researchAndDevelopment': '27195000000',
  'operatingExpenses': '57529000000',
  'investmentIncomeNet': 'None',
  'netInterestIncome': '1026000000',
  'interestIncome': '1041000000',
  'interestExpense': '1968000000',
  'nonInterestIncome': 'None',
  'otherNonOperatingIncome': 'None',
  'depreciation': 'None',
  'depreciationAndAmortization': '13861000000',
  'incomeBeforeTax': '89311000000',
  'incomeTaxExpense': '16950000000',
  'interestAndDebtExpense': 'None',
  'netIncomeFromContinuingOperations': '72361000000',
  'comprehensiveIncomeNetOfTax': 'None',
  'ebit': '91279000000',
  'ebitda': '105140000000',
  'netIncome': '72361000000'},
 {'fiscalDateEnding': '2022-06-30',
  'reportedCurrency': 'USD',
  'grossProfit': '135620000000',
  'totalRevenue': '198270000000',
  'costOfRevenue': '62650000000',
  'costofGoodsAndServicesSold': '62650000000',
  'operatingIncome': '83383000000',
  'sellingGeneralAndAdministrative': '5900000000',
  'researchAndDevelopment': '24512000000',
  'operatingExpenses': '52237000000',
  'investmentIncomeNet': 'None',
  'netInterestIncome': '31000000',
  'interestIncome': '2094000000',
  'interestExpense': '2063000000',
  'nonInterestIncome': 'None',
  'otherNonOperatingIncome': '333000000',
  'depreciation': 'None',
  'depreciationAndAmortization': '14460000000',
  'incomeBeforeTax': '83716000000',
  'incomeTaxExpense': '10978000000',
  'interestAndDebtExpense': 'None',
  'netIncomeFromContinuingOperations': '72738000000',
  'comprehensiveIncomeNetOfTax': 'None',
  'ebit': '85779000000',
  'ebitda': '100239000000',
  'netIncome': '72738000000'},
 {'fiscalDateEnding': '2021-06-30',
  'reportedCurrency': 'USD',
  'grossProfit': '115856000000',
  'totalRevenue': '168088000000',
  'costOfRevenue': '52232000000',
  'costofGoodsAndServicesSold': '52232000000',
  'operatingIncome': '69916000000',
  'sellingGeneralAndAdministrative': '5107000000',
  'researchAndDevelopment': '20716000000',
  'operatingExpenses': '45940000000',
  'investmentIncomeNet': 'None',
  'netInterestIncome': '-215000000',
  'interestIncome': '2131000000',
  'interestExpense': '2346000000',
  'nonInterestIncome': 'None',
  'otherNonOperatingIncome': '1186000000',
  'depreciation': 'None',
  'depreciationAndAmortization': '11686000000',
  'incomeBeforeTax': '71102000000',
  'incomeTaxExpense': '9831000000',
  'interestAndDebtExpense': 'None',
  'netIncomeFromContinuingOperations': '61271000000',
  'comprehensiveIncomeNetOfTax': 'None',
  'ebit': '73448000000',
  'ebitda': '85134000000',
  'netIncome': '61271000000'},
 {'fiscalDateEnding': '2020-06-30',
  'reportedCurrency': 'USD',
  'grossProfit': '96937000000',
  'totalRevenue': '143015000000',
  'costOfRevenue': '46078000000',
  'costofGoodsAndServicesSold': '46078000000',
  'operatingIncome': '52959000000',
  'sellingGeneralAndAdministrative': '5111000000',
  'researchAndDevelopment': '19269000000',
  'operatingExpenses': '43978000000',
  'investmentIncomeNet': 'None',
  'netInterestIncome': '-2591000000',
  'interestIncome': '2680000000',
  'interestExpense': '2591000000',
  'nonInterestIncome': 'None',
  'otherNonOperatingIncome': '77000000',
  'depreciation': 'None',
  'depreciationAndAmortization': '12796000000',
  'incomeBeforeTax': '53036000000',
  'incomeTaxExpense': '8755000000',
  'interestAndDebtExpense': 'None',
  'netIncomeFromContinuingOperations': '44281000000',
  'comprehensiveIncomeNetOfTax': 'None',
  'ebit': '55627000000',
  'ebitda': '68423000000',
  'netIncome': '44281000000'},
 {'fiscalDateEnding': '2019-06-30',
  'reportedCurrency': 'USD',
  'grossProfit': '82933000000',
  'totalRevenue': '125843000000',
  'costOfRevenue': '42910000000',
  'costofGoodsAndServicesSold': '42910000000',
  'operatingIncome': '42959000000',
  'sellingGeneralAndAdministrative': '4885000000',
  'researchAndDevelopment': '16876000000',
  'operatingExpenses': '39974000000',
  'investmentIncomeNet': 'None',
  'netInterestIncome': '-2686000000',
  'interestIncome': '812000000',
  'interestExpense': '2686000000',
  'nonInterestIncome': 'None',
  'otherNonOperatingIncome': '729000000',
  'depreciation': 'None',
  'depreciationAndAmortization': '11682000000',
  'incomeBeforeTax': '43688000000',
  'incomeTaxExpense': '4448000000',
  'interestAndDebtExpense': 'None',
  'netIncomeFromContinuingOperations': '39240000000',
  'comprehensiveIncomeNetOfTax': 'None',
  'ebit': '46374000000',
  'ebitda': '58056000000',
  'netIncome': '39240000000'},
 {'fiscalDateEnding': '2018-06-30',
  'reportedCurrency': 'USD',
  'grossProfit': '72007000000',
  'totalRevenue': '110360000000',
  'costOfRevenue': '38353000000',
  'costofGoodsAndServicesSold': '38353000000',
  'operatingIncome': '35058000000',
  'sellingGeneralAndAdministrative': '4754000000',
  'researchAndDevelopment': '14726000000',
  'operatingExpenses': '36949000000',
  'investmentIncomeNet': 'None',
  'netInterestIncome': '-2733000000',
  'interestIncome': '1522000000',
  'interestExpense': '2733000000',
  'nonInterestIncome': 'None',
  'otherNonOperatingIncome': '1416000000',
  'depreciation': 'None',
  'depreciationAndAmortization': '10261000000',
  'incomeBeforeTax': '36474000000',
  'incomeTaxExpense': '19903000000',
  'interestAndDebtExpense': 'None',
  'netIncomeFromContinuingOperations': '16571000000',
  'comprehensiveIncomeNetOfTax': 'None',
  'ebit': '39207000000',
  'ebitda': '49468000000',
  'netIncome': '16571000000'},
 {'fiscalDateEnding': '2017-06-30',
  'reportedCurrency': 'USD',
  'grossProfit': '62310000000',
  'totalRevenue': '96571000000',
  'costOfRevenue': '34261000000',
  'costofGoodsAndServicesSold': '34261000000',
  'operatingIncome': '29025000000',
  'sellingGeneralAndAdministrative': '4481000000',
  'researchAndDevelopment': '13037000000',
  'operatingExpenses': '32979000000',
  'investmentIncomeNet': 'None',
  'netInterestIncome': '-2222000000',
  'interestIncome': '1182000000',
  'interestExpense': '2222000000',
  'nonInterestIncome': 'None',
  'otherNonOperatingIncome': '823000000',
  'depreciation': 'None',
  'depreciationAndAmortization': '8778000000',
  'incomeBeforeTax': '29901000000',
  'incomeTaxExpense': '4412000000',
  'interestAndDebtExpense': 'None',
  'netIncomeFromContinuingOperations': '21204000000',
  'comprehensiveIncomeNetOfTax': 'None',
  'ebit': '32123000000',
  'ebitda': '40901000000',
  'netIncome': '25489000000'},
 {'fiscalDateEnding': '2016-06-30',
  'reportedCurrency': 'USD',
  'grossProfit': '58374000000',
  'totalRevenue': '91154000000',
  'costOfRevenue': '32780000000',
  'costofGoodsAndServicesSold': '32780000000',
  'operatingIncome': '26078000000',
  'sellingGeneralAndAdministrative': '4563000000',
  'researchAndDevelopment': '11988000000',
  'operatingExpenses': '32296000000',
  'investmentIncomeNet': 'None',
  'netInterestIncome': '-1243000000',
  'interestIncome': '78000000',
  'interestExpense': '1243000000',
  'nonInterestIncome': 'None',
  'otherNonOperatingIncome': '-431000000',
  'depreciation': 'None',
  'depreciationAndAmortization': '6622000000',
  'incomeBeforeTax': '25639000000',
  'incomeTaxExpense': '5100000000',
  'interestAndDebtExpense': 'None',
  'netIncomeFromContinuingOperations': '16798000000',
  'comprehensiveIncomeNetOfTax': 'None',
  'ebit': '26882000000',
  'ebitda': '33504000000',
  'netIncome': '20539000000'},
 {'fiscalDateEnding': '2015-06-30',
  'reportedCurrency': 'USD',
  'grossProfit': '60542000000',
  'totalRevenue': '93580000000',
  'costOfRevenue': '33038000000',
  'costofGoodsAndServicesSold': '33038000000',
  'operatingIncome': '18161000000',
  'sellingGeneralAndAdministrative': '4611000000',
  'researchAndDevelopment': '12046000000',
  'operatingExpenses': '42381000000',
  'investmentIncomeNet': 'None',
  'netInterestIncome': 'None',
  'interestIncome': 'None',
  'interestExpense': '781000000',
  'nonInterestIncome': 'None',
  'otherNonOperatingIncome': '346000000',
  'depreciation': 'None',
  'depreciationAndAmortization': '5957000000',
  'incomeBeforeTax': '18507000000',
  'incomeTaxExpense': '6314000000',
  'interestAndDebtExpense': 'None',
  'netIncomeFromContinuingOperations': '12193000000',
  'comprehensiveIncomeNetOfTax': 'None',
  'ebit': '19288000000',
  'ebitda': '25245000000',
  'netIncome': '12193000000'},
 {'fiscalDateEnding': '2014-06-30',
  'reportedCurrency': 'USD',
  'grossProfit': '59755000000',
  'totalRevenue': '86833000000',
  'costOfRevenue': '27078000000',
  'costofGoodsAndServicesSold': '27078000000',
  'operatingIncome': '27759000000',
  'sellingGeneralAndAdministrative': '4677000000',
  'researchAndDevelopment': '11381000000',
  'operatingExpenses': '31869000000',
  'investmentIncomeNet': 'None',
  'netInterestIncome': 'None',
  'interestIncome': 'None',
  'interestExpense': '597000000',
  'nonInterestIncome': 'None',
  'otherNonOperatingIncome': '61000000',
  'depreciation': 'None',
  'depreciationAndAmortization': '5212000000',
  'incomeBeforeTax': '27820000000',
  'incomeTaxExpense': '5746000000',
  'interestAndDebtExpense': 'None',
  'netIncomeFromContinuingOperations': '22074000000',
  'comprehensiveIncomeNetOfTax': 'None',
  'ebit': '28417000000',
  'ebitda': '33629000000',
  'netIncome': '22074000000'},
 {'fiscalDateEnding': '2013-06-30',
  'reportedCurrency': 'USD',
  'grossProfit': '57464000000',
  'totalRevenue': '77849000000',
  'costOfRevenue': '20385000000',
  'costofGoodsAndServicesSold': '20385000000',
  'operatingIncome': '26764000000',
  'sellingGeneralAndAdministrative': '5013000000',
  'researchAndDevelopment': '10411000000',
  'operatingExpenses': '30700000000',
  'investmentIncomeNet': 'None',
  'netInterestIncome': 'None',
  'interestIncome': 'None',
  'interestExpense': '429000000',
  'nonInterestIncome': 'None',
  'otherNonOperatingIncome': '288000000',
  'depreciation': 'None',
  'depreciationAndAmortization': '3755000000',
  'incomeBeforeTax': '27052000000',
  'incomeTaxExpense': '5189000000',
  'interestAndDebtExpense': 'None',
  'netIncomeFromContinuingOperations': '21863000000',
  'comprehensiveIncomeNetOfTax': 'None',
  'ebit': '27481000000',
  'ebitda': '31236000000',
  'netIncome': '21863000000'},
 {'fiscalDateEnding': '2012-06-30',
  'reportedCurrency': 'USD',
  'grossProfit': '56193000000',
  'totalRevenue': '73723000000',
  'costOfRevenue': '17530000000',
  'costofGoodsAndServicesSold': '17530000000',
  'operatingIncome': '21763000000',
  'sellingGeneralAndAdministrative': '4569000000',
  'researchAndDevelopment': '9811000000',
  'operatingExpenses': '28237000000',
  'investmentIncomeNet': 'None',
  'netInterestIncome': 'None',
  'interestIncome': 'None',
  'interestExpense': '380000000',
  'nonInterestIncome': 'None',
  'otherNonOperatingIncome': '504000000',
  'depreciation': 'None',
  'depreciationAndAmortization': '2967000000',
  'incomeBeforeTax': '22267000000',
  'incomeTaxExpense': '5289000000',
  'interestAndDebtExpense': 'None',
  'netIncomeFromContinuingOperations': '16978000000',
  'comprehensiveIncomeNetOfTax': 'None',
  'ebit': '22647000000',
  'ebitda': '25614000000',
  'netIncome': '16978000000'},
 {'fiscalDateEnding': '2011-06-30',
  'reportedCurrency': 'USD',
  'grossProfit': '54366000000',
  'totalRevenue': '69943000000',
  'costOfRevenue': '15577000000',
  'costofGoodsAndServicesSold': '15577000000',
  'operatingIncome': '27161000000',
  'sellingGeneralAndAdministrative': '4222000000',
  'researchAndDevelopment': '9043000000',
  'operatingExpenses': '27205000000',
  'investmentIncomeNet': 'None',
  'netInterestIncome': 'None',
  'interestIncome': 'None',
  'interestExpense': '295000000',
  'nonInterestIncome': 'None',
  'otherNonOperatingIncome': '910000000',
  'depreciation': 'None',
  'depreciationAndAmortization': '2766000000',
  'incomeBeforeTax': '28071000000',
  'incomeTaxExpense': '4921000000',
  'interestAndDebtExpense': 'None',
  'netIncomeFromContinuingOperations': '23150000000',
  'comprehensiveIncomeNetOfTax': 'None',
  'ebit': '28366000000',
  'ebitda': '31132000000',
  'netIncome': '23150000000'},
 {'fiscalDateEnding': '2010-06-30',
  'reportedCurrency': 'USD',
  'grossProfit': '50089000000',
  'totalRevenue': '62484000000',
  'costOfRevenue': '12395000000',
  'costofGoodsAndServicesSold': '12395000000',
  'operatingIncome': '24098000000',
  'sellingGeneralAndAdministrative': '4063000000',
  'researchAndDevelopment': '8714000000',
  'operatingExpenses': '25991000000',
  'investmentIncomeNet': 'None',
  'netInterestIncome': 'None',
  'interestIncome': 'None',
  'interestExpense': '151000000',
  'nonInterestIncome': 'None',
  'otherNonOperatingIncome': '915000000',
  'depreciation': 'None',
  'depreciationAndAmortization': '2673000000',
  'incomeBeforeTax': '25013000000',
  'incomeTaxExpense': '6253000000',
  'interestAndDebtExpense': 'None',
  'netIncomeFromContinuingOperations': '18760000000',
  'comprehensiveIncomeNetOfTax': 'None',
  'ebit': '25164000000',
  'ebitda': '27837000000',
  'netIncome': '18760000000'},
 {'fiscalDateEnding': '2009-06-30',
  'reportedCurrency': 'USD',
  'grossProfit': '46282000000',
  'totalRevenue': '58437000000',
  'costOfRevenue': '12155000000',
  'costofGoodsAndServicesSold': '12155000000',
  'operatingIncome': '20363000000',
  'sellingGeneralAndAdministrative': '4030000000',
  'researchAndDevelopment': '9010000000',
  'operatingExpenses': '25919000000',
  'investmentIncomeNet': 'None',
  'netInterestIncome': 'None',
  'interestIncome': 'None',
  'interestExpense': '38000000',
  'nonInterestIncome': 'None',
  'otherNonOperatingIncome': 'None',
  'depreciation': 'None',
  'depreciationAndAmortization': '2562000000',
  'incomeBeforeTax': '19821000000',
  'incomeTaxExpense': '5252000000',
  'interestAndDebtExpense': 'None',
  'netIncomeFromContinuingOperations': 'None',
  'comprehensiveIncomeNetOfTax': 'None',
  'ebit': '19859000000',
  'ebitda': '22421000000',
  'netIncome': '14569000000'},
 {'fiscalDateEnding': '2008-06-30',
  'reportedCurrency': 'USD',
  'grossProfit': '48822000000',
  'totalRevenue': '60420000000',
  'costOfRevenue': '11598000000',
  'costofGoodsAndServicesSold': '11598000000',
  'operatingIncome': '22271000000',
  'sellingGeneralAndAdministrative': '5127000000',
  'researchAndDevelopment': '8164000000',
  'operatingExpenses': '26551000000',
  'investmentIncomeNet': 'None',
  'netInterestIncome': 'None',
  'interestIncome': 'None',
  'interestExpense': '106000000',
  'nonInterestIncome': 'None',
  'otherNonOperatingIncome': 'None',
  'depreciation': 'None',
  'depreciationAndAmortization': '2056000000',
  'incomeBeforeTax': '23814000000',
  'incomeTaxExpense': '6133000000',
  'interestAndDebtExpense': 'None',
  'netIncomeFromContinuingOperations': 'None',
  'comprehensiveIncomeNetOfTax': 'None',
  'ebit': '23920000000',
  'ebitda': '25976000000',
  'netIncome': '17681000000'},
 {'fiscalDateEnding': '2007-06-30',
  'reportedCurrency': 'USD',
  'grossProfit': '40429000000',
  'totalRevenue': '51122000000',
  'costOfRevenue': '10693000000',
  'costofGoodsAndServicesSold': '10693000000',
  'operatingIncome': '18438000000',
  'sellingGeneralAndAdministrative': '3329000000',
  'researchAndDevelopment': '7121000000',
  'operatingExpenses': '21991000000',
  'investmentIncomeNet': 'None',
  'netInterestIncome': 'None',
  'interestIncome': 'None',
  'interestExpense': '0',
  'nonInterestIncome': 'None',
  'otherNonOperatingIncome': 'None',
  'depreciation': 'None',
  'depreciationAndAmortization': '1440000000',
  'incomeBeforeTax': '20101000000',
  'incomeTaxExpense': '6036000000',
  'interestAndDebtExpense': 'None',
  'netIncomeFromContinuingOperations': 'None',
  'comprehensiveIncomeNetOfTax': 'None',
  'ebit': '18438000000',
  'ebitda': '19878000000',
  'netIncome': '14065000000'},
 {'fiscalDateEnding': '2006-06-30',
  'reportedCurrency': 'USD',
  'grossProfit': '36632000000',
  'totalRevenue': '44282000000',
  'costOfRevenue': '7650000000',
  'costofGoodsAndServicesSold': '7650000000',
  'operatingIncome': '16472000000',
  'sellingGeneralAndAdministrative': '3758000000',
  'researchAndDevelopment': '6584000000',
  'operatingExpenses': '20160000000',
  'investmentIncomeNet': 'None',
  'netInterestIncome': 'None',
  'interestIncome': 'None',
  'interestExpense': '0',
  'nonInterestIncome': 'None',
  'otherNonOperatingIncome': 'None',
  'depreciation': 'None',
  'depreciationAndAmortization': '903000000',
  'incomeBeforeTax': '18262000000',
  'incomeTaxExpense': '5663000000',
  'interestAndDebtExpense': 'None',
  'netIncomeFromContinuingOperations': 'None',
  'comprehensiveIncomeNetOfTax': 'None',
  'ebit': '16472000000',
  'ebitda': '17375000000',
  'netIncome': '12599000000'}]

In [21]:
data['quarterlyReports']

[{'fiscalDateEnding': '2026-03-31',
  'reportedCurrency': 'USD',
  'grossProfit': '56058000000',
  'totalRevenue': '82886000000',
  'costOfRevenue': '26828000000',
  'costofGoodsAndServicesSold': '26828000000',
  'operatingIncome': '38398000000',
  'sellingGeneralAndAdministrative': '1931000000',
  'researchAndDevelopment': '8915000000',
  'operatingExpenses': '17660000000',
  'investmentIncomeNet': 'None',
  'netInterestIncome': '-48000000',
  'interestIncome': '730000000',
  'interestExpense': '778000000',
  'nonInterestIncome': 'None',
  'otherNonOperatingIncome': 'None',
  'depreciation': 'None',
  'depreciationAndAmortization': '10167000000',
  'incomeBeforeTax': '39340000000',
  'incomeTaxExpense': '7562000000',
  'interestAndDebtExpense': 'None',
  'netIncomeFromContinuingOperations': '31778000000',
  'comprehensiveIncomeNetOfTax': 'None',
  'ebit': '40118000000',
  'ebitda': '50285000000',
  'netIncome': '31778000000'},
 {'fiscalDateEnding': '2025-12-31',
  'reportedCurrency': 'USD',
  'grossProfit': '55295000000',
  'totalRevenue': '81273000000',
  'costOfRevenue': '25978000000',
  'costofGoodsAndServicesSold': '25978000000',
  'operatingIncome': '38275000000',
  'sellingGeneralAndAdministrative': '1932000000',
  'researchAndDevelopment': '8504000000',
  'operatingExpenses': '17020000000',
  'investmentIncomeNet': 'None',
  'netInterestIncome': '104000000',
  'interestIncome': '840000000',
  'interestExpense': '736000000',
  'nonInterestIncome': 'None',
  'otherNonOperatingIncome': 'None',
  'depreciation': 'None',
  'depreciationAndAmortization': '9198000000',
  'incomeBeforeTax': '48246000000',
  'incomeTaxExpense': '9788000000',
  'interestAndDebtExpense': 'None',
  'netIncomeFromContinuingOperations': '38458000000',
  'comprehensiveIncomeNetOfTax': 'None',
  'ebit': '48982000000',
  'ebitda': '58180000000',
  'netIncome': '38458000000'},
 {'fiscalDateEnding': '2025-09-30',
  'reportedCurrency': 'USD',
  'grossProfit': '53630000000',
  'totalRevenue': '77673000000',
  'costOfRevenue': '24043000000',
  'costofGoodsAndServicesSold': '24043000000',
  'operatingIncome': '37961000000',
  'sellingGeneralAndAdministrative': '1806000000',
  'researchAndDevelopment': '8146000000',
  'operatingExpenses': '15669000000',
  'investmentIncomeNet': 'None',
  'netInterestIncome': '278000000',
  'interestIncome': '976000000',
  'interestExpense': '698000000',
  'nonInterestIncome': 'None',
  'otherNonOperatingIncome': 'None',
  'depreciation': 'None',
  'depreciationAndAmortization': '13061000000',
  'incomeBeforeTax': '34301000000',
  'incomeTaxExpense': '6554000000',
  'interestAndDebtExpense': 'None',
  'netIncomeFromContinuingOperations': '27747000000',
  'comprehensiveIncomeNetOfTax': 'None',
  'ebit': '34999000000',
  'ebitda': '48060000000',
  'netIncome': '27747000000'},
 {'fiscalDateEnding': '2025-06-30',
  'reportedCurrency': 'USD',
  'grossProfit': '52427000000',
  'totalRevenue': '76441000000',
  'costOfRevenue': '24014000000',
  'costofGoodsAndServicesSold': '24014000000',
  'operatingIncome': '34323000000',
  'sellingGeneralAndAdministrative': '1990000000',
  'researchAndDevelopment': '8829000000',
  'operatingExpenses': '18104000000',
  'investmentIncomeNet': 'None',
  'netInterestIncome': '154000000',
  'interestIncome': '202000000',
  'interestExpense': '615000000',
  'nonInterestIncome': 'None',
  'otherNonOperatingIncome': 'None',
  'depreciation': 'None',
  'depreciationAndAmortization': '11203000000',
  'incomeBeforeTax': '32616000000',
  'incomeTaxExpense': '5383000000',
  'interestAndDebtExpense': 'None',
  'netIncomeFromContinuingOperations': '27233000000',
  'comprehensiveIncomeNetOfTax': 'None',
  'ebit': '33231000000',
  'ebitda': '44434000000',
  'netIncome': '27233000000'},
 {'fiscalDateEnding': '2025-03-31',
  'reportedCurrency': 'USD',
  'grossProfit': '48147000000',
  'totalRevenue': '70066000000',
  'costOfRevenue': '21919000000',
  'costofGoodsAndServicesSold': '21919000000',
  'operatingIncome': '32000000000',
  'sellingGeneralAndAdministrative': '1737000000',
  'researchAndDevelopment': '8198000000',
  'operatingExpenses': '16147000000',
  'investmentIncomeNet': 'None',
  'netInterestIncome': '3000000',
  'interestIncome': '597000000',
  'interestExpense': '594000000',
  'nonInterestIncome': 'None',
  'otherNonOperatingIncome': 'None',
  'depreciation': 'None',
  'depreciationAndAmortization': '8740000000',
  'incomeBeforeTax': '31377000000',
  'incomeTaxExpense': '5553000000',
  'interestAndDebtExpense': 'None',
  'netIncomeFromContinuingOperations': '25824000000',
  'comprehensiveIncomeNetOfTax': 'None',
  'ebit': '31971000000',
  'ebitda': '40711000000',
  'netIncome': '25824000000'},
 {'fiscalDateEnding': '2024-12-31',
  'reportedCurrency': 'USD',
  'grossProfit': '47833000000',
  'totalRevenue': '69632000000',
  'costOfRevenue': '21799000000',
  'costofGoodsAndServicesSold': '21799000000',
  'operatingIncome': '31653000000',
  'sellingGeneralAndAdministrative': '1823000000',
  'researchAndDevelopment': '7917000000',
  'operatingExpenses': '16180000000',
  'investmentIncomeNet': 'None',
  'netInterestIncome': '6000000',
  'interestIncome': '600000000',
  'interestExpense': '594000000',
  'nonInterestIncome': 'None',
  'otherNonOperatingIncome': 'None',
  'depreciation': 'None',
  'depreciationAndAmortization': '6827000000',
  'incomeBeforeTax': '29365000000',
  'incomeTaxExpense': '5257000000',
  'interestAndDebtExpense': 'None',
  'netIncomeFromContinuingOperations': '24108000000',
  'comprehensiveIncomeNetOfTax': 'None',
  'ebit': '29959000000',
  'ebitda': '36786000000',
  'netIncome': '24108000000'},
 {'fiscalDateEnding': '2024-09-30',
  'reportedCurrency': 'USD',
  'grossProfit': '45486000000',
  'totalRevenue': '65585000000',
  'costOfRevenue': '20099000000',
  'costofGoodsAndServicesSold': '20099000000',
  'operatingIncome': '30552000000',
  'sellingGeneralAndAdministrative': '1673000000',
  'researchAndDevelopment': '7544000000',
  'operatingExpenses': '14934000000',
  'investmentIncomeNet': 'None',
  'netInterestIncome': '99000000',
  'interestIncome': '681000000',
  'interestExpense': '582000000',
  'nonInterestIncome': 'None',
  'otherNonOperatingIncome': 'None',
  'depreciation': 'None',
  'depreciationAndAmortization': '7383000000',
  'incomeBeforeTax': '30269000000',
  'incomeTaxExpense': '5602000000',
  'interestAndDebtExpense': 'None',
  'netIncomeFromContinuingOperations': '24667000000',
  'comprehensiveIncomeNetOfTax': 'None',
  'ebit': '30851000000',
  'ebitda': '38234000000',
  'netIncome': '24667000000'},
 {'fiscalDateEnding': '2024-06-30',
  'reportedCurrency': 'USD',
  'grossProfit': '45043000000',
  'totalRevenue': '64727000000',
  'costOfRevenue': '19684000000',
  'costofGoodsAndServicesSold': '19684000000',
  'operatingIncome': '27925000000',
  'sellingGeneralAndAdministrative': '2246000000',
  'researchAndDevelopment': '8056000000',
  'operatingExpenses': '17118000000',
  'investmentIncomeNet': 'None',
  'netInterestIncome': '-63000000',
  'interestIncome': '638000000',
  'interestExpense': '701000000',
  'nonInterestIncome': 'None',
  'otherNonOperatingIncome': 'None',
  'depreciation': 'None',
  'depreciationAndAmortization': '6380000000',
  'incomeBeforeTax': '27250000000',
  'incomeTaxExpense': '5214000000',
  'interestAndDebtExpense': 'None',
  'netIncomeFromContinuingOperations': '22036000000',
  'comprehensiveIncomeNetOfTax': 'None',
  'ebit': '27951000000',
  'ebitda': '34331000000',
  'netIncome': '22036000000'},
 {'fiscalDateEnding': '2024-03-31',
  'reportedCurrency': 'USD',
  'grossProfit': '43353000000',
  'totalRevenue': '61858000000',
  'costOfRevenue': '18505000000',
  'costofGoodsAndServicesSold': '18505000000',
  'operatingIncome': '27581000000',
  'sellingGeneralAndAdministrative': '1912000000',
  'researchAndDevelopment': '7653000000',
  'operatingExpenses': '15772000000',
  'investmentIncomeNet': 'None',
  'netInterestIncome': '-181000000',
  'interestIncome': '619000000',
  'interestExpense': '800000000',
  'nonInterestIncome': 'None',
  'otherNonOperatingIncome': 'None',
  'depreciation': 'None',
  'depreciationAndAmortization': '6027000000',
  'incomeBeforeTax': '26727000000',
  'incomeTaxExpense': '4788000000',
  'interestAndDebtExpense': 'None',
  'netIncomeFromContinuingOperations': '21939000000',
  'comprehensiveIncomeNetOfTax': 'None',
  'ebit': '27527000000',
  'ebitda': '33554000000',
  'netIncome': '21939000000'},
 {'fiscalDateEnding': '2023-12-31',
  'reportedCurrency': 'USD',
  'grossProfit': '42397000000',
  'totalRevenue': '62020000000',
  'costOfRevenue': '19623000000',
  'costofGoodsAndServicesSold': '19623000000',
  'operatingIncome': '27032000000',
  'sellingGeneralAndAdministrative': '1977000000',
  'researchAndDevelopment': '7142000000',
  'operatingExpenses': '15365000000',
  'investmentIncomeNet': 'None',
  'netInterestIncome': '-175000000',
  'interestIncome': '734000000',
  'interestExpense': '909000000',
  'nonInterestIncome': 'None',
  'otherNonOperatingIncome': 'None',
  'depreciation': 'None',
  'depreciationAndAmortization': '5959000000',
  'incomeBeforeTax': '26526000000',
  'incomeTaxExpense': '4656000000',
  'interestAndDebtExpense': 'None',
  'netIncomeFromContinuingOperations': '21870000000',
  'comprehensiveIncomeNetOfTax': 'None',
  'ebit': '27435000000',
  'ebitda': '33394000000',
  'netIncome': '21870000000'},
 {'fiscalDateEnding': '2023-09-30',
  'reportedCurrency': 'USD',
  'grossProfit': '40215000000',
  'totalRevenue': '56517000000',
  'costOfRevenue': '16302000000',
  'costofGoodsAndServicesSold': '16302000000',
  'operatingIncome': '26895000000',
  'sellingGeneralAndAdministrative': '1474000000',
  'researchAndDevelopment': '6659000000',
  'operatingExpenses': '13320000000',
  'investmentIncomeNet': 'None',
  'netInterestIncome': '641000000',
  'interestIncome': '1166000000',
  'interestExpense': '525000000',
  'nonInterestIncome': 'None',
  'otherNonOperatingIncome': 'None',
  'depreciation': 'None',
  'depreciationAndAmortization': '3921000000',
  'incomeBeforeTax': '27284000000',
  'incomeTaxExpense': '4993000000',
  'interestAndDebtExpense': 'None',
  'netIncomeFromContinuingOperations': '22291000000',
  'comprehensiveIncomeNetOfTax': 'None',
  'ebit': '27809000000',
  'ebitda': '31730000000',
  'netIncome': '22291000000'},
 {'fiscalDateEnding': '2023-06-30',
  'reportedCurrency': 'USD',
  'grossProfit': '39394000000',
  'totalRevenue': '56189000000',
  'costOfRevenue': '16795000000',
  'costofGoodsAndServicesSold': '16795000000',
  'operatingIncome': '24254000000',
  'sellingGeneralAndAdministrative': '2197000000',
  'researchAndDevelopment': '6739000000',
  'operatingExpenses': '15140000000',
  'investmentIncomeNet': 'None',
  'netInterestIncome': '423000000',
  'interestIncome': '905000000',
  'interestExpense': '482000000',
  'nonInterestIncome': 'None',
  'otherNonOperatingIncome': 'None',
  'depreciation': 'None',
  'depreciationAndAmortization': '3874000000',
  'incomeBeforeTax': '24727000000',
  'incomeTaxExpense': '4646000000',
  'interestAndDebtExpense': 'None',
  'netIncomeFromContinuingOperations': '20081000000',
  'comprehensiveIncomeNetOfTax': 'None',
  'ebit': '24254000000',
  'ebitda': '28128000000',
  'netIncome': '20081000000'},
 {'fiscalDateEnding': '2023-03-31',
  'reportedCurrency': 'USD',
  'grossProfit': '36729000000',
  'totalRevenue': '52857000000',
  'costOfRevenue': '16128000000',
  'costofGoodsAndServicesSold': '16128000000',
  'operatingIncome': '22352000000',
  'sellingGeneralAndAdministrative': '1643000000',
  'researchAndDevelopment': '6984000000',
  'operatingExpenses': '14377000000',
  'investmentIncomeNet': 'None',
  'netInterestIncome': '252000000',
  'interestIncome': '748000000',
  'interestExpense': '496000000',
  'nonInterestIncome': 'None',
  'otherNonOperatingIncome': '321000000',
  'depreciation': 'None',
  'depreciationAndAmortization': '3549000000',
  'incomeBeforeTax': '22673000000',
  'incomeTaxExpense': '4374000000',
  'interestAndDebtExpense': 'None',
  'netIncomeFromContinuingOperations': '18299000000',
  'comprehensiveIncomeNetOfTax': 'None',
  'ebit': '23169000000',
  'ebitda': '26718000000',
  'netIncome': '18299000000'},
 {'fiscalDateEnding': '2022-12-31',
  'reportedCurrency': 'USD',
  'grossProfit': '35259000000',
  'totalRevenue': '52747000000',
  'costOfRevenue': '17488000000',
  'costofGoodsAndServicesSold': '17488000000',
  'operatingIncome': '20399000000',
  'sellingGeneralAndAdministrative': '2337000000',
  'researchAndDevelopment': '6844000000',
  'operatingExpenses': '14860000000',
  'investmentIncomeNet': 'None',
  'netInterestIncome': '210000000',
  'interestIncome': '700000000',
  'interestExpense': '490000000',
  'nonInterestIncome': 'None',
  'otherNonOperatingIncome': '-60000000',
  'depreciation': 'None',
  'depreciationAndAmortization': '3648000000',
  'incomeBeforeTax': '20339000000',
  'incomeTaxExpense': '3914000000',
  'interestAndDebtExpense': 'None',
  'netIncomeFromContinuingOperations': '16425000000',
  'comprehensiveIncomeNetOfTax': 'None',
  'ebit': '20399000000',
  'ebitda': '24047000000',
  'netIncome': '16425000000'},
 {'fiscalDateEnding': '2022-09-30',
  'reportedCurrency': 'USD',
  'grossProfit': '34670000000',
  'totalRevenue': '50122000000',
  'costOfRevenue': '15452000000',
  'costofGoodsAndServicesSold': '15452000000',
  'operatingIncome': '21518000000',
  'sellingGeneralAndAdministrative': '1398000000',
  'researchAndDevelopment': '6628000000',
  'operatingExpenses': '13152000000',
  'investmentIncomeNet': 'None',
  'netInterestIncome': '141000000',
  'interestIncome': '641000000',
  'interestExpense': '500000000',
  'nonInterestIncome': 'None',
  'otherNonOperatingIncome': '54000000',
  'depreciation': 'None',
  'depreciationAndAmortization': '3400000000',
  'incomeBeforeTax': '21572000000',
  'incomeTaxExpense': '4016000000',
  'interestAndDebtExpense': 'None',
  'netIncomeFromContinuingOperations': '17556000000',
  'comprehensiveIncomeNetOfTax': 'None',
  'ebit': '21518000000',
  'ebitda': '24918000000',
  'netIncome': '17556000000'},
 {'fiscalDateEnding': '2022-06-30',
  'reportedCurrency': 'USD',
  'grossProfit': '35436000000',
  'totalRevenue': '51865000000',
  'costOfRevenue': '16429000000',
  'costofGoodsAndServicesSold': '16429000000',
  'operatingIncome': '20534000000',
  'sellingGeneralAndAdministrative': '1749000000',
  'researchAndDevelopment': '6849000000',
  'operatingExpenses': '14902000000',
  'investmentIncomeNet': 'None',
  'netInterestIncome': '56000000',
  'interestIncome': '552000000',
  'interestExpense': '496000000',
  'nonInterestIncome': 'None',
  'otherNonOperatingIncome': '-47000000',
  'depreciation': 'None',
  'depreciationAndAmortization': '3979000000',
  'incomeBeforeTax': '20487000000',
  'incomeTaxExpense': '3747000000',
  'interestAndDebtExpense': 'None',
  'netIncomeFromContinuingOperations': '16740000000',
  'comprehensiveIncomeNetOfTax': 'None',
  'ebit': '20983000000',
  'ebitda': '24962000000',
  'netIncome': '16740000000'},
 {'fiscalDateEnding': '2022-03-31',
  'reportedCurrency': 'USD',
  'grossProfit': '33745000000',
  'totalRevenue': '49360000000',
  'costOfRevenue': '15615000000',
  'costofGoodsAndServicesSold': '15615000000',
  'operatingIncome': '20364000000',
  'sellingGeneralAndAdministrative': '1480000000',
  'researchAndDevelopment': '6306000000',
  'operatingExpenses': '13381000000',
  'investmentIncomeNet': 'None',
  'netInterestIncome': '16000000',
  'interestIncome': '519000000',
  'interestExpense': '503000000',
  'nonInterestIncome': 'None',
  'otherNonOperatingIncome': '-174000000',
  'depreciation': 'None',
  'depreciationAndAmortization': '3773000000',
  'incomeBeforeTax': '20190000000',
  'incomeTaxExpense': '3462000000',
  'interestAndDebtExpense': 'None',
  'netIncomeFromContinuingOperations': '16728000000',
  'comprehensiveIncomeNetOfTax': 'None',
  'ebit': '20693000000',
  'ebitda': '24466000000',
  'netIncome': '16728000000'},
 {'fiscalDateEnding': '2021-12-31',
  'reportedCurrency': 'USD',
  'grossProfit': '34768000000',
  'totalRevenue': '51728000000',
  'costOfRevenue': '16960000000',
  'costofGoodsAndServicesSold': '16960000000',
  'operatingIncome': '22247000000',
  'sellingGeneralAndAdministrative': '1384000000',
  'researchAndDevelopment': '5758000000',
  'operatingExpenses': '12521000000',
  'investmentIncomeNet': 'None',
  'netInterestIncome': '-22000000',
  'interestIncome': '503000000',
  'interestExpense': '525000000',
  'nonInterestIncome': 'None',
  'otherNonOperatingIncome': '268000000',
  'depreciation': 'None',
  'depreciationAndAmortization': '3496000000',
  'incomeBeforeTax': '22515000000',
  'incomeTaxExpense': '3750000000',
  'interestAndDebtExpense': 'None',
  'netIncomeFromContinuingOperations': '18765000000',
  'comprehensiveIncomeNetOfTax': 'None',
  'ebit': '23040000000',
  'ebitda': '26536000000',
  'netIncome': '18765000000'},
 {'fiscalDateEnding': '2021-09-30',
  'reportedCurrency': 'USD',
  'grossProfit': '31671000000',
  'totalRevenue': '45317000000',
  'costOfRevenue': '13646000000',
  'costofGoodsAndServicesSold': '13646000000',
  'operatingIncome': '20238000000',
  'sellingGeneralAndAdministrative': '1287000000',
  'researchAndDevelopment': '5599000000',
  'operatingExpenses': '11433000000',
  'investmentIncomeNet': 'None',
  'netInterestIncome': '-19000000',
  'interestIncome': '520000000',
  'interestExpense': '539000000',
  'nonInterestIncome': 'None',
  'otherNonOperatingIncome': '286000000',
  'depreciation': 'None',
  'depreciationAndAmortization': '3212000000',
  'incomeBeforeTax': '20524000000',
  'incomeTaxExpense': '19000000',
  'interestAndDebtExpense': 'None',
  'netIncomeFromContinuingOperations': '20505000000',
  'comprehensiveIncomeNetOfTax': 'None',
  'ebit': '21063000000',
  'ebitda': '24275000000',
  'netIncome': '20505000000'},
 {'fiscalDateEnding': '2021-06-30',
  'reportedCurrency': 'USD',
  'grossProfit': '32161000000',
  'totalRevenue': '46152000000',
  'costOfRevenue': '13991000000',
  'costofGoodsAndServicesSold': '13991000000',
  'operatingIncome': '19095000000',
  'sellingGeneralAndAdministrative': '1522000000',
  'researchAndDevelopment': '5687000000',
  'operatingExpenses': '13066000000',
  'investmentIncomeNet': 'None',
  'netInterestIncome': '-56000000',
  'interestIncome': '497000000',
  'interestExpense': '553000000',
  'nonInterestIncome': 'None',
  'otherNonOperatingIncome': '310000000',
  'depreciation': 'None',
  'depreciationAndAmortization': '3344000000',
  'incomeBeforeTax': '19405000000',
  'incomeTaxExpense': '2947000000',
  'interestAndDebtExpense': 'None',
  'netIncomeFromContinuingOperations': '16458000000',
  'comprehensiveIncomeNetOfTax': 'None',
  'ebit': '19958000000',
  'ebitda': '23302000000',
  'netIncome': '16458000000'},
 {'fiscalDateEnding': '2021-03-31',
  'reportedCurrency': 'USD',
  'grossProfit': '28661000000',
  'totalRevenue': '41706000000',
  'costOfRevenue': '13045000000',
  'costofGoodsAndServicesSold': '13045000000',
  'operatingIncome': '17048000000',
  'sellingGeneralAndAdministrative': '1327000000',
  'researchAndDevelopment': '5204000000',
  'operatingExpenses': '11613000000',
  'investmentIncomeNet': 'None',
  'netInterestIncome': '-114000000',
  'interestIncome': '519000000',
  'interestExpense': '633000000',
  'nonInterestIncome': 'None',
  'otherNonOperatingIncome': '188000000',
  'depreciation': 'None',
  'depreciationAndAmortization': '2936000000',
  'incomeBeforeTax': '17236000000',
  'incomeTaxExpense': '1779000000',
  'interestAndDebtExpense': 'None',
  'netIncomeFromContinuingOperations': '15457000000',
  'comprehensiveIncomeNetOfTax': 'None',
  'ebit': '17869000000',
  'ebitda': '20805000000',
  'netIncome': '15457000000'},
 {'fiscalDateEnding': '2020-12-31',
  'reportedCurrency': 'USD',
  'grossProfit': '28882000000',
  'totalRevenue': '43076000000',
  'costOfRevenue': '14194000000',

In [22]:
# prompt:  convert list of dictionaries into a pandas DataFrame
import pandas as pd
import numpy as np

# Step 1: Initialize the DataFrame
df = pd.DataFrame(data['annualReports'])

df.head(10)

,fiscalDateEnding,reportedCurrency,grossProfit,totalRevenue,costOfRevenue,costofGoodsAndServicesSold,operatingIncome,sellingGeneralAndAdministrative,researchAndDevelopment,operatingExpenses,...,depreciation,depreciationAndAmortization,incomeBeforeTax,incomeTaxExpense,interestAndDebtExpense,netIncomeFromContinuingOperations,comprehensiveIncomeNetOfTax,ebit,ebitda,netIncome
0,2025-06-30,USD,193893000000,281724000000,87831000000,87831000000,128528000000,7223000000,32488000000,65365000000,...,None,34153000000,123627000000,21795000000,None,101832000000,None,126012000000,160165000000,101832000000
1,2024-06-30,USD,171008000000,245122000000,74114000000,74114000000,109433000000,7609000000,29510000000,61575000000,...,None,22287000000,107787000000,19651000000,None,88136000000,None,110722000000,133009000000,88136000000
2,2023-06-30,USD,146052000000,211915000000,65863000000,65863000000,88523000000,7575000000,27195000000,57529000000,...,None,13861000000,89311000000,16950000000,None,72361000000,None,91279000000,105140000000,72361000000
3,2022-06-30,USD,135620000000,198270000000,62650000000,62650000000,83383000000,5900000000,24512000000,52237000000,...,None,14460000000,83716000000,10978000000,None,72738000000,None,85779000000,100239000000,72738000000
4,2021-06-30,USD,115856000000,168088000000,52232000000,52232000000,69916000000,5107000000,20716000000,45940000000,...,None,11686000000,71102000000,9831000000,None,61271000000,None,73448000000,85134000000,61271000000
5,2020-06-30,USD,96937000000,143015000000,46078000000,46078000000,52959000000,5111000000,19269000000,43978000000,...,None,12796000000,53036000000,8755000000,None,44281000000,None,55627000000,68423000000,44281000000
6,2019-06-30,USD,82933000000,125843000000,42910000000,42910000000,42959000000,4885000000,16876000000,39974000000,...,None,11682000000,43688000000,4448000000,None,39240000000,None,46374000000,58056000000,39240000000
7,2018-06-30,USD,72007000000,110360000000,38353000000,38353000000,35058000000,4754000000,14726000000,36949000000,...,None,10261000000,36474000000,19903000000,None,16571000000,None,39207000000,49468000000,16571000000
8,2017-06-30,USD,62310000000,96571000000,34261000000,34261000000,29025000000,4481000000,13037000000,32979000000,...,None,8778000000,29901000000,4412000000,None,21204000000,None,32123000000,40901000000,25489000000
9,2016-06-30,USD,58374000000,91154000000,32780000000,32780000000,26078000000,4563000000,11988000000,32296000000,...,None,6622000000,25639000000,5100000000,None,16798000000,None,26882000000,33504000000,20539000000

In [ ]:
# Optional: Convert date column to official datetime format
df['fiscalDateEnding'] = pd.to_datetime(df['fiscalDateEnding'])

print(df)

# 4) Technical Data
```
Relative Strength Index. - RSI


Scale: The RSI oscillates on a fixed scale between 0 and 100.

Overbought (>= 70): An RSI value at or above 70 suggests that an asset is overvalued and may be primed for a trend reversal or corrective price pullback.

Oversold (<= 30): An RSI value at or below 30 suggests that an asset is undervalued or oversold, indicating a potential buying opportunity or price bounce
```

## How Traders Use It
```
Reversal Signals: Selling when the RSI drops back below 70 from an overbought state, or buying when it climbs back above 30 from an oversold state

Divergence: If the asset price hits a new high, but the RSI fails to make a new high, it signals weakening momentum, suggesting the price might drop.

Trend Confirmation: An RSI consistently remaining above 50 generally indicates a strong bullish uptrend, while staying below 50 indicates a bearish downtrend [1].

In [23]:
TICKER='AAPL'
url = (
    f"https://www.alphavantage.co/query?"
    f"function=RSI"
    f"&symbol={TICKER}"
    f"&interval=daily"
    f"&time_period=14"
    f"&series_type=close"
    f"&apikey={ALPHAADVANTAGE_API_KEY}"
)

data = requests.get(url).json()

In [24]:
data

{'Meta Data': {'1: Symbol': 'AAPL',
  '2: Indicator': 'Relative Strength Index (RSI)',
  '3: Last Refreshed': '2026-06-05',
  '4: Interval': 'daily',
  '5: Time Period': 14,
  '6: Series Type': 'close',
  '7: Time Zone': 'US/Eastern Time'},
 'Technical Analysis: RSI': {'2026-06-05': {'RSI': '60.8174'},
  '2026-06-04': {'RSI': '66.6123'},
  '2026-06-03': {'RSI': '65.8591'},
  '2026-06-02': {'RSI': '73.7247'},
  '2026-06-01': {'RSI': '67.1733'},
  '2026-05-29': {'RSI': '79.0043'},
  '2026-05-28': {'RSI': '80.0286'},
  '2026-05-27': {'RSI': '79.1004'},
  '2026-05-26': {'RSI': '77.6353'},
  '2026-05-22': {'RSI': '78.6306'},
  '2026-05-21': {'RSI': '76.4381'},
  '2026-05-20': {'RSI': '74.7148'},
  '2026-05-19': {'RSI': '72.4772'},
  '2026-05-18': {'RSI': '71.6754'},
  '2026-05-15': {'RSI': '76.0255'},
  '2026-05-14': {'RSI': '74.8264'},
  '2026-05-13': {'RSI': '75.9794'},
  '2026-05-12': {'RSI': '73.6550'},
  '2026-05-11': {'RSI': '72.3614'},
  '2026-05-08': {'RSI': '72.9413'},
  '2026-05-07': {'RSI': '69.3121'},
  '2026-05-06': {'RSI': '69.4150'},
  '2026-05-05': {'RSI': '67.2681'},
  '2026-05-04': {'RSI': '61.7677'},
  '2026-05-01': {'RSI': '66.4363'},
  '2026-04-30': {'RSI': '58.7476'},
  '2026-04-29': {'RSI': '57.5350'},
  '2026-04-28': {'RSI': '58.2628'},
  '2026-04-27': {'RSI': '55.2451'},
  '2026-04-24': {'RSI': '59.7062'},
  '2026-04-23': {'RSI': '62.9488'},
  '2026-04-22': {'RSI': '62.7427'},
  '2026-04-21': {'RSI': '56.7239'},
  '2026-04-20': {'RSI': '66.5332'},
  '2026-04-17': {'RSI': '64.1753'},
  '2026-04-16': {'RSI': '57.4299'},
  '2026-04-15': {'RSI': '62.2590'},
  '2026-04-14': {'RSI': '53.0676'},
  '2026-04-13': {'RSI': '53.6583'},
  '2026-04-10': {'RSI': '55.6483'},
  '2026-04-09': {'RSI': '55.6633'},
  '2026-04-08': {'RSI': '53.8288'},
  '2026-04-07': {'RSI': '46.8998'},
  '2026-04-06': {'RSI': '54.4283'},
  '2026-04-02': {'RSI': '50.3706'},
  '2026-04-01': {'RSI': '49.9626'},
  '2026-03-31': {'RSI': '47.4152'},
  '2026-03-30': {'RSI': '35.5613'},
  '2026-03-27': {'RSI': '37.9701'},
  '2026-03-26': {'RSI': '43.0769'},
  '2026-03-25': {'RSI': '42.6037'},
  '2026-03-24': {'RSI': '40.9493'},
  '2026-03-23': {'RSI': '40.7063'},
  '2026-03-20': {'RSI': '34.9042'},
  '2026-03-19': {'RSI': '35.8059'},
  '2026-03-18': {'RSI': '36.6952'},
  '2026-03-17': {'RSI': '40.8159'},
  '2026-03-16': {'RSI': '38.7156'},
  '2026-03-13': {'RSI': '34.5879'},
  '2026-03-12': {'RSI': '39.7856'},
  '2026-03-11': {'RSI': '45.4664'},
  '2026-03-10': {'RSI': '45.4903'},
  '2026-03-09': {'RSI': '44.1972'},
  '2026-03-06': {'RSI': '40.8798'},
  '2026-03-05': {'RSI': '43.7009'},
  '2026-03-04': {'RSI': '46.0249'},
  '2026-03-03': {'RSI': '47.3135'},
  '2026-03-02': {'RSI': '48.3039'},
  '2026-02-27': {'RSI': '47.7384'},
  '2026-02-26': {'RSI': '57.1699'},
  '2026-02-25': {'RSI': '58.7428'},
  '2026-02-24': {'RSI': '56.9469'},
  '2026-02-23': {'RSI': '51.3378'},
  '2026-02-20': {'RSI': '49.7044'},
  '2026-02-19': {'RSI': '45.4540'},
  '2026-02-18': {'RSI': '49.0843'},
  '2026-02-17': {'RSI': '48.6091'},
  '2026-02-13': {'RSI': '39.5871'},
  '2026-02-12': {'RSI': '44.9724'},
  '2026-02-11': {'RSI': '63.5509'},
  '2026-02-10': {'RSI': '61.6042'},
  '2026-02-09': {'RSI': '63.2237'},
  '2026-02-06': {'RSI': '69.0258'},
  '2026-02-05': {'RSI': '67.1143'},
  '2026-02-04': {'RSI': '68.1390'},
  '2026-02-03': {'RSI': '61.5502'},
  '2026-02-02': {'RSI': '62.4570'},
  '2026-01-30': {'RSI': '48.4444'},
  '2026-01-29': {'RSI': '46.3244'},
  '2026-01-28': {'RSI': '42.9864'},
  '2026-01-27': {'RSI': '45.6056'},
  '2026-01-26': {'RSI': '40.3292'},
  '2026-01-23': {'RSI': '22.2920'},
  '2026-01-22': {'RSI': '22.5583'},
  '2026-01-21': {'RSI': '20.5685'},
  '2026-01-20': {'RSI': '17.9103'},
  '2026-01-16': {'RSI': '25.1841'},
  '2026-01-15': {'RSI': '28.4392'},
  '2026-01-14': {'RSI': '30.8576'},
  '2026-01-13': {'RSI': '32.4537'},
  '2026-01-12': {'RSI': '29.9856'},
  '2026-01-09': {'RSI': '27.2711'},
  '2026-01-08': {'RSI': '26.2758'},
  '2026-01-07': {'RSI': '27.6493'},
  '2026-01-06': {'RSI': '29.9358'},
  '2026-01-05': {'RSI': '36.7472'},
  '2026-01-02': {'RSI': '43.8351'},
  '2025-12-31': {'RSI': '45.6900'},
  '2025-12-30': {'RSI': '48.4207'},
  '2025-12-29': {'RSI': '49.9663'},
  '2025-12-26': {'RSI': '49.1687'},
  '2025-12-24': {'RSI': '50.0119'},
  '2025-12-23': {'RSI': '47.0288'},
  '2025-12-22': {'RSI': '44.0570'},
  '2025-12-19': {'RSI': '49.0170'},
  '2025-12-18': {'RSI': '45.9179'},
  '2025-12-17': {'RSI': '45.1863'},
  '2025-12-16': {'RSI': '50.1749'},
  '2025-12-15': {'RSI': '49.2355'},
  '2025-12-12': {'RSI': '57.6533'},
  '2025-12-11': {'RSI': '57.2463'},
  '2025-12-10': {'RSI': '58.8209'},
  '2025-12-09': {'RSI': '56.4479'},
  '2025-12-08': {'RSI': '57.8209'},
  '2025-12-05': {'RSI': '59.5055'},
  '2025-12-04': {'RSI': '63.1939'},
  '2025-12-03': {'RSI': '70.4832'},
  '2025-12-02': {'RSI': '75.2491'},
  '2025-12-01': {'RSI': '72.6478'},
  '2025-11-28': {'RSI': '68.4071'},
  '2025-11-26': {'RSI': '66.9518'},
  '2025-11-25': {'RSI': '66.3088'},
  '2025-11-24': {'RSI': '65.1696'},
  '2025-11-21': {'RSI': '59.8515'},
  '2025-11-20': {'RSI': '51.7617'},
  '2025-11-19': {'RSI': '56.4150'},
  '2025-11-18': {'RSI': '54.5765'},
  '2025-11-17': {'RSI': '54.6147'},
  '2025-11-14': {'RSI': '65.0838'},
  '2025-11-13': {'RSI': '66.3726'},
  '2025-11-12': {'RSI': '67.5691'},
  '2025-11-11': {'RSI': '71.6759'},
  '2025-11-10': {'RSI': '65.2664'},
  '2025-11-07': {'RSI': '63.6675'},
  '2025-11-06': {'RSI': '66.7057'},
  '2025-11-05': {'RSI': '67.5577'},
  '2025-11-04': {'RSI': '67.4534'},
  '2025-11-03': {'RSI': '66.4619'},
  '2025-10-31': {'RSI': '69.0668'},
  '2025-10-30': {'RSI': '71.0856'},
  '2025-10-29': {'RSI': '69.7296'},
  '2025-10-28': {'RSI': '69.1769'},
  '2025-10-27': {'RSI': '69.0344'},
  '2025-10-24': {'RSI': '64.1875'},
  '2025-10-23': {'RSI': '61.1318'},
  '2025-10-22': {'RSI': '60.0273'},
  '2025-10-21': {'RSI': '66.7624'},
  '2025-10-20': {'RSI': '66.3321'},
  '2025-10-17': {'RSI': '56.5175'},
  '2025-10-16': {'RSI': '49.9239'},
  '2025-10-15': {'RSI': '52.8287'},
  '2025-10-14': {'RSI': '50.6122'},
  '2025-10-13': {'RSI': '50.4607'},
  '2025-10-10': {'RSI': '47.1938'},
  '2025-10-09': {'RSI': '60.8718'},
  '2025-10-08': {'RSI': '69.4377'},
  '2025-10-07': {'RSI': '67.7831'},
  '2025-10-06': {'RSI': '68.2391'},
  '2025-10-03': {'RSI': '71.0497'},
  '2025-10-02': {'RSI': '70.2893'},
  '2025-10-01': {'RSI': '68.8555'},
  '2025-09-30': {'RSI': '68.1590'},
  '2025-09-29': {'RSI': '67.9969'},
  '2025-09-26': {'RSI': '69.6935'},
  '2025-09-25': {'RSI': '71.9762'},
  '2025-09-24': {'RSI': '68.9190'},
  '2025-09-23': {'RSI': '72.3252'},
  '2025-09-22': {'RSI': '75.0043'},
  '2025-09-19': {'RSI': '67.9316'},
  '2025-09-18': {'RSI': '60.4466'},
  '2025-09-17': {'RSI': '62.4172'},
  '2025-09-16': {'RSI': '61.5361'},
  '2025-09-15': {'RSI': '60.0341'},
  '2025-09-12': {'RSI': '57.2207'},
  '2025-09-11': {'RSI': '52.4456'},
  '2025-09-10': {'RSI': '48.1344'},
  '2025-09-09': {'RSI': '59.9006'},
  '2025-09-08': {'RSI': '67.0019'},
  '2025-09-05': {'RSI': '71.0101'},
  '2025-09-04': {'RSI': '71.2068'},
  '2025-09-03': {'RSI': '70.0870'},
  '2025-09-02': {'RSI': '60.5777'},
  '2025-08-29': {'RSI': '65.9630'},
  '2025-08-28': {'RSI': '66.9217'},
  '2025-08-27': {'RSI': '64.5646'},
  '2025-08-26': {'RSI': '63.1756'},
  '2025-08-25': {'RSI': '60.5599'},
  '2025-08-22': {'RSI': '61.6955'},
  '2025-08-21': {'RSI': '58.2285'},
  '2025-08-20': {'RSI': '60.1920'},
  '2025-08-19': {'RSI': '69.0548'},
  '2025-08-18': {'RSI': '69.7465'},
  '2025-08-15': {'RSI': '71.1501'},
  '2025-08-14': {'RSI': '73.4846'},
  '2025-08-13': {'RSI': '74.5342'},
  '2025-08-12': {'RSI': '72.0543'},
  '2025-08-11': {'RSI': '70.2486'},
  '2025-08-08': {'RSI': '73.6623'},
  '2025-08-07': {'RSI': '66.2258'},
  '2025-08-06': {'RSI': '58.2659'},
  '2025-08-05': {'RSI': '37.3892'},
  '2025-08-04': {'RSI': '38.1264'},
  '2025-08-01': {'RSI': '35.4609'},
  '2025-07-31': {'RSI': '45.1175'},
  '2025-07-30': {'RSI': '48.6237'},
  '2025-07-29': {'RSI': '54.5256'},
  '2025-07-28': {'RSI': '63.4862'},
  '2025-07-25': {'RSI': '63.1422'},
  '2025-07-24': {'RSI': '62.9133'},
  '2025-07-23': {'RSI': '64.1153'},
  '2025-07-22': {'RSI': '64.8529'},
  '2025-07-21': {'RSI': '61.7118'},
  '2025-07-18': {'RSI': '59.4324'},
  '2025-07-17': {'RSI': '57.3274'},
  '2025-07-16': {'RSI': '57.6627'},
  '2025-07-15': {'RSI': '55.8649'},
  '2025-07-14': {'RSI': '55.0376'},
  '2025-07-11': {'RSI': '60.4962'},
  '2025-07-10': {'RSI': '63.3683'},
  '2025-07-09': {'RSI': '61.6506'},
  '2025-07-08': {'RSI': '60.1051'},
  '2025-07-07': {'RSI': '60.0257'},
  '2025-07-03': {'RSI': '67.5150'},
  '2025-07-02': {'RSI': '66.3115'},
  '2025-07-01': {'RSI': '60.6822'},
  '2025-06-30': {'RSI': '56.8409'},
  '2025-06-27': {'RSI': '49.8142'},
  '2025-06-26': {'RSI': '49.6653'},
  '2025-06-25': {'RSI': '50.6416'},
  '2025-06-24': {'RSI': '48.5277'},
  '2025-06-23': {'RSI': '50.4380'},
  '2025-06-20': {'RSI': '49.6715'},
  '2025-06-18': {'RSI': '42.3527'},
  '2025-06-17': {'RSI': '40.6483'},
  '2025-06-16': {'RSI': '44.2404'},
  '2025-06-13': {'RSI': '40.7978'},
  '2025-06-12': {'RSI': '44.3468'},
  '2025-06-11': {'RSI': '43.6517'},
  '2025-06-10': {'RSI': '48.9054'},
  '2025-06-09': {'RSI': '47.0494'},
  '2025-06-06': {'RSI': '50.4978'},
  '2025-06-05': {'RSI': '45.5630'},
  '2025-06-04': {'RSI': '48.5549'},
  '2025-06-03': {'RSI': '49.1709'},
  '2025-06-02': {'RSI': '46.9921'},
  '2025-05-30': {'RSI': '45.8246'},
  '2025-05-29': {'RSI': '44.6255'},
  '2025-05-28': {'RSI': '45.1097'},
  '2025-05-27': {'RSI': '44.8615'},
  '2025-05-23': {'RSI': '38.8184'},
  '2025-05-22': {'RSI': '44.3872'},
  '2025-05-21': {'RSI': '45.1075'},
  '2025-05-20': {'RSI': '50.0337'},
  '2025-05-19': {'RSI': '52.1629'},
  '2025-05-16': {'RSI': '54.9686'},
  '2025-05-15': {'RSI': '55.1798'},
  '2025-05-14': {'RSI': '56.1066'},
  '2025-05-13': {'RSI': '56.7097'},
  '2025-05-12': {'RSI': '55.1117'},
  '2025-05-09': {'RSI': '43.8694'},
  '2025-05-08': {'RSI': '42.7637'},
  '2025-05-07': {'RSI': '41.4875'},
  '2025-05-06': {'RSI': '43.1144'},
  '2025-05-05': {'RSI': '43.3800'},
  '2025-05-02': {'RSI': '48.0526'},
  '2025-05-01': {'RSI': '54.8171'},
  '2025-04-30': {'RSI': '54.2012'},
  '2025-04-29': {'RSI': '53.2706'},
  '2025-04-28': {'RSI': '52.5277'},
  '2025-04-25': {'RSI': '51.9577'},
  '2025-04-24': {'RSI': '51.3841'},
  '2025-04-23': {'RSI': '49.0436'},
  '2025-04-22': {'RSI': '45.9276'},
  '2025-04-21': {'RSI': '41.4243'},
  '2025-04-17': {'RSI': '43.3715'},
  '2025-04-16': {'RSI': '41.5619'},
  '2025-04-15': {'RSI': '45.4811'},
  '2025-04-14': {'RSI': '45.6742'},
  '2025-04-11': {'RSI': '43.0941'},
  '2025-04-10': {'RSI': '38.2795'},
  '2025-04-09': {'RSI': '41.8665'},
  '2025-04-08': {'RSI': '20.0578'},
  '2025-04-07': {'RSI': '22.7710'},
  '2025-04-04': {'RSI': '25.1933'},
  '2025-04-03': {'RSI': '31.9469'},
  '2025-04-02': {'RSI': '48.9924'},
  '2025-04-01': {'RSI': '48.1232'},
  '2025-03-31': {'RSI': '46.8498'},
  '2025-03-28': {'RSI': '41.5312'},
  '2025-03-27': {'RSI': '47.7755'},
  '2025-03-26': {'RSI': '44.7689'},
  '2025-03-25': {'RSI': '47.1825'},
  '2025-03-24': {'RSI': '43.3227'},
  '2025-03-21': {'RSI': '40.0065'},
  '2025-03-20': {'RSI': '33.9208'},
  '2025-03-19': {'RSI': '34.8173'},
  '2025-03-18': {'RSI': '31.0309'},
  '2025-03-17': {'RSI': '31.9153'},
  '2025-03-14': {'RSI': '31.2065'},
  '2025-03-13': {'RSI': '25.8519'},
  '2025-03-12': {'RSI': '30.0074'},
  '2025-03-11': {'RSI': '32.5787'},
  '2025-03-10': {'RSI': '37.7448'},
  '2025-03-07': {'RSI': '50.8018'},
  '2025-03-06': {'RSI': '45.1125'},
  '2025-03-05': {'RSI': '45.6498'},
  '2025-03-04': {'RSI': '45.8851'},
  '2025-03-03': {'RSI': '48.4469'},
  '2025-02-28': {'RSI': '53.4768'},
  '2025-02-27': {'RSI': '47.4386'},
  '2025-02-26': {'RSI': '51.6328'},
  '2025-02-25': {'RSI': '62.9070'},
  '2025-02-24': {'RSI': '63.0217'},
  '2025-02-21': {'RSI': '61.3293'},
  '2025-02-20': {'RSI': '61.8038'},
  '2025-02-19': {'RSI': '60.8392'},
  '2025-02-18': {'RSI': '60.4528'},
  '2025-02-14': {'RSI': '60.6333'},
  '2025-02-13': {'RSI': '57.8744'},
  '2025-02-12': {'RSI': '53.2571'},
  '2025-02-11': {'RSI': '48.4742'},
  '2025-02-10': {'RSI': '42.0335'},
  '2025-02-07': {'RSI': '41.6661'},
  '2025-02-06': {'RSI': '47.4481'},
  '2025-02-05': {'RSI': '46.5235'},
  '2025-02-04': {'RSI': '46.8604'},
  '2025-02-03': {'RSI': '41.1141'},
  '2025-01-31': {'RSI': '49.3858'},
  '2025-01-30': {'RSI': '51.2927'},
  '2025-01-29': {'RSI': '53.4251'},
  '2025-01-28': {'RSI': '52.2803'},
  '2025-01-27': {'RSI': '42.2072'},
  '2025-01-24': {'RSI': '30.7698'},
  '2025-01-23': {'RSI': '31.4891'},
  '2025-01-22': {'RSI': '31.6217'},
  '2025-01-21': {'RSI': '29.6975'},
  '2025-01-17': {'RSI': '35.4036'},
  '2025-01-16': {'RSI': '32.5850'},
  '2025-01-15': {'RSI': '42.1198'},
  '2025-01-14': {'RSI': '33.4881'},
  '2025-01-13': {'RSI': '34.6592'},
  '2025-01-10': {'RSI': '37.3095'},
  '2025-01-08': {'RSI': '44.9266'},
  '2025-01-07': {'RSI': '44.0380'},
  '2025-01-06': {'RSI': '48.1452'},
  '2025-01-03': {'RSI': '45.3638'},
  '2025-01-02': {'RSI': '46.0491'},
  '2024-12-31': {'RSI': '56.7159'},
  '2024-12-30': {'RSI': '60.2256'},
  '2024-12-27': {'RSI': '67.6263'},
  '2024-12-26': {'RSI': '76.4529'},
  '2024-12-24': {'RSI': '75.7503'},
  '2024-12-23': {'RSI': '73.0857'},
  '2024-12-20': {'RSI': '72.3342'},
  '2024-12-19': {'RSI': '67.2119'},
  '2024-12-18': {'RSI': '64.9831'},
  '2024-12-17': {'RSI': '80.9232'},
  '2024-12-16': {'RSI': '78.7480'},
  '2024-12-13': {'RSI': '75.6767'},
  '2024-12-12': {'RSI': '75.4845'},
  '2024-12-11': {'RSI': '73.8237'},
  '2024-12-10': {'RSI': '78.1017'},
  '2024-12-09': {'RSI': '77.1206'},
  '2024-12-06': {'RSI': '72.7799'},
  '2024-12-05': {'RSI': '73.4417'},
  '2024-12-04': {'RSI': '73.4080'},
  '2024-12-03': {'RSI': '73.0268'},
  '2024-12-02': {'RSI': '69.5860'},
  '2024-11-29': {'RSI': '66.6701'},
  '2024-11-27': {'RSI': '63.1901'},
  '2024-11-26': {'RSI': '63.5237'},
  '2024-11-25': {'RSI': '60.2402'},
  '2024-11-22': {'RSI': '55.0989'},
  '2024-11-21': {'RSI': '52.5342'},
  '2024-11-20': {'RSI': '53.5439'},
  '2024-11-19': {'RSI': '52.2660'},
  '2024-11-18': {'RSI': '51.8216'},
  '2024-11-15': {'RSI': '46.4438'},
  '2024-11-14': {'RSI': '52.2142'},
  '2024-11-13': {'RSI': '46.2434'},
  '2024-11-12': {'RSI': '44.3911'},
  '2024-11-11': {'RSI': '44.3911'},
  '2024-11-08': {'RSI': '48.8424'},
  '2024-11-07': {'RSI': '49.2959'},
  '2024-11-06': {'RSI': '40.2083'},
  '2024-11-05': {'RSI': '41.2614'},
  '2024-11-04': {'RSI': '38.3014'},
  '2024-11-01': {'RSI': '39.4553'},
  '2024-10-31': {'RSI': '43.5129'},
  '2024-10-30': {'RSI': '50.2096'},
  '2024-10-29': {'RSI': '57.1707'},
  '2024-10-28': {'RSI': '56.7496'},
  '2024-10-25': {'RSI': '53.6292'},
  '2024-10-24': {'RSI': '52.2798'},
  '2024-10-23': {'RSI': '52.6013'},
  '2024-10-22': {'RSI': '62.1239'},
  '2024-10-21': {'RSI': '63.4199'},
  '2024-10-18': {'RSI': '61.6463'},
  '2024-10-17': {'RSI': '58.0055'},
  '2024-10-16': {'RSI': '57.5194'},
  '2024-10-15': {'RSI': '61.1998'},
  '2024-10-14': {'RSI': '58.1356'},
  '2024-10-11': {'RSI': '53.0752'},
  '2024-10-10': {'RSI': '55.5527'},
  '2024-10-09': {'RSI': '56.3727'},
  '2024-10-08': {'RSI': '51.3445'},
  '2024-10-07': {'RSI': '44.9710'},
  '2024-10-04': {'RSI': '53.0533'},
  '2024-10-03': {'RSI': '51.2544'},
  '2024-10-02': {'RSI': '53.1106'},
  '2024-10-01': {'RSI': '52.2867'},
  '2024-09-30': {'RSI': '64.9027'},
  '2024-09-27': {'RSI': '57.6163'},
  '2024-09-26': {'RSI': '57.1886'},
  '2024-09-25': {'RSI': '55.4089'},
  '2024-09-24': {'RSI': '57.3333'},
  '2024-09-23': {'RSI': '56.0579'},
  '2024-09-20': {'RSI': '59.2176'},
  '2024-09-19': {'RSI': '60.4427'},
  '2024-09-18': {'RSI': '48.3214'},
  '2024-09-17': {'RSI': '40.2104'},
  '2024-09-16': {'RSI': '39.1415'},
  '2024-09-13': {'RSI': '50.0710'},
  '2024-09-12': {'RSI': '50.6447'},
  '2024-09-11': {'RSI': '50.4299'},
  '2024-09-10': {'RSI': '45.3042'},
  '2024-09-09': {'RSI': '46.7113'},
  '2024-09-06': {'RSI': '46.5378'},
  '2024-09-05': {'RSI': '49.1108'},
  '2024-09-04': {'RSI': '46.4126'},
  '2024-09-03': {'RSI': '49.4689'},
  '2024-08-30': {'RSI': '61.7137'},
  '2024-08-29': {'RSI': '63.5664'},
  '2024-08-28': {'RSI': '58.7647'},
  '2024-08-27': {'RSI': '62.3240'},
  '2024-08-26': {'RSI': '61.1170'},
  '2024-08-23': {'RSI': '60.6487'},
  '2024-08-22': {'RSI': '57.4132'},
  '2024-08-21': {'RSI': '61.1955'},
  '2024-08-20': {'RSI': '61.4165'},
  '2024-08-19': {'RSI': '60.6732'},
  '2024-08-16': {'RSI': '60.9546'},
  '2024-08-15': {'RSI': '59.5048'},
  '2024-08-14': {'RSI': '56.0901'},
  '2024-08-13': {'RSI': '55.5682'},
  '2024-08-12': {'RSI': '51.0813'},
  '2024-08-09': {'RSI': '49.1189'},
  '2024-08-08': {'RSI': '45.2380'},
  '2024-08-07': {'RSI': '40.1923'},
  '2024-08-06': {'RSI': '36.1375'},
  '2024-08-05': {'RSI': '38.0229'},
  '2024-08-02': {'RSI': '50.7984'},
  '2024-08-01': {'RSI': '48.5236'},
  '2024-07-31': {'RSI': '54.3057'},
  '2024-07-30': {'RSI': '49.3657'},
  '2024-07-29': {'RSI': '48.4828'},
  '2024-07-26': {'RSI': '48.0623'},
  '2024-07-25': {'RSI': '47.3930'},
  '2024-07-24': {'RSI': '48.6947'},
  '2024-07-23': {'RSI': '57.7744'},
  '2024-07-22': {'RSI': '56.5536'},
  '2024-07-19': {'RSI': '57.0642'},
  '2024-07-18': {'RSI': '56.9301'},
  '2024-07-17': {'RSI': '63.6003'},
  '2024-07-16': {'RSI': '73.7395'},
  '2024-07-15': {'RSI': '73.4617'},
  '2024-07-12': {'RSI': '70.8284'},
  '2024-07-11': {'RSI': '68.6025'},
  '2024-07-10': {'RSI': '78.7687'},
  '2024-07-09': {'RSI': '76.1614'},
  '2024-07-08': {'RSI': '75.6051'},
  '2024-07-05': {'RSI': '74.6600'},
  '2024-07-03': {'RSI': '71.3210'},
  '2024-07-02': {'RSI': '70.3516'},
  '2024-07-01': {'RSI': '67.5508'},
  '2024-06-28': {'RSI': '61.6999'},
  '2024-06-27': {'RSI': '68.1804'},
  '2024-06-26': {'RSI': '67.4039'},
  '2024-06-25': {'RSI': '63.3161'},
  '2024-06-24': {'RSI': '62.3403'},
  '2024-06-21': {'RSI': '61.6788'},
  '2024-06-20': {'RSI': '65.2655'},
  '2024-06-18': {'RSI': '73.6353'},
  '2024-06-17': {'RSI': '78.4588'},
  '2024-06-14': {'RSI': '75.8823'},
  '2024-06-13': {'RSI': '79.5828'},
  '2024-06-12': {'RSI': '78.9453'},
  '2024-06-11': {'RSI': '75.3261'},
  '2024-06-10': {'RSI': '60.3131'},
  '2024-06-07': {'RSI': '71.1088'},
  '2024-06-06': {'RSI': '67.6742'},
  '2024-06-05': {'RSI': '72.2760'},
  '2024-06-04': {'RSI': '70.2197'},
  '2024-06-03': {'RSI': '69.7816'},
  '2024-05-31': {'RSI': '67.2964'},
  '2024-05-30': {'RSI': '65.8916'},
  '2024-05-29': {'RSI': '64.4129'},
  '2024-05-28': {'RSI': '63.9779'},
  '2024-05-24': {'RSI': '63.9643'},
  '2024-05-23': {'RSI': '59.5579'},
  '2024-05-22': {'RSI': '69.8414'},
  '2024-05-21': {'RSI': '74.1283'},
  '2024-05-20': {'RSI': '72.7237'},
  '2024-05-17': {'RSI': '71.4378'},
  '2024-05-16': {'RSI': '71.4057'},
  '2024-05-15': {'RSI': '71.2858'},
  '2024-05-14': {'RSI': '68.9819'},
  '2024-05-13': {'RSI': '67.7763'},
  '2024-05-10': {'RSI': '64.1412'},
  '2024-05-09': {'RSI': '66.8925'},
  '2024-05-08': {'RSI': '64.8767'},
  '2024-05-07': {'RSI': '64.5038'},
  '2024-05-06': {'RSI': '63.7792'},
  '2024-05-03': {'RSI': '66.8460'},
  '2024-05-02': {'RSI': '54.1614'},
  '2024-05-01': {'RSI': '47.4307'},
  '2024-04-30': {'RSI': '49.2864'},
  '2024-04-29': {'RSI': '55.4907'},
  '2024-04-26': {'RSI': '47.3342'},
  '2024-04-25': {'RSI': '48.4934'},
  '2024-04-24': {'RSI': '46.7064'},
  '2024-04-23': {'RSI': '42.1661'},
  '2024-04-22': {'RSI': '39.7843'},
  '2024-04-19': {'RSI': '37.9024'},
  '2024-04-18': {'RSI': '40.7762'},
  '2024-04-17': {'RSI': '42.1734'},
  '2024-04-16': {'RSI': '44.1949'},
  '2024-04-15': {'RSI': '49.4768'},
  '2024-04-12': {'RSI': '56.8319'},
  '2024-04-11': {'RSI': '54.3678'},
  '2024-04-10': {'RSI': '38.7616'},
  '2024-04-09': {'RSI': '42.2549'},
  '2024-04-08': {'RSI': '38.9574'},
  '2024-04-05': {'RSI': '40.9696'},
  '2024-04-04': {'RSI': '39.0019'},
  '2024-04-03': {'RSI': '40.3664'},
  '2024-04-02': {'RSI': '38.4139'},
  '2024-04-01': {'RSI': '40.2099'},

In [25]:
# Lets see the keys

data.keys()

dict_keys(['Meta Data', 'Technical Analysis: RSI'])

In [26]:
data['Meta Data']

{'1: Symbol': 'AAPL',
 '2: Indicator': 'Relative Strength Index (RSI)',
 '3: Last Refreshed': '2026-06-05',
 '4: Interval': 'daily',
 '5: Time Period': 14,
 '6: Series Type': 'close',
 '7: Time Zone': 'US/Eastern Time'}

In [27]:
data['Technical Analysis: RSI']

{'2026-06-05': {'RSI': '60.8174'},
 '2026-06-04': {'RSI': '66.6123'},
 '2026-06-03': {'RSI': '65.8591'},
 '2026-06-02': {'RSI': '73.7247'},
 '2026-06-01': {'RSI': '67.1733'},
 '2026-05-29': {'RSI': '79.0043'},
 '2026-05-28': {'RSI': '80.0286'},
 '2026-05-27': {'RSI': '79.1004'},
 '2026-05-26': {'RSI': '77.6353'},
 '2026-05-22': {'RSI': '78.6306'},
 '2026-05-21': {'RSI': '76.4381'},
 '2026-05-20': {'RSI': '74.7148'},
 '2026-05-19': {'RSI': '72.4772'},
 '2026-05-18': {'RSI': '71.6754'},
 '2026-05-15': {'RSI': '76.0255'},
 '2026-05-14': {'RSI': '74.8264'},
 '2026-05-13': {'RSI': '75.9794'},
 '2026-05-12': {'RSI': '73.6550'},
 '2026-05-11': {'RSI': '72.3614'},
 '2026-05-08': {'RSI': '72.9413'},
 '2026-05-07': {'RSI': '69.3121'},
 '2026-05-06': {'RSI': '69.4150'},
 '2026-05-05': {'RSI': '67.2681'},
 '2026-05-04': {'RSI': '61.7677'},
 '2026-05-01': {'RSI': '66.4363'},
 '2026-04-30': {'RSI': '58.7476'},
 '2026-04-29': {'RSI': '57.5350'},
 '2026-04-28': {'RSI': '58.2628'},
 '2026-04-27': {'RSI': '55.2451'},
 '2026-04-24': {'RSI': '59.7062'},
 '2026-04-23': {'RSI': '62.9488'},
 '2026-04-22': {'RSI': '62.7427'},
 '2026-04-21': {'RSI': '56.7239'},
 '2026-04-20': {'RSI': '66.5332'},
 '2026-04-17': {'RSI': '64.1753'},
 '2026-04-16': {'RSI': '57.4299'},
 '2026-04-15': {'RSI': '62.2590'},
 '2026-04-14': {'RSI': '53.0676'},
 '2026-04-13': {'RSI': '53.6583'},
 '2026-04-10': {'RSI': '55.6483'},
 '2026-04-09': {'RSI': '55.6633'},
 '2026-04-08': {'RSI': '53.8288'},
 '2026-04-07': {'RSI': '46.8998'},
 '2026-04-06': {'RSI': '54.4283'},
 '2026-04-02': {'RSI': '50.3706'},
 '2026-04-01': {'RSI': '49.9626'},
 '2026-03-31': {'RSI': '47.4152'},
 '2026-03-30': {'RSI': '35.5613'},
 '2026-03-27': {'RSI': '37.9701'},
 '2026-03-26': {'RSI': '43.0769'},
 '2026-03-25': {'RSI': '42.6037'},
 '2026-03-24': {'RSI': '40.9493'},
 '2026-03-23': {'RSI': '40.7063'},
 '2026-03-20': {'RSI': '34.9042'},
 '2026-03-19': {'RSI': '35.8059'},
 '2026-03-18': {'RSI': '36.6952'},
 '2026-03-17': {'RSI': '40.8159'},
 '2026-03-16': {'RSI': '38.7156'},
 '2026-03-13': {'RSI': '34.5879'},
 '2026-03-12': {'RSI': '39.7856'},
 '2026-03-11': {'RSI': '45.4664'},
 '2026-03-10': {'RSI': '45.4903'},
 '2026-03-09': {'RSI': '44.1972'},
 '2026-03-06': {'RSI': '40.8798'},
 '2026-03-05': {'RSI': '43.7009'},
 '2026-03-04': {'RSI': '46.0249'},
 '2026-03-03': {'RSI': '47.3135'},
 '2026-03-02': {'RSI': '48.3039'},
 '2026-02-27': {'RSI': '47.7384'},
 '2026-02-26': {'RSI': '57.1699'},
 '2026-02-25': {'RSI': '58.7428'},
 '2026-02-24': {'RSI': '56.9469'},
 '2026-02-23': {'RSI': '51.3378'},
 '2026-02-20': {'RSI': '49.7044'},
 '2026-02-19': {'RSI': '45.4540'},
 '2026-02-18': {'RSI': '49.0843'},
 '2026-02-17': {'RSI': '48.6091'},
 '2026-02-13': {'RSI': '39.5871'},
 '2026-02-12': {'RSI': '44.9724'},
 '2026-02-11': {'RSI': '63.5509'},
 '2026-02-10': {'RSI': '61.6042'},
 '2026-02-09': {'RSI': '63.2237'},
 '2026-02-06': {'RSI': '69.0258'},
 '2026-02-05': {'RSI': '67.1143'},
 '2026-02-04': {'RSI': '68.1390'},
 '2026-02-03': {'RSI': '61.5502'},
 '2026-02-02': {'RSI': '62.4570'},
 '2026-01-30': {'RSI': '48.4444'},
 '2026-01-29': {'RSI': '46.3244'},
 '2026-01-28': {'RSI': '42.9864'},
 '2026-01-27': {'RSI': '45.6056'},
 '2026-01-26': {'RSI': '40.3292'},
 '2026-01-23': {'RSI': '22.2920'},
 '2026-01-22': {'RSI': '22.5583'},
 '2026-01-21': {'RSI': '20.5685'},
 '2026-01-20': {'RSI': '17.9103'},
 '2026-01-16': {'RSI': '25.1841'},
 '2026-01-15': {'RSI': '28.4392'},
 '2026-01-14': {'RSI': '30.8576'},
 '2026-01-13': {'RSI': '32.4537'},
 '2026-01-12': {'RSI': '29.9856'},
 '2026-01-09': {'RSI': '27.2711'},
 '2026-01-08': {'RSI': '26.2758'},
 '2026-01-07': {'RSI': '27.6493'},
 '2026-01-06': {'RSI': '29.9358'},
 '2026-01-05': {'RSI': '36.7472'},
 '2026-01-02': {'RSI': '43.8351'},
 '2025-12-31': {'RSI': '45.6900'},
 '2025-12-30': {'RSI': '48.4207'},
 '2025-12-29': {'RSI': '49.9663'},
 '2025-12-26': {'RSI': '49.1687'},
 '2025-12-24': {'RSI': '50.0119'},
 '2025-12-23': {'RSI': '47.0288'},
 '2025-12-22': {'RSI': '44.0570'},
 '2025-12-19': {'RSI': '49.0170'},
 '2025-12-18': {'RSI': '45.9179'},
 '2025-12-17': {'RSI': '45.1863'},
 '2025-12-16': {'RSI': '50.1749'},
 '2025-12-15': {'RSI': '49.2355'},
 '2025-12-12': {'RSI': '57.6533'},
 '2025-12-11': {'RSI': '57.2463'},
 '2025-12-10': {'RSI': '58.8209'},
 '2025-12-09': {'RSI': '56.4479'},
 '2025-12-08': {'RSI': '57.8209'},
 '2025-12-05': {'RSI': '59.5055'},
 '2025-12-04': {'RSI': '63.1939'},
 '2025-12-03': {'RSI': '70.4832'},
 '2025-12-02': {'RSI': '75.2491'},
 '2025-12-01': {'RSI': '72.6478'},
 '2025-11-28': {'RSI': '68.4071'},
 '2025-11-26': {'RSI': '66.9518'},
 '2025-11-25': {'RSI': '66.3088'},
 '2025-11-24': {'RSI': '65.1696'},
 '2025-11-21': {'RSI': '59.8515'},
 '2025-11-20': {'RSI': '51.7617'},
 '2025-11-19': {'RSI': '56.4150'},
 '2025-11-18': {'RSI': '54.5765'},
 '2025-11-17': {'RSI': '54.6147'},
 '2025-11-14': {'RSI': '65.0838'},
 '2025-11-13': {'RSI': '66.3726'},
 '2025-11-12': {'RSI': '67.5691'},
 '2025-11-11': {'RSI': '71.6759'},
 '2025-11-10': {'RSI': '65.2664'},
 '2025-11-07': {'RSI': '63.6675'},
 '2025-11-06': {'RSI': '66.7057'},
 '2025-11-05': {'RSI': '67.5577'},
 '2025-11-04': {'RSI': '67.4534'},
 '2025-11-03': {'RSI': '66.4619'},
 '2025-10-31': {'RSI': '69.0668'},
 '2025-10-30': {'RSI': '71.0856'},
 '2025-10-29': {'RSI': '69.7296'},
 '2025-10-28': {'RSI': '69.1769'},
 '2025-10-27': {'RSI': '69.0344'},
 '2025-10-24': {'RSI': '64.1875'},
 '2025-10-23': {'RSI': '61.1318'},
 '2025-10-22': {'RSI': '60.0273'},
 '2025-10-21': {'RSI': '66.7624'},
 '2025-10-20': {'RSI': '66.3321'},
 '2025-10-17': {'RSI': '56.5175'},
 '2025-10-16': {'RSI': '49.9239'},
 '2025-10-15': {'RSI': '52.8287'},
 '2025-10-14': {'RSI': '50.6122'},
 '2025-10-13': {'RSI': '50.4607'},
 '2025-10-10': {'RSI': '47.1938'},
 '2025-10-09': {'RSI': '60.8718'},
 '2025-10-08': {'RSI': '69.4377'},
 '2025-10-07': {'RSI': '67.7831'},
 '2025-10-06': {'RSI': '68.2391'},
 '2025-10-03': {'RSI': '71.0497'},
 '2025-10-02': {'RSI': '70.2893'},
 '2025-10-01': {'RSI': '68.8555'},
 '2025-09-30': {'RSI': '68.1590'},
 '2025-09-29': {'RSI': '67.9969'},
 '2025-09-26': {'RSI': '69.6935'},
 '2025-09-25': {'RSI': '71.9762'},
 '2025-09-24': {'RSI': '68.9190'},
 '2025-09-23': {'RSI': '72.3252'},
 '2025-09-22': {'RSI': '75.0043'},
 '2025-09-19': {'RSI': '67.9316'},
 '2025-09-18': {'RSI': '60.4466'},
 '2025-09-17': {'RSI': '62.4172'},
 '2025-09-16': {'RSI': '61.5361'},
 '2025-09-15': {'RSI': '60.0341'},
 '2025-09-12': {'RSI': '57.2207'},
 '2025-09-11': {'RSI': '52.4456'},
 '2025-09-10': {'RSI': '48.1344'},
 '2025-09-09': {'RSI': '59.9006'},
 '2025-09-08': {'RSI': '67.0019'},
 '2025-09-05': {'RSI': '71.0101'},
 '2025-09-04': {'RSI': '71.2068'},
 '2025-09-03': {'RSI': '70.0870'},
 '2025-09-02': {'RSI': '60.5777'},
 '2025-08-29': {'RSI': '65.9630'},
 '2025-08-28': {'RSI': '66.9217'},
 '2025-08-27': {'RSI': '64.5646'},
 '2025-08-26': {'RSI': '63.1756'},
 '2025-08-25': {'RSI': '60.5599'},
 '2025-08-22': {'RSI': '61.6955'},
 '2025-08-21': {'RSI': '58.2285'},
 '2025-08-20': {'RSI': '60.1920'},
 '2025-08-19': {'RSI': '69.0548'},
 '2025-08-18': {'RSI': '69.7465'},
 '2025-08-15': {'RSI': '71.1501'},
 '2025-08-14': {'RSI': '73.4846'},
 '2025-08-13': {'RSI': '74.5342'},
 '2025-08-12': {'RSI': '72.0543'},
 '2025-08-11': {'RSI': '70.2486'},
 '2025-08-08': {'RSI': '73.6623'},
 '2025-08-07': {'RSI': '66.2258'},
 '2025-08-06': {'RSI': '58.2659'},
 '2025-08-05': {'RSI': '37.3892'},
 '2025-08-04': {'RSI': '38.1264'},
 '2025-08-01': {'RSI': '35.4609'},
 '2025-07-31': {'RSI': '45.1175'},
 '2025-07-30': {'RSI': '48.6237'},
 '2025-07-29': {'RSI': '54.5256'},
 '2025-07-28': {'RSI': '63.4862'},
 '2025-07-25': {'RSI': '63.1422'},
 '2025-07-24': {'RSI': '62.9133'},
 '2025-07-23': {'RSI': '64.1153'},
 '2025-07-22': {'RSI': '64.8529'},
 '2025-07-21': {'RSI': '61.7118'},
 '2025-07-18': {'RSI': '59.4324'},
 '2025-07-17': {'RSI': '57.3274'},
 '2025-07-16': {'RSI': '57.6627'},
 '2025-07-15': {'RSI': '55.8649'},
 '2025-07-14': {'RSI': '55.0376'},
 '2025-07-11': {'RSI': '60.4962'},
 '2025-07-10': {'RSI': '63.3683'},
 '2025-07-09': {'RSI': '61.6506'},
 '2025-07-08': {'RSI': '60.1051'},
 '2025-07-07': {'RSI': '60.0257'},
 '2025-07-03': {'RSI': '67.5150'},
 '2025-07-02': {'RSI': '66.3115'},
 '2025-07-01': {'RSI': '60.6822'},
 '2025-06-30': {'RSI': '56.8409'},
 '2025-06-27': {'RSI': '49.8142'},
 '2025-06-26': {'RSI': '49.6653'},
 '2025-06-25': {'RSI': '50.6416'},
 '2025-06-24': {'RSI': '48.5277'},
 '2025-06-23': {'RSI': '50.4380'},
 '2025-06-20': {'RSI': '49.6715'},
 '2025-06-18': {'RSI': '42.3527'},
 '2025-06-17': {'RSI': '40.6483'},
 '2025-06-16': {'RSI': '44.2404'},
 '2025-06-13': {'RSI': '40.7978'},
 '2025-06-12': {'RSI': '44.3468'},
 '2025-06-11': {'RSI': '43.6517'},
 '2025-06-10': {'RSI': '48.9054'},
 '2025-06-09': {'RSI': '47.0494'},
 '2025-06-06': {'RSI': '50.4978'},
 '2025-06-05': {'RSI': '45.5630'},
 '2025-06-04': {'RSI': '48.5549'},
 '2025-06-03': {'RSI': '49.1709'},
 '2025-06-02': {'RSI': '46.9921'},
 '2025-05-30': {'RSI': '45.8246'},
 '2025-05-29': {'RSI': '44.6255'},
 '2025-05-28': {'RSI': '45.1097'},
 '2025-05-27': {'RSI': '44.8615'},
 '2025-05-23': {'RSI': '38.8184'},
 '2025-05-22': {'RSI': '44.3872'},
 '2025-05-21': {'RSI': '45.1075'},
 '2025-05-20': {'RSI': '50.0337'},
 '2025-05-19': {'RSI': '52.1629'},
 '2025-05-16': {'RSI': '54.9686'},
 '2025-05-15': {'RSI': '55.1798'},
 '2025-05-14': {'RSI': '56.1066'},
 '2025-05-13': {'RSI': '56.7097'},
 '2025-05-12': {'RSI': '55.1117'},
 '2025-05-09': {'RSI': '43.8694'},
 '2025-05-08': {'RSI': '42.7637'},
 '2025-05-07': {'RSI': '41.4875'},
 '2025-05-06': {'RSI': '43.1144'},
 '2025-05-05': {'RSI': '43.3800'},
 '2025-05-02': {'RSI': '48.0526'},
 '2025-05-01': {'RSI': '54.8171'},
 '2025-04-30': {'RSI': '54.2012'},
 '2025-04-29': {'RSI': '53.2706'},
 '2025-04-28': {'RSI': '52.5277'},
 '2025-04-25': {'RSI': '51.9577'},
 '2025-04-24': {'RSI': '51.3841'},
 '2025-04-23': {'RSI': '49.0436'},
 '2025-04-22': {'RSI': '45.9276'},
 '2025-04-21': {'RSI': '41.4243'},
 '2025-04-17': {'RSI': '43.3715'},
 '2025-04-16': {'RSI': '41.5619'},
 '2025-04-15': {'RSI': '45.4811'},
 '2025-04-14': {'RSI': '45.6742'},
 '2025-04-11': {'RSI': '43.0941'},
 '2025-04-10': {'RSI': '38.2795'},
 '2025-04-09': {'RSI': '41.8665'},
 '2025-04-08': {'RSI': '20.0578'},
 '2025-04-07': {'RSI': '22.7710'},
 '2025-04-04': {'RSI': '25.1933'},
 '2025-04-03': {'RSI': '31.9469'},
 '2025-04-02': {'RSI': '48.9924'},
 '2025-04-01': {'RSI': '48.1232'},
 '2025-03-31': {'RSI': '46.8498'},
 '2025-03-28': {'RSI': '41.5312'},
 '2025-03-27': {'RSI': '47.7755'},
 '2025-03-26': {'RSI': '44.7689'},
 '2025-03-25': {'RSI': '47.1825'},
 '2025-03-24': {'RSI': '43.3227'},
 '2025-03-21': {'RSI': '40.0065'},
 '2025-03-20': {'RSI': '33.9208'},
 '2025-03-19': {'RSI': '34.8173'},
 '2025-03-18': {'RSI': '31.0309'},
 '2025-03-17': {'RSI': '31.9153'},
 '2025-03-14': {'RSI': '31.2065'},
 '2025-03-13': {'RSI': '25.8519'},
 '2025-03-12': {'RSI': '30.0074'},
 '2025-03-11': {'RSI': '32.5787'},
 '2025-03-10': {'RSI': '37.7448'},
 '2025-03-07': {'RSI': '50.8018'},
 '2025-03-06': {'RSI': '45.1125'},
 '2025-03-05': {'RSI': '45.6498'},
 '2025-03-04': {'RSI': '45.8851'},
 '2025-03-03': {'RSI': '48.4469'},
 '2025-02-28': {'RSI': '53.4768'},
 '2025-02-27': {'RSI': '47.4386'},
 '2025-02-26': {'RSI': '51.6328'},
 '2025-02-25': {'RSI': '62.9070'},
 '2025-02-24': {'RSI': '63.0217'},
 '2025-02-21': {'RSI': '61.3293'},
 '2025-02-20': {'RSI': '61.8038'},
 '2025-02-19': {'RSI': '60.8392'},
 '2025-02-18': {'RSI': '60.4528'},
 '2025-02-14': {'RSI': '60.6333'},
 '2025-02-13': {'RSI': '57.8744'},
 '2025-02-12': {'RSI': '53.2571'},
 '2025-02-11': {'RSI': '48.4742'},
 '2025-02-10': {'RSI': '42.0335'},
 '2025-02-07': {'RSI': '41.6661'},
 '2025-02-06': {'RSI': '47.4481'},
 '2025-02-05': {'RSI': '46.5235'},
 '2025-02-04': {'RSI': '46.8604'},
 '2025-02-03': {'RSI': '41.1141'},
 '2025-01-31': {'RSI': '49.3858'},
 '2025-01-30': {'RSI': '51.2927'},
 '2025-01-29': {'RSI': '53.4251'},
 '2025-01-28': {'RSI': '52.2803'},
 '2025-01-27': {'RSI': '42.2072'},
 '2025-01-24': {'RSI': '30.7698'},
 '2025-01-23': {'RSI': '31.4891'},
 '2025-01-22': {'RSI': '31.6217'},
 '2025-01-21': {'RSI': '29.6975'},
 '2025-01-17': {'RSI': '35.4036'},
 '2025-01-16': {'RSI': '32.5850'},
 '2025-01-15': {'RSI': '42.1198'},
 '2025-01-14': {'RSI': '33.4881'},
 '2025-01-13': {'RSI': '34.6592'},
 '2025-01-10': {'RSI': '37.3095'},
 '2025-01-08': {'RSI': '44.9266'},
 '2025-01-07': {'RSI': '44.0380'},
 '2025-01-06': {'RSI': '48.1452'},
 '2025-01-03': {'RSI': '45.3638'},
 '2025-01-02': {'RSI': '46.0491'},
 '2024-12-31': {'RSI': '56.7159'},
 '2024-12-30': {'RSI': '60.2256'},
 '2024-12-27': {'RSI': '67.6263'},
 '2024-12-26': {'RSI': '76.4529'},
 '2024-12-24': {'RSI': '75.7503'},
 '2024-12-23': {'RSI': '73.0857'},
 '2024-12-20': {'RSI': '72.3342'},
 '2024-12-19': {'RSI': '67.2119'},
 '2024-12-18': {'RSI': '64.9831'},
 '2024-12-17': {'RSI': '80.9232'},
 '2024-12-16': {'RSI': '78.7480'},
 '2024-12-13': {'RSI': '75.6767'},
 '2024-12-12': {'RSI': '75.4845'},
 '2024-12-11': {'RSI': '73.8237'},
 '2024-12-10': {'RSI': '78.1017'},
 '2024-12-09': {'RSI': '77.1206'},
 '2024-12-06': {'RSI': '72.7799'},
 '2024-12-05': {'RSI': '73.4417'},
 '2024-12-04': {'RSI': '73.4080'},
 '2024-12-03': {'RSI': '73.0268'},
 '2024-12-02': {'RSI': '69.5860'},
 '2024-11-29': {'RSI': '66.6701'},
 '2024-11-27': {'RSI': '63.1901'},
 '2024-11-26': {'RSI': '63.5237'},
 '2024-11-25': {'RSI': '60.2402'},
 '2024-11-22': {'RSI': '55.0989'},
 '2024-11-21': {'RSI': '52.5342'},
 '2024-11-20': {'RSI': '53.5439'},
 '2024-11-19': {'RSI': '52.2660'},
 '2024-11-18': {'RSI': '51.8216'},
 '2024-11-15': {'RSI': '46.4438'},
 '2024-11-14': {'RSI': '52.2142'},
 '2024-11-13': {'RSI': '46.2434'},
 '2024-11-12': {'RSI': '44.3911'},
 '2024-11-11': {'RSI': '44.3911'},
 '2024-11-08': {'RSI': '48.8424'},
 '2024-11-07': {'RSI': '49.2959'},
 '2024-11-06': {'RSI': '40.2083'},
 '2024-11-05': {'RSI': '41.2614'},
 '2024-11-04': {'RSI': '38.3014'},
 '2024-11-01': {'RSI': '39.4553'},
 '2024-10-31': {'RSI': '43.5129'},
 '2024-10-30': {'RSI': '50.2096'},
 '2024-10-29': {'RSI': '57.1707'},
 '2024-10-28': {'RSI': '56.7496'},
 '2024-10-25': {'RSI': '53.6292'},
 '2024-10-24': {'RSI': '52.2798'},
 '2024-10-23': {'RSI': '52.6013'},
 '2024-10-22': {'RSI': '62.1239'},
 '2024-10-21': {'RSI': '63.4199'},
 '2024-10-18': {'RSI': '61.6463'},
 '2024-10-17': {'RSI': '58.0055'},
 '2024-10-16': {'RSI': '57.5194'},
 '2024-10-15': {'RSI': '61.1998'},
 '2024-10-14': {'RSI': '58.1356'},
 '2024-10-11': {'RSI': '53.0752'},
 '2024-10-10': {'RSI': '55.5527'},
 '2024-10-09': {'RSI': '56.3727'},
 '2024-10-08': {'RSI': '51.3445'},
 '2024-10-07': {'RSI': '44.9710'},
 '2024-10-04': {'RSI': '53.0533'},
 '2024-10-03': {'RSI': '51.2544'},
 '2024-10-02': {'RSI': '53.1106'},
 '2024-10-01': {'RSI': '52.2867'},
 '2024-09-30': {'RSI': '64.9027'},
 '2024-09-27': {'RSI': '57.6163'},
 '2024-09-26': {'RSI': '57.1886'},
 '2024-09-25': {'RSI': '55.4089'},
 '2024-09-24': {'RSI': '57.3333'},
 '2024-09-23': {'RSI': '56.0579'},
 '2024-09-20': {'RSI': '59.2176'},
 '2024-09-19': {'RSI': '60.4427'},
 '2024-09-18': {'RSI': '48.3214'},
 '2024-09-17': {'RSI': '40.2104'},
 '2024-09-16': {'RSI': '39.1415'},
 '2024-09-13': {'RSI': '50.0710'},
 '2024-09-12': {'RSI': '50.6447'},
 '2024-09-11': {'RSI': '50.4299'},
 '2024-09-10': {'RSI': '45.3042'},
 '2024-09-09': {'RSI': '46.7113'},
 '2024-09-06': {'RSI': '46.5378'},
 '2024-09-05': {'RSI': '49.1108'},
 '2024-09-04': {'RSI': '46.4126'},
 '2024-09-03': {'RSI': '49.4689'},
 '2024-08-30': {'RSI': '61.7137'},
 '2024-08-29': {'RSI': '63.5664'},
 '2024-08-28': {'RSI': '58.7647'},
 '2024-08-27': {'RSI': '62.3240'},
 '2024-08-26': {'RSI': '61.1170'},
 '2024-08-23': {'RSI': '60.6487'},
 '2024-08-22': {'RSI': '57.4132'},
 '2024-08-21': {'RSI': '61.1955'},
 '2024-08-20': {'RSI': '61.4165'},
 '2024-08-19': {'RSI': '60.6732'},
 '2024-08-16': {'RSI': '60.9546'},
 '2024-08-15': {'RSI': '59.5048'},
 '2024-08-14': {'RSI': '56.0901'},
 '2024-08-13': {'RSI': '55.5682'},
 '2024-08-12': {'RSI': '51.0813'},
 '2024-08-09': {'RSI': '49.1189'},
 '2024-08-08': {'RSI': '45.2380'},
 '2024-08-07': {'RSI': '40.1923'},
 '2024-08-06': {'RSI': '36.1375'},
 '2024-08-05': {'RSI': '38.0229'},
 '2024-08-02': {'RSI': '50.7984'},
 '2024-08-01': {'RSI': '48.5236'},
 '2024-07-31': {'RSI': '54.3057'},
 '2024-07-30': {'RSI': '49.3657'},
 '2024-07-29': {'RSI': '48.4828'},
 '2024-07-26': {'RSI': '48.0623'},
 '2024-07-25': {'RSI': '47.3930'},
 '2024-07-24': {'RSI': '48.6947'},
 '2024-07-23': {'RSI': '57.7744'},
 '2024-07-22': {'RSI': '56.5536'},
 '2024-07-19': {'RSI': '57.0642'},
 '2024-07-18': {'RSI': '56.9301'},
 '2024-07-17': {'RSI': '63.6003'},
 '2024-07-16': {'RSI': '73.7395'},
 '2024-07-15': {'RSI': '73.4617'},
 '2024-07-12': {'RSI': '70.8284'},
 '2024-07-11': {'RSI': '68.6025'},
 '2024-07-10': {'RSI': '78.7687'},
 '2024-07-09': {'RSI': '76.1614'},
 '2024-07-08': {'RSI': '75.6051'},
 '2024-07-05': {'RSI': '74.6600'},
 '2024-07-03': {'RSI': '71.3210'},
 '2024-07-02': {'RSI': '70.3516'},
 '2024-07-01': {'RSI': '67.5508'},
 '2024-06-28': {'RSI': '61.6999'},
 '2024-06-27': {'RSI': '68.1804'},
 '2024-06-26': {'RSI': '67.4039'},
 '2024-06-25': {'RSI': '63.3161'},
 '2024-06-24': {'RSI': '62.3403'},
 '2024-06-21': {'RSI': '61.6788'},
 '2024-06-20': {'RSI': '65.2655'},
 '2024-06-18': {'RSI': '73.6353'},
 '2024-06-17': {'RSI': '78.4588'},
 '2024-06-14': {'RSI': '75.8823'},
 '2024-06-13': {'RSI': '79.5828'},
 '2024-06-12': {'RSI': '78.9453'},
 '2024-06-11': {'RSI': '75.3261'},
 '2024-06-10': {'RSI': '60.3131'},
 '2024-06-07': {'RSI': '71.1088'},
 '2024-06-06': {'RSI': '67.6742'},
 '2024-06-05': {'RSI': '72.2760'},
 '2024-06-04': {'RSI': '70.2197'},
 '2024-06-03': {'RSI': '69.7816'},
 '2024-05-31': {'RSI': '67.2964'},
 '2024-05-30': {'RSI': '65.8916'},
 '2024-05-29': {'RSI': '64.4129'},
 '2024-05-28': {'RSI': '63.9779'},
 '2024-05-24': {'RSI': '63.9643'},
 '2024-05-23': {'RSI': '59.5579'},
 '2024-05-22': {'RSI': '69.8414'},
 '2024-05-21': {'RSI': '74.1283'},
 '2024-05-20': {'RSI': '72.7237'},
 '2024-05-17': {'RSI': '71.4378'},
 '2024-05-16': {'RSI': '71.4057'},
 '2024-05-15': {'RSI': '71.2858'},
 '2024-05-14': {'RSI': '68.9819'},
 '2024-05-13': {'RSI': '67.7763'},
 '2024-05-10': {'RSI': '64.1412'},
 '2024-05-09': {'RSI': '66.8925'},
 '2024-05-08': {'RSI': '64.8767'},
 '2024-05-07': {'RSI': '64.5038'},
 '2024-05-06': {'RSI': '63.7792'},
 '2024-05-03': {'RSI': '66.8460'},
 '2024-05-02': {'RSI': '54.1614'},
 '2024-05-01': {'RSI': '47.4307'},
 '2024-04-30': {'RSI': '49.2864'},
 '2024-04-29': {'RSI': '55.4907'},
 '2024-04-26': {'RSI': '47.3342'},
 '2024-04-25': {'RSI': '48.4934'},
 '2024-04-24': {'RSI': '46.7064'},
 '2024-04-23': {'RSI': '42.1661'},
 '2024-04-22': {'RSI': '39.7843'},
 '2024-04-19': {'RSI': '37.9024'},
 '2024-04-18': {'RSI': '40.7762'},
 '2024-04-17': {'RSI': '42.1734'},
 '2024-04-16': {'RSI': '44.1949'},
 '2024-04-15': {'RSI': '49.4768'},
 '2024-04-12': {'RSI': '56.8319'},
 '2024-04-11': {'RSI': '54.3678'},
 '2024-04-10': {'RSI': '38.7616'},
 '2024-04-09': {'RSI': '42.2549'},
 '2024-04-08': {'RSI': '38.9574'},
 '2024-04-05': {'RSI': '40.9696'},
 '2024-04-04': {'RSI': '39.0019'},
 '2024-04-03': {'RSI': '40.3664'},
 '2024-04-02': {'RSI': '38.4139'},
 '2024-04-01': {'RSI': '40.2099'},
 '2024-03-28': {'RSI': '42.4559'},
 '2024-03-27': {'RSI': '45.4296'},
 '2024-03-26': {'RSI': '37.4231'},
 '2024-03-25': {'RSI': '39.1104'},
 '2024-03-22': {'RSI': '41.2782'},
 '2024-03-21': {'RSI': '39.2898'},
 '2024-03-20': {'RSI': '52.5431'},
 '2024-03-19': {'RSI': '46.6098'},
 '2024-03-18': {'RSI': '40.2937'},
 '2024-03-15': {'RSI': '37.0717'},
 '2024-03-14': {'RSI': '37.7247'},
 '2024-03-13': {'RSI': '32.2730'},
 '2024-03-12': {'RSI': '35.5151'},
 '2024-03-11': {'RSI': '34.1102'},
 '2024-03-08': {'RSI': '27.9787'},
 '2024-03-07': {'RSI': '22.2228'},
 '2024-03-06': {'RSI': '22.3378'},
 '2024-03-05': {'RSI': '23.2695'},
 '2024-03-04': {'RSI': '28.8299'},
 '2024-03-01': {'RSI': '36.1811'},
 '2024-02-29': {'RSI': '38.3516'},
 '2024-02-28': {'RSI': '39.7114'},
 '2024-02-27': {'RSI': '42.2219'},

In [28]:
# Step 1: Load dictionary using 'index' orientation
df = pd.DataFrame.from_dict(data['Technical Analysis: RSI'], orient='index')

# Step 2: Convert the date index to actual datetime objects
df.index = pd.to_datetime(df.index)
df.index.name = 'Date'

# Step 3: Convert the RSI column from text to numeric floats
df['RSI'] = pd.to_numeric(df['RSI'])

# Step 4: Sort chronologically (oldest date to newest date)
df = df.sort_index()

print(df)

                RSI
Date
1999-11-19  69.9838
1999-11-22  66.4703
1999-11-23  68.5184
1999-11-24  70.2012
1999-11-26  70.5350
...             ...
2026-06-01  67.1733
2026-06-02  73.7247
2026-06-03  65.8591
2026-06-04  66.6123
2026-06-05  60.8174

[6675 rows x 1 columns]

# 5) Forex Data

In [29]:
url = (
    f"https://www.alphavantage.co/query?"
    f"function=FX_DAILY"
    f"&from_symbol=USD"
    f"&to_symbol=INR"  # INDIA is INR, Jordan is JOD
    f"&apikey={ALPHAADVANTAGE_API_KEY}"
)

data = requests.get(url).json()

In [30]:
data

{'Meta Data': {'1. Information': 'Forex Daily Prices (open, high, low, close)',
  '2. From Symbol': 'USD',
  '3. To Symbol': 'INR',
  '4. Output Size': 'Compact',
  '5. Last Refreshed': '2026-06-05',
  '6. Time Zone': 'UTC'},
 'Time Series FX (Daily)': {'2026-06-05': {'1. open': '95.71250',
   '2. high': '95.77000',
   '3. low': '94.88500',
   '4. close': '94.94500'},
  '2026-06-04': {'1. open': '95.70000',
   '2. high': '95.79000',
   '3. low': '95.59500',
   '4. close': '95.78000'},
  '2026-06-03': {'1. open': '95.26000',
   '2. high': '95.79500',
   '3. low': '95.26000',
   '4. close': '95.70500'},
  '2026-06-02': {'1. open': '95.05000',
   '2. high': '95.28250',
   '3. low': '95.02250',
   '4. close': '95.26000'},
  '2026-06-01': {'1. open': '94.97000',
   '2. high': '95.03750',
   '3. low': '94.72750',
   '4. close': '94.99000'},
  '2026-05-29': {'1. open': '95.68000',
   '2. high': '95.68000',
   '3. low': '94.95250',
   '4. close': '95.00000'},
  '2026-05-28': {'1. open': '95.69000',
   '2. high': '95.69000',
   '3. low': '95.68000',
   '4. close': '95.68000'},
  '2026-05-27': {'1. open': '95.75000',
   '2. high': '95.79250',
   '3. low': '95.65000',
   '4. close': '95.69000'},
  '2026-05-26': {'1. open': '95.38000',
   '2. high': '95.68000',
   '3. low': '95.34000',
   '4. close': '95.68000'},
  '2026-05-25': {'1. open': '95.35000',
   '2. high': '95.44500',
   '3. low': '95.10750',
   '4. close': '95.23000'},
  '2026-05-22': {'1. open': '96.20000',
   '2. high': '96.30000',
   '3. low': '95.68000',
   '4. close': '95.69000'},
  '2026-05-21': {'1. open': '96.30000',
   '2. high': '96.50250',
   '3. low': '96.03250',
   '4. close': '96.20000'},
  '2026-05-20': {'1. open': '96.86000',
   '2. high': '96.96000',
   '3. low': '96.71500',
   '4. close': '96.82000'},
  '2026-05-19': {'1. open': '96.36500',
   '2. high': '96.61500',
   '3. low': '96.27000',
   '4. close': '96.53250'},
  '2026-05-18': {'1. open': '96.16500',
   '2. high': '96.38750',
   '3. low': '96.11500',
   '4. close': '96.34500'},
  '2026-05-15': {'1. open': '95.87000',
   '2. high': '96.13500',
   '3. low': '95.86000',
   '4. close': '95.96000'},
  '2026-05-14': {'1. open': '95.73000',
   '2. high': '95.95750',
   '3. low': '95.62000',
   '4. close': '95.76250'},
  '2026-05-13': {'1. open': '95.63000',
   '2. high': '95.79500',
   '3. low': '95.51250',
   '4. close': '95.69000'},
  '2026-05-12': {'1. open': '95.30000',
   '2. high': '95.73750',
   '3. low': '95.30000',
   '4. close': '95.63000'},
  '2026-05-11': {'1. open': '94.95000',
   '2. high': '95.31000',
   '3. low': '94.88000',
   '4. close': '95.31000'},
  '2026-05-08': {'1. open': '94.25000',
   '2. high': '94.67000',
   '3. low': '94.25000',
   '4. close': '94.38300'},
  '2026-05-07': {'1. open': '94.60500',
   '2. high': '94.90250',
   '3. low': '94.06500',
   '4. close': '94.25000'},
  '2026-05-06': {'1. open': '95.03500',
   '2. high': '95.17500',
   '3. low': '94.55870',
   '4. close': '94.61000'},
  '2026-05-05': {'1. open': '95.31000',
   '2. high': '95.43250',
   '3. low': '95.18000',
   '4. close': '95.18000'},
  '2026-05-04': {'1. open': '94.95000',
   '2. high': '95.08750',
   '3. low': '94.81000',
   '4. close': '95.08750'},
  '2026-05-01': {'1. open': '94.90000',
   '2. high': '94.90000',
   '3. low': '94.89000',
   '4. close': '94.89000'},
  '2026-04-30': {'1. open': '94.85000',
   '2. high': '95.33000',
   '3. low': '94.84000',
   '4. close': '94.90000'},
  '2026-04-29': {'1. open': '94.54000',
   '2. high': '94.85000',
   '3. low': '94.54000',
   '4. close': '94.85000'},
  '2026-04-28': {'1. open': '94.37000',
   '2. high': '94.57500',
   '3. low': '94.37000',
   '4. close': '94.54000'},
  '2026-04-27': {'1. open': '94.24500',
   '2. high': '94.28250',
   '3. low': '94.09620',
   '4. close': '94.19000'},
  '2026-04-24': {'1. open': '94.10000',
   '2. high': '94.30500',
   '3. low': '94.10000',
   '4. close': '94.24000'},
  '2026-04-23': {'1. open': '94.00500',
   '2. high': '94.15250',
   '3. low': '94.00000',
   '4. close': '94.10000'},
  '2026-04-22': {'1. open': '93.48000',
   '2. high': '93.86000',
   '3. low': '93.48000',
   '4. close': '93.79000'},
  '2026-04-21': {'1. open': '93.11000',
   '2. high': '93.62500',
   '3. low': '93.11000',
   '4. close': '93.48000'},
  '2026-04-20': {'1. open': '92.58600',
   '2. high': '93.23750',
   '3. low': '92.57900',
   '4. close': '93.11000'},
  '2026-04-17': {'1. open': '93.13000',
   '2. high': '93.13000',
   '3. low': '92.42400',
   '4. close': '92.59800'},
  '2026-04-16': {'1. open': '93.25000',
   '2. high': '93.38700',
   '3. low': '92.90600',
   '4. close': '93.02500'},
  '2026-04-15': {'1. open': '93.10100',
   '2. high': '93.49300',
   '3. low': '93.05800',
   '4. close': '93.35500'},
  '2026-04-14': {'1. open': '93.09800',
   '2. high': '93.40200',
   '3. low': '93.00800',
   '4. close': '93.14500'},
  '2026-04-13': {'1. open': '93.31300',
   '2. high': '93.42600',
   '3. low': '93.10000',
   '4. close': '93.21300'},
  '2026-04-10': {'1. open': '92.65200',
   '2. high': '93.07100',
   '3. low': '92.40400',
   '4. close': '93.07000'},
  '2026-04-09': {'1. open': '92.54000',
   '2. high': '92.91000',
   '3. low': '92.29300',
   '4. close': '92.45000'},
  '2026-04-08': {'1. open': '92.85000',
   '2. high': '92.85000',
   '3. low': '92.32700',
   '4. close': '92.58000'},
  '2026-04-07': {'1. open': '93.00250',
   '2. high': '93.07000',
   '3. low': '92.79800',
   '4. close': '92.84000'},
  '2026-04-06': {'1. open': '92.64500',
   '2. high': '93.18600',
   '3. low': '92.63900',
   '4. close': '93.06000'},
  '2026-04-03': {'1. open': '92.71300',
   '2. high': '92.75100',
   '3. low': '92.58500',
   '4. close': '92.69000'},
  '2026-04-02': {'1. open': '93.22400',
   '2. high': '93.68600',
   '3. low': '92.78900',
   '4. close': '92.95200'},
  '2026-04-01': {'1. open': '93.53900',
   '2. high': '93.88500',
   '3. low': '93.00800',
   '4. close': '93.20600'},
  '2026-03-31': {'1. open': '94.36800',
   '2. high': '94.37500',
   '3. low': '93.41100',
   '4. close': '93.45700'},
  '2026-03-30': {'1. open': '92.95200',
   '2. high': '95.21000',
   '3. low': '92.93200',
   '4. close': '94.35300'},
  '2026-03-27': {'1. open': '94.27700',
   '2. high': '94.98100',
   '3. low': '94.11100',
   '4. close': '94.77700'},
  '2026-03-26': {'1. open': '93.79000',
   '2. high': '94.28100',
   '3. low': '93.79000',
   '4. close': '94.26700'},
  '2026-03-25': {'1. open': '93.98500',
   '2. high': '94.20700',
   '3. low': '93.74300',
   '4. close': '93.88600'},
  '2026-03-24': {'1. open': '93.50000',
   '2. high': '94.12100',
   '3. low': '93.50000',
   '4. close': '94.01300'},
  '2026-03-23': {'1. open': '93.73800',
   '2. high': '94.12900',
   '3. low': '92.90300',
   '4. close': '93.19100'},
  '2026-03-20': {'1. open': '92.89400',
   '2. high': '93.80700',
   '3. low': '92.82900',
   '4. close': '93.67200'},
  '2026-03-19': {'1. open': '92.99900',
   '2. high': '93.37000',
   '3. low': '92.83800',
   '4. close': '92.89100'},
  '2026-03-18': {'1. open': '92.40200',
   '2. high': '93.10100',
   '3. low': '92.32400',
   '4. close': '93.10100'},
  '2026-03-17': {'1. open': '92.23000',
   '2. high': '92.47250',
   '3. low': '92.23000',
   '4. close': '92.37500'},
  '2026-03-16': {'1. open': '92.43000',
   '2. high': '92.47800',
   '3. low': '92.13900',
   '4. close': '92.23400'},
  '2026-03-13': {'1. open': '92.31200',
   '2. high': '92.55100',
   '3. low': '92.23200',
   '4. close': '92.51000'},
  '2026-03-12': {'1. open': '92.23800',
   '2. high': '92.49900',
   '3. low': '92.04000',
   '4. close': '92.36800'},
  '2026-03-11': {'1. open': '91.89400',
   '2. high': '92.23900',
   '3. low': '91.83000',
   '4. close': '92.20200'},
  '2026-03-10': {'1. open': '91.82200',
   '2. high': '92.19900',
   '3. low': '91.66900',
   '4. close': '91.94500'},
  '2026-03-09': {'1. open': '92.30000',
   '2. high': '92.37200',
   '3. low': '92.10100',
   '4. close': '92.13000'},
  '2026-03-06': {'1. open': '91.65200',
   '2. high': '91.99200',
   '3. low': '91.56500',
   '4. close': '91.92800'},
  '2026-03-05': {'1. open': '92.12700',
   '2. high': '92.15900',
   '3. low': '91.32200',
   '4. close': '91.75700'},
  '2026-03-04': {'1. open': '92.00700',
   '2. high': '92.30600',
   '3. low': '91.86300',
   '4. close': '92.09700'},
  '2026-03-03': {'1. open': '91.55000',
   '2. high': '92.22500',
   '3. low': '91.55000',
   '4. close': '92.03000'},
  '2026-03-02': {'1. open': '91.22900',
   '2. high': '91.76700',
   '3. low': '91.16200',
   '4. close': '91.55500'},
  '2026-02-27': {'1. open': '91.01700',
   '2. high': '91.13400',
   '3. low': '90.91000',
   '4. close': '91.04600'},
  '2026-02-26': {'1. open': '90.93600',
   '2. high': '91.06800',
   '3. low': '90.80100',
   '4. close': '90.97300'},
  '2026-02-25': {'1. open': '90.90800',
   '2. high': '90.96300',
   '3. low': '90.85500',
   '4. close': '90.87400'},
  '2026-02-24': {'1. open': '91.02100',
   '2. high': '91.02300',
   '3. low': '90.84700',
   '4. close': '90.89800'},
  '2026-02-23': {'1. open': '90.76000',
   '2. high': '91.01300',
   '3. low': '90.67500',
   '4. close': '91.01100'},
  '2026-02-20': {'1. open': '91.02500',
   '2. high': '91.08300',
   '3. low': '90.70100',
   '4. close': '90.70100'},
  '2026-02-19': {'1. open': '90.76300',
   '2. high': '91.20400',
   '3. low': '90.69000',
   '4. close': '91.01800'},
  '2026-02-18': {'1. open': '90.59700',
   '2. high': '90.78300',
   '3. low': '90.57000',
   '4. close': '90.77500'},
  '2026-02-17': {'1. open': '90.75600',
   '2. high': '90.79500',
   '3. low': '90.58700',
   '4. close': '90.62700'},
  '2026-02-16': {'1. open': '90.50600',
   '2. high': '90.82200',
   '3. low': '90.50000',
   '4. close': '90.75900'},
  '2026-02-13': {'1. open': '90.56100',
   '2. high': '90.75500',
   '3. low': '90.46200',
   '4. close': '90.52500'},
  '2026-02-12': {'1. open': '90.62300',
   '2. high': '90.72700',
   '3. low': '90.38500',
   '4. close': '90.54400'},
  '2026-02-11': {'1. open': '90.58200',
   '2. high': '90.82300',
   '3. low': '90.46000',
   '4. close': '90.73000'},
  '2026-02-10': {'1. open': '90.77200',
   '2. high': '90.78100',
   '3. low': '90.46300',
   '4. close': '90.55800'},
  '2026-02-09': {'1. open': '90.46500',
   '2. high': '90.79100',
   '3. low': '90.36750',
   '4. close': '90.72900'},
  '2026-02-06': {'1. open': '90.31000',
   '2. high': '90.84000',
   '3. low': '90.16800',
   '4. close': '90.57500'},
  '2026-02-05': {'1. open': '90.35700',
   '2. high': '90.51600',
   '3. low': '90.05500',
   '4. close': '90.31400'},
  '2026-02-04': {'1. open': '90.37200',
   '2. high': '90.53000',
   '3. low': '90.22600',
   '4. close': '90.37100'},
  '2026-02-03': {'1. open': '90.34800',
   '2. high': '90.51500',
   '3. low': '90.01400',
   '4. close': '90.39400'},
  '2026-02-02': {'1. open': '91.77300',
   '2. high': '92.01800',
   '3. low': '91.27000',
   '4. close': '91.27000'},
  '2026-01-30': {'1. open': '91.85000',
   '2. high': '92.00800',
   '3. low': '91.64500',
   '4. close': '91.67100'},
  '2026-01-29': {'1. open': '92.00300',
   '2. high': '92.12400',
   '3. low': '91.77000',
   '4. close': '91.77700'},
  '2026-01-28': {'1. open': '91.53000',
   '2. high': '92.21300',
   '3. low': '91.41300',
   '4. close': '92.02300'},
  '2026-01-27': {'1. open': '91.77000',
   '2. high': '91.89100',
   '3. low': '91.45200',
   '4. close': '91.45400'},
  '2026-01-26': {'1. open': '91.52600',
   '2. high': '91.78200',
   '3. low': '91.49300',
   '4. close': '91.68300'},
  '2026-01-23': {'1. open': '91.53500',
   '2. high': '91.98000',
   '3. low': '91.40500',
   '4. close': '91.65500'},
  '2026-01-22': {'1. open': '91.51000',
   '2. high': '91.67500',
   '3. low': '91.25700',
   '4. close': '91.55000'},
  '2026-01-21': {'1. open': '91.05000',
   '2. high': '91.74500',
   '3. low': '90.99300',
   '4. close': '91.52000'},
  '2026-01-20': {'1. open': '90.90000',
   '2. high': '91.09000',
   '3. low': '90.86300',
   '4. close': '91.08900'},
  '2026-01-19': {'1. open': '90.68800',
   '2. high': '91.01000',
   '3. low': '90.60120',
   '4. close': '90.87300'}}}

In [31]:
# Lets see the keys

data.keys()

dict_keys(['Meta Data', 'Time Series FX (Daily)'])

In [32]:
data['Meta Data']

{'1. Information': 'Forex Daily Prices (open, high, low, close)',
 '2. From Symbol': 'USD',
 '3. To Symbol': 'INR',
 '4. Output Size': 'Compact',
 '5. Last Refreshed': '2026-06-05',
 '6. Time Zone': 'UTC'}

In [33]:
data['Time Series FX (Daily)']

{'2026-06-05': {'1. open': '95.71250',
  '2. high': '95.77000',
  '3. low': '94.88500',
  '4. close': '94.94500'},
 '2026-06-04': {'1. open': '95.70000',
  '2. high': '95.79000',
  '3. low': '95.59500',
  '4. close': '95.78000'},
 '2026-06-03': {'1. open': '95.26000',
  '2. high': '95.79500',
  '3. low': '95.26000',
  '4. close': '95.70500'},
 '2026-06-02': {'1. open': '95.05000',
  '2. high': '95.28250',
  '3. low': '95.02250',
  '4. close': '95.26000'},
 '2026-06-01': {'1. open': '94.97000',
  '2. high': '95.03750',
  '3. low': '94.72750',
  '4. close': '94.99000'},
 '2026-05-29': {'1. open': '95.68000',
  '2. high': '95.68000',
  '3. low': '94.95250',
  '4. close': '95.00000'},
 '2026-05-28': {'1. open': '95.69000',
  '2. high': '95.69000',
  '3. low': '95.68000',
  '4. close': '95.68000'},
 '2026-05-27': {'1. open': '95.75000',
  '2. high': '95.79250',
  '3. low': '95.65000',
  '4. close': '95.69000'},
 '2026-05-26': {'1. open': '95.38000',
  '2. high': '95.68000',
  '3. low': '95.34000',
  '4. close': '95.68000'},
 '2026-05-25': {'1. open': '95.35000',
  '2. high': '95.44500',
  '3. low': '95.10750',
  '4. close': '95.23000'},
 '2026-05-22': {'1. open': '96.20000',
  '2. high': '96.30000',
  '3. low': '95.68000',
  '4. close': '95.69000'},
 '2026-05-21': {'1. open': '96.30000',
  '2. high': '96.50250',
  '3. low': '96.03250',
  '4. close': '96.20000'},
 '2026-05-20': {'1. open': '96.86000',
  '2. high': '96.96000',
  '3. low': '96.71500',
  '4. close': '96.82000'},
 '2026-05-19': {'1. open': '96.36500',
  '2. high': '96.61500',
  '3. low': '96.27000',
  '4. close': '96.53250'},
 '2026-05-18': {'1. open': '96.16500',
  '2. high': '96.38750',
  '3. low': '96.11500',
  '4. close': '96.34500'},
 '2026-05-15': {'1. open': '95.87000',
  '2. high': '96.13500',
  '3. low': '95.86000',
  '4. close': '95.96000'},
 '2026-05-14': {'1. open': '95.73000',
  '2. high': '95.95750',
  '3. low': '95.62000',
  '4. close': '95.76250'},
 '2026-05-13': {'1. open': '95.63000',
  '2. high': '95.79500',
  '3. low': '95.51250',
  '4. close': '95.69000'},
 '2026-05-12': {'1. open': '95.30000',
  '2. high': '95.73750',
  '3. low': '95.30000',
  '4. close': '95.63000'},
 '2026-05-11': {'1. open': '94.95000',
  '2. high': '95.31000',
  '3. low': '94.88000',
  '4. close': '95.31000'},
 '2026-05-08': {'1. open': '94.25000',
  '2. high': '94.67000',
  '3. low': '94.25000',
  '4. close': '94.38300'},
 '2026-05-07': {'1. open': '94.60500',
  '2. high': '94.90250',
  '3. low': '94.06500',
  '4. close': '94.25000'},
 '2026-05-06': {'1. open': '95.03500',
  '2. high': '95.17500',
  '3. low': '94.55870',
  '4. close': '94.61000'},
 '2026-05-05': {'1. open': '95.31000',
  '2. high': '95.43250',
  '3. low': '95.18000',
  '4. close': '95.18000'},
 '2026-05-04': {'1. open': '94.95000',
  '2. high': '95.08750',
  '3. low': '94.81000',
  '4. close': '95.08750'},
 '2026-05-01': {'1. open': '94.90000',
  '2. high': '94.90000',
  '3. low': '94.89000',
  '4. close': '94.89000'},
 '2026-04-30': {'1. open': '94.85000',
  '2. high': '95.33000',
  '3. low': '94.84000',
  '4. close': '94.90000'},
 '2026-04-29': {'1. open': '94.54000',
  '2. high': '94.85000',
  '3. low': '94.54000',
  '4. close': '94.85000'},
 '2026-04-28': {'1. open': '94.37000',
  '2. high': '94.57500',
  '3. low': '94.37000',
  '4. close': '94.54000'},
 '2026-04-27': {'1. open': '94.24500',
  '2. high': '94.28250',
  '3. low': '94.09620',
  '4. close': '94.19000'},
 '2026-04-24': {'1. open': '94.10000',
  '2. high': '94.30500',
  '3. low': '94.10000',
  '4. close': '94.24000'},
 '2026-04-23': {'1. open': '94.00500',
  '2. high': '94.15250',
  '3. low': '94.00000',
  '4. close': '94.10000'},
 '2026-04-22': {'1. open': '93.48000',
  '2. high': '93.86000',
  '3. low': '93.48000',
  '4. close': '93.79000'},
 '2026-04-21': {'1. open': '93.11000',
  '2. high': '93.62500',
  '3. low': '93.11000',
  '4. close': '93.48000'},
 '2026-04-20': {'1. open': '92.58600',
  '2. high': '93.23750',
  '3. low': '92.57900',
  '4. close': '93.11000'},
 '2026-04-17': {'1. open': '93.13000',
  '2. high': '93.13000',
  '3. low': '92.42400',
  '4. close': '92.59800'},
 '2026-04-16': {'1. open': '93.25000',
  '2. high': '93.38700',
  '3. low': '92.90600',
  '4. close': '93.02500'},
 '2026-04-15': {'1. open': '93.10100',
  '2. high': '93.49300',
  '3. low': '93.05800',
  '4. close': '93.35500'},
 '2026-04-14': {'1. open': '93.09800',
  '2. high': '93.40200',
  '3. low': '93.00800',
  '4. close': '93.14500'},
 '2026-04-13': {'1. open': '93.31300',
  '2. high': '93.42600',
  '3. low': '93.10000',
  '4. close': '93.21300'},
 '2026-04-10': {'1. open': '92.65200',
  '2. high': '93.07100',
  '3. low': '92.40400',
  '4. close': '93.07000'},
 '2026-04-09': {'1. open': '92.54000',
  '2. high': '92.91000',
  '3. low': '92.29300',
  '4. close': '92.45000'},
 '2026-04-08': {'1. open': '92.85000',
  '2. high': '92.85000',
  '3. low': '92.32700',
  '4. close': '92.58000'},
 '2026-04-07': {'1. open': '93.00250',
  '2. high': '93.07000',
  '3. low': '92.79800',
  '4. close': '92.84000'},
 '2026-04-06': {'1. open': '92.64500',
  '2. high': '93.18600',
  '3. low': '92.63900',
  '4. close': '93.06000'},
 '2026-04-03': {'1. open': '92.71300',
  '2. high': '92.75100',
  '3. low': '92.58500',
  '4. close': '92.69000'},
 '2026-04-02': {'1. open': '93.22400',
  '2. high': '93.68600',
  '3. low': '92.78900',
  '4. close': '92.95200'},
 '2026-04-01': {'1. open': '93.53900',
  '2. high': '93.88500',
  '3. low': '93.00800',
  '4. close': '93.20600'},
 '2026-03-31': {'1. open': '94.36800',
  '2. high': '94.37500',
  '3. low': '93.41100',
  '4. close': '93.45700'},
 '2026-03-30': {'1. open': '92.95200',
  '2. high': '95.21000',
  '3. low': '92.93200',
  '4. close': '94.35300'},
 '2026-03-27': {'1. open': '94.27700',
  '2. high': '94.98100',
  '3. low': '94.11100',
  '4. close': '94.77700'},
 '2026-03-26': {'1. open': '93.79000',
  '2. high': '94.28100',
  '3. low': '93.79000',
  '4. close': '94.26700'},
 '2026-03-25': {'1. open': '93.98500',
  '2. high': '94.20700',
  '3. low': '93.74300',
  '4. close': '93.88600'},
 '2026-03-24': {'1. open': '93.50000',
  '2. high': '94.12100',
  '3. low': '93.50000',
  '4. close': '94.01300'},
 '2026-03-23': {'1. open': '93.73800',
  '2. high': '94.12900',
  '3. low': '92.90300',
  '4. close': '93.19100'},
 '2026-03-20': {'1. open': '92.89400',
  '2. high': '93.80700',
  '3. low': '92.82900',
  '4. close': '93.67200'},
 '2026-03-19': {'1. open': '92.99900',
  '2. high': '93.37000',
  '3. low': '92.83800',
  '4. close': '92.89100'},
 '2026-03-18': {'1. open': '92.40200',
  '2. high': '93.10100',
  '3. low': '92.32400',
  '4. close': '93.10100'},
 '2026-03-17': {'1. open': '92.23000',
  '2. high': '92.47250',
  '3. low': '92.23000',
  '4. close': '92.37500'},
 '2026-03-16': {'1. open': '92.43000',
  '2. high': '92.47800',
  '3. low': '92.13900',
  '4. close': '92.23400'},
 '2026-03-13': {'1. open': '92.31200',
  '2. high': '92.55100',
  '3. low': '92.23200',
  '4. close': '92.51000'},
 '2026-03-12': {'1. open': '92.23800',
  '2. high': '92.49900',
  '3. low': '92.04000',
  '4. close': '92.36800'},
 '2026-03-11': {'1. open': '91.89400',
  '2. high': '92.23900',
  '3. low': '91.83000',
  '4. close': '92.20200'},
 '2026-03-10': {'1. open': '91.82200',
  '2. high': '92.19900',
  '3. low': '91.66900',
  '4. close': '91.94500'},
 '2026-03-09': {'1. open': '92.30000',
  '2. high': '92.37200',
  '3. low': '92.10100',
  '4. close': '92.13000'},
 '2026-03-06': {'1. open': '91.65200',
  '2. high': '91.99200',
  '3. low': '91.56500',
  '4. close': '91.92800'},
 '2026-03-05': {'1. open': '92.12700',
  '2. high': '92.15900',
  '3. low': '91.32200',
  '4. close': '91.75700'},
 '2026-03-04': {'1. open': '92.00700',
  '2. high': '92.30600',
  '3. low': '91.86300',
  '4. close': '92.09700'},
 '2026-03-03': {'1. open': '91.55000',
  '2. high': '92.22500',
  '3. low': '91.55000',
  '4. close': '92.03000'},
 '2026-03-02': {'1. open': '91.22900',
  '2. high': '91.76700',
  '3. low': '91.16200',
  '4. close': '91.55500'},
 '2026-02-27': {'1. open': '91.01700',
  '2. high': '91.13400',
  '3. low': '90.91000',
  '4. close': '91.04600'},
 '2026-02-26': {'1. open': '90.93600',
  '2. high': '91.06800',
  '3. low': '90.80100',
  '4. close': '90.97300'},
 '2026-02-25': {'1. open': '90.90800',
  '2. high': '90.96300',
  '3. low': '90.85500',
  '4. close': '90.87400'},
 '2026-02-24': {'1. open': '91.02100',
  '2. high': '91.02300',
  '3. low': '90.84700',
  '4. close': '90.89800'},
 '2026-02-23': {'1. open': '90.76000',
  '2. high': '91.01300',
  '3. low': '90.67500',
  '4. close': '91.01100'},
 '2026-02-20': {'1. open': '91.02500',
  '2. high': '91.08300',
  '3. low': '90.70100',
  '4. close': '90.70100'},
 '2026-02-19': {'1. open': '90.76300',
  '2. high': '91.20400',
  '3. low': '90.69000',
  '4. close': '91.01800'},
 '2026-02-18': {'1. open': '90.59700',
  '2. high': '90.78300',
  '3. low': '90.57000',
  '4. close': '90.77500'},
 '2026-02-17': {'1. open': '90.75600',
  '2. high': '90.79500',
  '3. low': '90.58700',
  '4. close': '90.62700'},
 '2026-02-16': {'1. open': '90.50600',
  '2. high': '90.82200',
  '3. low': '90.50000',
  '4. close': '90.75900'},
 '2026-02-13': {'1. open': '90.56100',
  '2. high': '90.75500',
  '3. low': '90.46200',
  '4. close': '90.52500'},
 '2026-02-12': {'1. open': '90.62300',
  '2. high': '90.72700',
  '3. low': '90.38500',
  '4. close': '90.54400'},
 '2026-02-11': {'1. open': '90.58200',
  '2. high': '90.82300',
  '3. low': '90.46000',
  '4. close': '90.73000'},
 '2026-02-10': {'1. open': '90.77200',
  '2. high': '90.78100',
  '3. low': '90.46300',
  '4. close': '90.55800'},
 '2026-02-09': {'1. open': '90.46500',
  '2. high': '90.79100',
  '3. low': '90.36750',
  '4. close': '90.72900'},
 '2026-02-06': {'1. open': '90.31000',
  '2. high': '90.84000',
  '3. low': '90.16800',
  '4. close': '90.57500'},
 '2026-02-05': {'1. open': '90.35700',
  '2. high': '90.51600',
  '3. low': '90.05500',
  '4. close': '90.31400'},
 '2026-02-04': {'1. open': '90.37200',
  '2. high': '90.53000',
  '3. low': '90.22600',
  '4. close': '90.37100'},
 '2026-02-03': {'1. open': '90.34800',
  '2. high': '90.51500',
  '3. low': '90.01400',
  '4. close': '90.39400'},
 '2026-02-02': {'1. open': '91.77300',
  '2. high': '92.01800',
  '3. low': '91.27000',
  '4. close': '91.27000'},
 '2026-01-30': {'1. open': '91.85000',
  '2. high': '92.00800',
  '3. low': '91.64500',
  '4. close': '91.67100'},
 '2026-01-29': {'1. open': '92.00300',
  '2. high': '92.12400',
  '3. low': '91.77000',
  '4. close': '91.77700'},
 '2026-01-28': {'1. open': '91.53000',
  '2. high': '92.21300',
  '3. low': '91.41300',
  '4. close': '92.02300'},
 '2026-01-27': {'1. open': '91.77000',
  '2. high': '91.89100',
  '3. low': '91.45200',
  '4. close': '91.45400'},
 '2026-01-26': {'1. open': '91.52600',
  '2. high': '91.78200',
  '3. low': '91.49300',
  '4. close': '91.68300'},
 '2026-01-23': {'1. open': '91.53500',
  '2. high': '91.98000',
  '3. low': '91.40500',
  '4. close': '91.65500'},
 '2026-01-22': {'1. open': '91.51000',
  '2. high': '91.67500',
  '3. low': '91.25700',
  '4. close': '91.55000'},
 '2026-01-21': {'1. open': '91.05000',
  '2. high': '91.74500',
  '3. low': '90.99300',
  '4. close': '91.52000'},
 '2026-01-20': {'1. open': '90.90000',
  '2. high': '91.09000',
  '3. low': '90.86300',
  '4. close': '91.08900'},
 '2026-01-19': {'1. open': '90.68800',
  '2. high': '91.01000',
  '3. low': '90.60120',
  '4. close': '90.87300'}}

In [59]:
# Step 2: Load dictionary with keys as the row index
df = pd.DataFrame.from_dict(data['Time Series FX (Daily)'], orient='index')

df

             1. open   2. high    3. low  4. close
2026-06-02  95.05000  95.28250  95.02250  95.26000
2026-06-01  94.97000  95.03750  94.72750  94.99000
2026-05-29  95.68000  95.68000  94.95250  95.00000
2026-05-28  95.69000  95.69000  95.68000  95.68000
2026-05-27  95.75000  95.79250  95.65000  95.69000
...              ...       ...       ...       ...
2026-01-20  90.90000  91.09000  90.86300  91.08900
2026-01-19  90.68800  91.01000  90.60120  90.87300
2026-01-16  90.31300  90.88100  90.31300  90.68200
2026-01-15  90.18500  90.43100  90.16900  90.33900
2026-01-14  90.26000  90.38300  89.97250  90.24300

[100 rows x 4 columns]

In [60]:
# Following is OPTIONAL

# Step 3: Clean the column names (remove the numbers and dots)
df.columns = [col.split('. ')[1] for col in df.columns]

# Step 4: Convert all text string numbers to numeric floats
df = df.apply(pd.to_numeric)

# Step 5: Convert index to datetime format and sort chronologically
df.index = pd.to_datetime(df.index)
df.index.name = 'date'
df = df.sort_index()

df

              open     high      low   close
date
2026-01-14  90.260  90.3830  89.9725  90.243
2026-01-15  90.185  90.4310  90.1690  90.339
2026-01-16  90.313  90.8810  90.3130  90.682
2026-01-19  90.688  91.0100  90.6012  90.873
2026-01-20  90.900  91.0900  90.8630  91.089
...            ...      ...      ...     ...
2026-05-27  95.750  95.7925  95.6500  95.690
2026-05-28  95.690  95.6900  95.6800  95.680
2026-05-29  95.680  95.6800  94.9525  95.000
2026-06-01  94.970  95.0375  94.7275  94.990
2026-06-02  95.050  95.2825  95.0225  95.260

[100 rows x 4 columns]

# 6) Cryptocurrency Data

In [34]:
url = (
    f"https://www.alphavantage.co/query?"
    f"function=DIGITAL_CURRENCY_DAILY"
    f"&symbol=BTC"  # Bitcoin BTC, 
    f"&market=USD"
    f"&apikey={ALPHAADVANTAGE_API_KEY}"
)

data = requests.get(url).json()

In [35]:
data

{'Meta Data': {'1. Information': 'Daily Prices and Volumes for Digital Currency',
  '2. Digital Currency Code': 'BTC',
  '3. Digital Currency Name': 'Bitcoin',
  '4. Market Code': 'USD',
  '5. Market Name': 'United States Dollar',
  '6. Last Refreshed': '2026-06-08 00:00:00',
  '7. Time Zone': 'UTC'},
 'Time Series (Digital Currency Daily)': {'2026-06-08': {'1. open': '63302.03000000',
   '2. high': '63513.09000000',
   '3. low': '63114.23000000',
   '4. close': '63502.17000000',
   '5. volume': '321.37628282'},
  '2026-06-07': {'1. open': '60850.48000000',
   '2. high': '64234.45000000',
   '3. low': '60706.40000000',
   '4. close': '63302.73000000',
   '5. volume': '9793.17273270'},
  '2026-06-06': {'1. open': '61031.98000000',
   '2. high': '61499.41000000',
   '3. low': '59448.45000000',
   '4. close': '60850.48000000',
   '5. volume': '9073.41539934'},
  '2026-06-05': {'1. open': '63806.02000000',
   '2. high': '63906.02000000',
   '3. low': '59073.01000000',
   '4. close': '61032.00000000',
   '5. volume': '28732.71500543'},
  '2026-06-04': {'1. open': '64039.99000000',
   '2. high': '64695.00000000',
   '3. low': '61309.25000000',
   '4. close': '63806.02000000',
   '5. volume': '25533.58651100'},
  '2026-06-03': {'1. open': '66658.45000000',
   '2. high': '67416.50000000',
   '3. low': '63985.01000000',
   '4. close': '64040.00000000',
   '5. volume': '15790.02945596'},
  '2026-06-02': {'1. open': '71314.43000000',
   '2. high': '71315.67000000',
   '3. low': '66100.01000000',
   '4. close': '66658.35000000',
   '5. volume': '15741.32305621'},
  '2026-06-01': {'1. open': '73575.18000000',
   '2. high': '73978.52000000',
   '3. low': '70555.00000000',
   '4. close': '71314.42000000',
   '5. volume': '10835.86426218'},
  '2026-05-31': {'1. open': '73770.69000000',
   '2. high': '74156.59000000',
   '3. low': '73288.00000000',
   '4. close': '73575.17000000',
   '5. volume': '3318.87878933'},
  '2026-05-30': {'1. open': '73366.77000000',
   '2. high': '74029.01000000',
   '3. low': '73107.24000000',
   '4. close': '73770.69000000',
   '5. volume': '4015.02525805'},
  '2026-05-29': {'1. open': '73512.55000000',
   '2. high': '74224.84000000',
   '3. low': '72364.13000000',
   '4. close': '73366.77000000',
   '5. volume': '9057.16460696'},
  '2026-05-28': {'1. open': '74316.71000000',
   '2. high': '74462.40000000',
   '3. low': '72445.11000000',
   '4. close': '73512.56000000',
   '5. volume': '8579.08613888'},
  '2026-05-27': {'1. open': '75826.10000000',
   '2. high': '76033.66000000',
   '3. low': '74113.95000000',
   '4. close': '74315.98000000',
   '5. volume': '6385.20290985'},
  '2026-05-26': {'1. open': '77249.07000000',
   '2. high': '78015.46000000',
   '3. low': '75555.00000000',
   '4. close': '75826.10000000',
   '5. volume': '8614.24488170'},
  '2026-05-25': {'1. open': '76975.99000000',
   '2. high': '77834.55000000',
   '3. low': '76807.04000000',
   '4. close': '77249.07000000',
   '5. volume': '3335.38172719'},
  '2026-05-24': {'1. open': '76648.65000000',
   '2. high': '77412.32000000',
   '3. low': '76000.00000000',
   '4. close': '76975.99000000',
   '5. volume': '3695.06880542'},
  '2026-05-23': {'1. open': '75446.99000000',
   '2. high': '77305.00000000',
   '3. low': '74197.11000000',
   '4. close': '76650.00000000',
   '5. volume': '5619.05214390'},
  '2026-05-22': {'1. open': '77547.25000000',
   '2. high': '77833.02000000',
   '3. low': '75266.73000000',
   '4. close': '75443.91000000',
   '5. volume': '5132.27865239'},
  '2026-05-21': {'1. open': '77475.98000000',
   '2. high': '78123.68000000',
   '3. low': '76619.02000000',
   '4. close': '77547.62000000',
   '5. volume': '6038.75037562'},
  '2026-05-20': {'1. open': '76767.48000000',
   '2. high': '77782.61000000',
   '3. low': '76433.52000000',
   '4. close': '77475.99000000',
   '5. volume': '6016.20525065'},
  '2026-05-19': {'1. open': '76943.96000000',
   '2. high': '77350.08000000',
   '3. low': '76061.12000000',
   '4. close': '76767.48000000',
   '5. volume': '4874.41365584'},
  '2026-05-18': {'1. open': '77406.57000000',
   '2. high': '77764.28000000',
   '3. low': '75992.00000000',
   '4. close': '76943.98000000',
   '5. volume': '8825.37701993'},
  '2026-05-17': {'1. open': '78105.46000000',
   '2. high': '78570.00000000',
   '3. low': '76673.54000000',
   '4. close': '77407.59000000',
   '5. volume': '2500.63873433'},
  '2026-05-16': {'1. open': '79058.50000000',
   '2. high': '79182.02000000',
   '3. low': '77608.95000000',
   '4. close': '78105.45000000',
   '5. volume': '3053.43839711'},
  '2026-05-15': {'1. open': '81078.04000000',
   '2. high': '81650.00000000',
   '3. low': '78591.99000000',
   '4. close': '79058.51000000',
   '5. volume': '6789.73368724'},
  '2026-05-14': {'1. open': '79288.26000000',
   '2. high': '82066.22000000',
   '3. low': '78885.42000000',
   '4. close': '81079.39000000',
   '5. volume': '13222.23476392'},
  '2026-05-13': {'1. open': '80484.72000000',
   '2. high': '81293.93000000',
   '3. low': '78699.83000000',
   '4. close': '79288.26000000',
   '5. volume': '7960.11188101'},
  '2026-05-12': {'1. open': '81727.09000000',
   '2. high': '81778.00000000',
   '3. low': '79802.51000000',
   '4. close': '80484.72000000',
   '5. volume': '5247.36830885'},
  '2026-05-11': {'1. open': '82199.99000000',
   '2. high': '82379.00000000',
   '3. low': '80417.72000000',
   '4. close': '81727.06000000',
   '5. volume': '7031.61760564'},
  '2026-05-10': {'1. open': '80655.97000000',
   '2. high': '82450.00000000',
   '3. low': '80273.86000000',
   '4. close': '82199.99000000',
   '5. volume': '3971.08807704'},
  '2026-05-09': {'1. open': '80188.82000000',
   '2. high': '81065.32000000',
   '3. low': '80115.33000000',
   '4. close': '80655.96000000',
   '5. volume': '2056.58900174'},
  '2026-05-08': {'1. open': '80005.38000000',
   '2. high': '80487.39000000',
   '3. low': '79520.44000000',
   '4. close': '80188.82000000',
   '5. volume': '3086.74170459'},
  '2026-05-07': {'1. open': '81438.11000000',
   '2. high': '81709.17000000',
   '3. low': '79456.00000000',
   '4. close': '80005.38000000',
   '5. volume': '7038.15097074'},
  '2026-05-06': {'1. open': '80907.72000000',
   '2. high': '82814.23000000',
   '3. low': '80699.66000000',
   '4. close': '81438.10000000',
   '5. volume': '8276.53099017'},
  '2026-05-05': {'1. open': '79852.37000000',
   '2. high': '81799.60000000',
   '3. low': '79789.50000000',
   '4. close': '80907.72000000',
   '5. volume': '9129.50056534'},
  '2026-05-04': {'1. open': '78558.88000000',
   '2. high': '80750.00000000',
   '3. low': '78205.00000000',
   '4. close': '79852.37000000',
   '5. volume': '11539.41548269'},
  '2026-05-03': {'1. open': '78682.31000000',
   '2. high': '79428.60000000',
   '3. low': '78073.01000000',
   '4. close': '78558.89000000',
   '5. volume': '2766.87588315'},
  '2026-05-02': {'1. open': '78234.05000000',
   '2. high': '79155.00000000',
   '3. low': '78034.28000000',
   '4. close': '78682.31000000',
   '5. volume': '2444.21427844'},
  '2026-05-01': {'1. open': '76305.78000000',
   '2. high': '78961.14000000',
   '3. low': '76275.01000000',
   '4. close': '78234.05000000',
   '5. volume': '8786.48048854'},
  '2026-04-30': {'1. open': '75752.87000000',
   '2. high': '76655.95000000',
   '3. low': '75290.10000000',
   '4. close': '76305.78000000',
   '5. volume': '6282.45727649'},
  '2026-04-29': {'1. open': '76317.99000000',
   '2. high': '77906.84000000',
   '3. low': '74914.00000000',
   '4. close': '75752.88000000',
   '5. volume': '9665.58304734'},
  '2026-04-28': {'1. open': '77364.48000000',
   '2. high': '77478.99000000',
   '3. low': '75646.84000000',
   '4. close': '76317.99000000',
   '5. volume': '6625.83124653'},
  '2026-04-27': {'1. open': '78673.84000000',
   '2. high': '79496.00000000',
   '3. low': '76447.51000000',
   '4. close': '77364.42000000',
   '5. volume': '9288.76247228'},
  '2026-04-26': {'1. open': '77650.72000000',
   '2. high': '78943.00000000',
   '3. low': '77346.44000000',
   '4. close': '78673.83000000',
   '5. volume': '3942.05709744'},
  '2026-04-25': {'1. open': '77461.79000000',
   '2. high': '77911.09000000',
   '3. low': '77179.20000000',
   '4. close': '77650.72000000',
   '5. volume': '2871.67459101'},
  '2026-04-24': {'1. open': '78281.32000000',
   '2. high': '78607.38000000',
   '3. low': '77289.00000000',
   '4. close': '77461.80000000',
   '5. volume': '7766.77212029'},
  '2026-04-23': {'1. open': '78208.52000000',
   '2. high': '78722.96000000',
   '3. low': '76979.99000000',
   '4. close': '78281.32000000',
   '5. volume': '9366.75503457'},
  '2026-04-22': {'1. open': '76355.73000000',
   '2. high': '79523.00000000',
   '3. low': '76145.00000000',
   '4. close': '78208.52000000',
   '5. volume': '11757.91950096'},
  '2026-04-21': {'1. open': '75864.86000000',
   '2. high': '76926.37000000',
   '3. low': '74817.27000000',
   '4. close': '76348.58000000',
   '5. volume': '7556.91793671'},
  '2026-04-20': {'1. open': '73823.27000000',
   '2. high': '76600.00000000',
   '3. low': '73741.53000000',
   '4. close': '75864.86000000',
   '5. volume': '8979.33512634'},
  '2026-04-19': {'1. open': '75736.00000000',
   '2. high': '76278.36000000',
   '3. low': '73777.86000000',
   '4. close': '73823.14000000',
   '5. volume': '5477.34091341'},
  '2026-04-18': {'1. open': '77098.01000000',
   '2. high': '77450.15000000',
   '3. low': '75473.81000000',
   '4. close': '75736.82000000',
   '5. volume': '4245.34274580'},
  '2026-04-17': {'1. open': '75163.09000000',
   '2. high': '78390.00000000',
   '3. low': '74558.21000000',
   '4. close': '77098.01000000',
   '5. volume': '15414.90050977'},
  '2026-04-16': {'1. open': '74839.97000000',
   '2. high': '75539.91000000',
   '3. low': '73298.01000000',
   '4. close': '75163.09000000',
   '5. volume': '8138.95301491'},
  '2026-04-15': {'1. open': '74176.09000000',
   '2. high': '75458.81000000',
   '3. low': '73545.00000000',
   '4. close': '74836.31000000',
   '5. volume': '7732.11670824'},
  '2026-04-14': {'1. open': '74448.00000000',
   '2. high': '76127.18000000',
   '3. low': '73854.50000000',
   '4. close': '74179.04000000',
   '5. volume': '21086.20700901'},
  '2026-04-13': {'1. open': '70755.35000000',
   '2. high': '74936.90000000',
   '3. low': '70576.27000000',
   '4. close': '74446.00000000',
   '5. volume': '17452.66428951'},
  '2026-04-12': {'1. open': '73085.99000000',
   '2. high': '73172.14000000',
   '3. low': '70512.70000000',
   '4. close': '70755.35000000',
   '5. volume': '4443.04188961'},
  '2026-04-11': {'1. open': '72997.88000000',
   '2. high': '73822.95000000',
   '3. low': '72564.35000000',
   '4. close': '73086.00000000',
   '5. volume': '2795.93594516'},
  '2026-04-10': {'1. open': '71798.01000000',
   '2. high': '73477.87000000',
   '3. low': '71431.55000000',
   '4. close': '72997.88000000',
   '5. volume': '10066.64303661'},
  '2026-04-09': {'1. open': '71083.99000000',
   '2. high': '73147.81000000',
   '3. low': '70468.74000000',
   '4. close': '71798.01000000',
   '5. volume': '10707.78813462'},
  '2026-04-08': {'1. open': '71910.21000000',
   '2. high': '72861.38000000',
   '3. low': '70684.65000000',
   '4. close': '71085.99000000',
   '5. volume': '11083.24086941'},
  '2026-04-07': {'1. open': '68853.60000000',
   '2. high': '72753.97000000',
   '3. low': '67710.01000000',
   '4. close': '71910.20000000',
   '5. volume': '11156.72732306'},
  '2026-04-06': {'1. open': '69005.00000000',
   '2. high': '70378.48000000',
   '3. low': '68332.00000000',
   '4. close': '68853.61000000',
   '5. volume': '11182.35365631'},
  '2026-04-05': {'1. open': '67291.72000000',
   '2. high': '69117.60000000',
   '3. low': '66600.00000000',
   '4. close': '69005.00000000',
   '5. volume': '3810.37749315'},
  '2026-04-04': {'1. open': '66959.98000000',
   '2. high': '67535.20000000',
   '3. low': '66770.64000000',
   '4. close': '67291.73000000',
   '5. volume': '2412.86305009'},
  '2026-04-03': {'1. open': '66899.11000000',
   '2. high': '67375.70000000',
   '3. low': '66275.01000000',
   '4. close': '66959.99000000',
   '5. volume': '4181.03967015'},
  '2026-04-02': {'1. open': '68112.34000000',
   '2. high': '68652.00000000',
   '3. low': '65696.96000000',
   '4. close': '66894.48000000',
   '5. volume': '8813.97029196'},
  '2026-04-01': {'1. open': '68221.84000000',
   '2. high': '69285.99000000',
   '3. low': '67525.59000000',
   '4. close': '68112.35000000',
   '5. volume': '9804.65444480'},
  '2026-03-31': {'1. open': '66737.08000000',
   '2. high': '68518.10000000',
   '3. low': '65924.82000000',
   '4. close': '68221.85000000',
   '5. volume': '11831.58350430'},
  '2026-03-30': {'1. open': '65957.95000000',
   '2. high': '68129.33000000',
   '3. low': '65736.63000000',
   '4. close': '66737.18000000',
   '5. volume': '10707.53083699'},
  '2026-03-29': {'1. open': '66320.16000000',
   '2. high': '67076.07000000',
   '3. low': '64938.66000000',
   '4. close': '65956.94000000',
   '5. volume': '4588.31530898'},
  '2026-03-28': {'1. open': '66353.33000000',
   '2. high': '67249.65000000',
   '3. low': '65876.61000000',
   '4. close': '66320.15000000',
   '5. volume': '4011.39625322'},
  '2026-03-27': {'1. open': '68769.02000000',
   '2. high': '69128.75000000',
   '3. low': '65498.75000000',
   '4. close': '66353.34000000',
   '5. volume': '13681.42559929'},
  '2026-03-26': {'1. open': '71301.52000000',
   '2. high': '71414.33000000',
   '3. low': '68102.36000000',
   '4. close': '68769.02000000',
   '5. volume': '8225.19395173'},
  '2026-03-25': {'1. open': '70533.48000000',
   '2. high': '72030.29000000',
   '3. low': '70357.10000000',
   '4. close': '71301.53000000',
   '5. volume': '7665.36824144'},
  '2026-03-24': {'1. open': '70874.22000000',
   '2. high': '71389.00000000',
   '3. low': '68889.00000000',
   '4. close': '70533.49000000',
   '5. volume': '7238.74499869'},
  '2026-03-23': {'1. open': '67844.94000000',
   '2. high': '71811.00000000',
   '3. low': '67425.00000000',
   '4. close': '70874.23000000',
   '5. volume': '10354.71705596'},
  '2026-03-22': {'1. open': '68912.02000000',
   '2. high': '69577.00000000',
   '3. low': '67332.05000000',
   '4. close': '67844.94000000',
   '5. volume': '4889.89870785'},
  '2026-03-21': {'1. open': '70497.01000000',
   '2. high': '71075.92000000',
   '3. low': '68562.13000000',
   '4. close': '68912.02000000',
   '5. volume': '2856.70812643'},
  '2026-03-20': {'1. open': '69917.19000000',
   '2. high': '71384.62000000',
   '3. low': '69360.00000000',
   '4. close': '70497.01000000',
   '5. volume': '7315.89355875'},
  '2026-03-19': {'1. open': '71245.01000000',
   '2. high': '71628.00000000',
   '3. low': '68772.78000000',
   '4. close': '69918.30000000',
   '5. volume': '7794.02546506'},
  '2026-03-18': {'1. open': '73934.11000000',
   '2. high': '74700.00000000',
   '3. low': '70474.83000000',
   '4. close': '71245.02000000',
   '5. volume': '9248.11451050'},
  '2026-03-17': {'1. open': '74886.46000000',
   '2. high': '76022.60000000',
   '3. low': '73400.01000000',
   '4. close': '73934.11000000',
   '5. volume': '11357.85437394'},
  '2026-03-16': {'1. open': '72830.01000000',
   '2. high': '74913.69000000',
   '3. low': '72276.24000000',
   '4. close': '74886.47000000',
   '5. volume': '12657.43153702'},
  '2026-03-15': {'1. open': '71232.01000000',
   '2. high': '73220.80000000',
   '3. low': '70868.41000000',
   '4. close': '72830.01000000',
   '5. volume': '5785.61944649'},
  '2026-03-14': {'1. open': '70944.32000000',
   '2. high': '71316.00000000',
   '3. low': '70236.02000000',
   '4. close': '71232.02000000',
   '5. volume': '3174.08339322'},
  '2026-03-13': {'1. open': '70530.02000000',
   '2. high': '73968.00000000',
   '3. low': '70398.01000000',
   '4. close': '70944.33000000',
   '5. volume': '12304.21633821'},
  '2026-03-12': {'1. open': '70208.03000000',
   '2. high': '70819.84000000',
   '3. low': '69180.01000000',
   '4. close': '70531.56000000',
   '5. volume': '9708.42046678'},
  '2026-03-11': {'1. open': '69960.83000000',
   '2. high': '71358.48000000',
   '3. low': '68980.74000000',
   '4. close': '70208.00000000',
   '5. volume': '9851.72870494'},
  '2026-03-10': {'1. open': '68432.16000000',
   '2. high': '71800.00000000',
   '3. low': '68383.50000000',
   '4. close': '69960.83000000',
   '5. volume': '13322.43399947'},
  '2026-03-09': {'1. open': '65970.56000000',
   '2. high': '69543.00000000',
   '3. low': '65820.93000000',
   '4. close': '68432.17000000',
   '5. volume': '13303.95615379'},
  '2026-03-08': {'1. open': '67259.62000000',
   '2. high': '68201.16000000',
   '3. low': '65618.51000000',
   '4. close': '65970.56000000',
   '5. volume': '5505.17926548'},
  '2026-03-07': {'1. open': '68108.23000000',
   '2. high': '68544.79000000',
   '3. low': '66921.33000000',
   '4. close': '67259.62000000',
   '5. volume': '3245.05107908'},
  '2026-03-06': {'1. open': '70887.61000000',
   '2. high': '71428.40000000',
   '3. low': '67725.14000000',
   '4. close': '68108.24000000',
   '5. volume': '11045.21439575'},
  '2026-03-05': {'1. open': '72683.26000000',
   '2. high': '73588.24000000',
   '3. low': '70639.01000000',
   '4. close': '70887.60000000',
   '5. volume': '10891.71826063'},
  '2026-03-04': {'1. open': '68335.99000000',
   '2. high': '74100.00000000',
   '3. low': '67391.17000000',
   '4. close': '72683.26000000',
   '5. volume': '21142.77079177'},
  '2026-03-03': {'1. open': '68832.00000000',
   '2. high': '69255.36000000',
   '3. low': '66138.20000000',
   '4. close': '68335.99000000',
   '5. volume': '12823.72759460'},
  '2026-03-02': {'1. open': '65771.56000000',
   '2. high': '70128.74000000',
   '3. low': '65250.12000000',
   '4. close': '68832.01000000',
   '5. volume': '17772.46881037'},
  '2026-03-01': {'1. open': '66971.54000000',
   '2. high': '68200.00000000',
   '3. low': '65008.38000000',
   '4. close': '65769.00000000',
   '5. volume': '8511.88788603'},
  '2026-02-28': {'1. open': '65859.93000000',
   '2. high': '67761.55000000',
   '3. low': '63019.60000000',
   '4. close': '66967.85000000',
   '5. volume': '9093.24916408'},
  '2026-02-27': {'1. open': '67490.50000000',
   '2. high': '68223.07000000',
   '3. low': '64942.87000000',
   '4. close': '65859.94000000',
   '5. volume': '10276.79604611'},
  '2026-02-26': {'1. open': '67992.68000000',
   '2. high': '68866.86000000',
   '3. low': '66500.92000000',
   '4. close': '67490.51000000',
   '5. volume': '10678.27331982'},
  '2026-02-25': {'1. open': '64068.33000000',
   '2. high': '70020.00000000',
   '3. low': '63912.25000000',
   '4. close': '67992.68000000',
   '5. volume': '17322.54859823'},
  '2026-02-24': {'1. open': '64625.78000000',
   '2. high': '64988.32000000',
   '3. low': '62534.61000000',
   '4. close': '64068.33000000',
   '5. volume': '12517.40763597'},
  '2026-02-23': {'1. open': '67616.01000000',
   '2. high': '67656.42000000',
   '3. low': '63855.00000000',
   '4. close': '64625.78000000',
   '5. volume': '15198.01176266'},
  '2026-02-22': {'1. open': '67955.78000000',
   '2. high': '68241.40000000',
   '3. low': '67132.81000000',
   '4. close': '67617.98000000',
   '5. volume': '3263.53347230'},
  '2026-02-21': {'1. open': '67984.42000000',
   '2. high': '68683.27000000',
   '3. low': '67516.93000000',
   '4. close': '67955.78000000',
   '5. volume': '3287.06467470'},
  '2026-02-20': {'1. open': '66972.49000000',
   '2. high': '68294.86000000',
   '3. low': '66427.23000000',
   '4. close': '67984.42000000',
   '5. volume': '11349.70677085'},
  '2026-02-19': {'1. open': '66419.78000000',
   '2. high': '67288.22000000',
   '3. low': '65604.63000000',
   '4. close': '66972.50000000',
   '5. volume': '8505.29632895'},
  '2026-02-18': {'1. open': '67466.70000000',
   '2. high': '68438.84000000',
   '3. low': '65812.57000000',
   '4. close': '66419.79000000',
   '5. volume': '9687.16921753'},
  '2026-02-17': {'1. open': '68859.55000000',
   '2. high': '69199.51000000',

In [36]:
data.keys()

dict_keys(['Meta Data', 'Time Series (Digital Currency Daily)'])

In [37]:
data['Meta Data']

{'1. Information': 'Daily Prices and Volumes for Digital Currency',
 '2. Digital Currency Code': 'BTC',
 '3. Digital Currency Name': 'Bitcoin',
 '4. Market Code': 'USD',
 '5. Market Name': 'United States Dollar',
 '6. Last Refreshed': '2026-06-08 00:00:00',
 '7. Time Zone': 'UTC'}

In [38]:
data['Time Series (Digital Currency Daily)']

{'2026-06-08': {'1. open': '63302.03000000',
  '2. high': '63513.09000000',
  '3. low': '63114.23000000',
  '4. close': '63502.17000000',
  '5. volume': '321.37628282'},
 '2026-06-07': {'1. open': '60850.48000000',
  '2. high': '64234.45000000',
  '3. low': '60706.40000000',
  '4. close': '63302.73000000',
  '5. volume': '9793.17273270'},
 '2026-06-06': {'1. open': '61031.98000000',
  '2. high': '61499.41000000',
  '3. low': '59448.45000000',
  '4. close': '60850.48000000',
  '5. volume': '9073.41539934'},
 '2026-06-05': {'1. open': '63806.02000000',
  '2. high': '63906.02000000',
  '3. low': '59073.01000000',
  '4. close': '61032.00000000',
  '5. volume': '28732.71500543'},
 '2026-06-04': {'1. open': '64039.99000000',
  '2. high': '64695.00000000',
  '3. low': '61309.25000000',
  '4. close': '63806.02000000',
  '5. volume': '25533.58651100'},
 '2026-06-03': {'1. open': '66658.45000000',
  '2. high': '67416.50000000',
  '3. low': '63985.01000000',
  '4. close': '64040.00000000',
  '5. volume': '15790.02945596'},
 '2026-06-02': {'1. open': '71314.43000000',
  '2. high': '71315.67000000',
  '3. low': '66100.01000000',
  '4. close': '66658.35000000',
  '5. volume': '15741.32305621'},
 '2026-06-01': {'1. open': '73575.18000000',
  '2. high': '73978.52000000',
  '3. low': '70555.00000000',
  '4. close': '71314.42000000',
  '5. volume': '10835.86426218'},
 '2026-05-31': {'1. open': '73770.69000000',
  '2. high': '74156.59000000',
  '3. low': '73288.00000000',
  '4. close': '73575.17000000',
  '5. volume': '3318.87878933'},
 '2026-05-30': {'1. open': '73366.77000000',
  '2. high': '74029.01000000',
  '3. low': '73107.24000000',
  '4. close': '73770.69000000',
  '5. volume': '4015.02525805'},
 '2026-05-29': {'1. open': '73512.55000000',
  '2. high': '74224.84000000',
  '3. low': '72364.13000000',
  '4. close': '73366.77000000',
  '5. volume': '9057.16460696'},
 '2026-05-28': {'1. open': '74316.71000000',
  '2. high': '74462.40000000',
  '3. low': '72445.11000000',
  '4. close': '73512.56000000',
  '5. volume': '8579.08613888'},
 '2026-05-27': {'1. open': '75826.10000000',
  '2. high': '76033.66000000',
  '3. low': '74113.95000000',
  '4. close': '74315.98000000',
  '5. volume': '6385.20290985'},
 '2026-05-26': {'1. open': '77249.07000000',
  '2. high': '78015.46000000',
  '3. low': '75555.00000000',
  '4. close': '75826.10000000',
  '5. volume': '8614.24488170'},
 '2026-05-25': {'1. open': '76975.99000000',
  '2. high': '77834.55000000',
  '3. low': '76807.04000000',
  '4. close': '77249.07000000',
  '5. volume': '3335.38172719'},
 '2026-05-24': {'1. open': '76648.65000000',
  '2. high': '77412.32000000',
  '3. low': '76000.00000000',
  '4. close': '76975.99000000',
  '5. volume': '3695.06880542'},
 '2026-05-23': {'1. open': '75446.99000000',
  '2. high': '77305.00000000',
  '3. low': '74197.11000000',
  '4. close': '76650.00000000',
  '5. volume': '5619.05214390'},
 '2026-05-22': {'1. open': '77547.25000000',
  '2. high': '77833.02000000',
  '3. low': '75266.73000000',
  '4. close': '75443.91000000',
  '5. volume': '5132.27865239'},
 '2026-05-21': {'1. open': '77475.98000000',
  '2. high': '78123.68000000',
  '3. low': '76619.02000000',
  '4. close': '77547.62000000',
  '5. volume': '6038.75037562'},
 '2026-05-20': {'1. open': '76767.48000000',
  '2. high': '77782.61000000',
  '3. low': '76433.52000000',
  '4. close': '77475.99000000',
  '5. volume': '6016.20525065'},
 '2026-05-19': {'1. open': '76943.96000000',
  '2. high': '77350.08000000',
  '3. low': '76061.12000000',
  '4. close': '76767.48000000',
  '5. volume': '4874.41365584'},
 '2026-05-18': {'1. open': '77406.57000000',
  '2. high': '77764.28000000',
  '3. low': '75992.00000000',
  '4. close': '76943.98000000',
  '5. volume': '8825.37701993'},
 '2026-05-17': {'1. open': '78105.46000000',
  '2. high': '78570.00000000',
  '3. low': '76673.54000000',
  '4. close': '77407.59000000',
  '5. volume': '2500.63873433'},
 '2026-05-16': {'1. open': '79058.50000000',
  '2. high': '79182.02000000',
  '3. low': '77608.95000000',
  '4. close': '78105.45000000',
  '5. volume': '3053.43839711'},
 '2026-05-15': {'1. open': '81078.04000000',
  '2. high': '81650.00000000',
  '3. low': '78591.99000000',
  '4. close': '79058.51000000',
  '5. volume': '6789.73368724'},
 '2026-05-14': {'1. open': '79288.26000000',
  '2. high': '82066.22000000',
  '3. low': '78885.42000000',
  '4. close': '81079.39000000',
  '5. volume': '13222.23476392'},
 '2026-05-13': {'1. open': '80484.72000000',
  '2. high': '81293.93000000',
  '3. low': '78699.83000000',
  '4. close': '79288.26000000',
  '5. volume': '7960.11188101'},
 '2026-05-12': {'1. open': '81727.09000000',
  '2. high': '81778.00000000',
  '3. low': '79802.51000000',
  '4. close': '80484.72000000',
  '5. volume': '5247.36830885'},
 '2026-05-11': {'1. open': '82199.99000000',
  '2. high': '82379.00000000',
  '3. low': '80417.72000000',
  '4. close': '81727.06000000',
  '5. volume': '7031.61760564'},
 '2026-05-10': {'1. open': '80655.97000000',
  '2. high': '82450.00000000',
  '3. low': '80273.86000000',
  '4. close': '82199.99000000',
  '5. volume': '3971.08807704'},
 '2026-05-09': {'1. open': '80188.82000000',
  '2. high': '81065.32000000',
  '3. low': '80115.33000000',
  '4. close': '80655.96000000',
  '5. volume': '2056.58900174'},
 '2026-05-08': {'1. open': '80005.38000000',
  '2. high': '80487.39000000',
  '3. low': '79520.44000000',
  '4. close': '80188.82000000',
  '5. volume': '3086.74170459'},
 '2026-05-07': {'1. open': '81438.11000000',
  '2. high': '81709.17000000',
  '3. low': '79456.00000000',
  '4. close': '80005.38000000',
  '5. volume': '7038.15097074'},
 '2026-05-06': {'1. open': '80907.72000000',
  '2. high': '82814.23000000',
  '3. low': '80699.66000000',
  '4. close': '81438.10000000',
  '5. volume': '8276.53099017'},
 '2026-05-05': {'1. open': '79852.37000000',
  '2. high': '81799.60000000',
  '3. low': '79789.50000000',
  '4. close': '80907.72000000',
  '5. volume': '9129.50056534'},
 '2026-05-04': {'1. open': '78558.88000000',
  '2. high': '80750.00000000',
  '3. low': '78205.00000000',
  '4. close': '79852.37000000',
  '5. volume': '11539.41548269'},
 '2026-05-03': {'1. open': '78682.31000000',
  '2. high': '79428.60000000',
  '3. low': '78073.01000000',
  '4. close': '78558.89000000',
  '5. volume': '2766.87588315'},
 '2026-05-02': {'1. open': '78234.05000000',
  '2. high': '79155.00000000',
  '3. low': '78034.28000000',
  '4. close': '78682.31000000',
  '5. volume': '2444.21427844'},
 '2026-05-01': {'1. open': '76305.78000000',
  '2. high': '78961.14000000',
  '3. low': '76275.01000000',
  '4. close': '78234.05000000',
  '5. volume': '8786.48048854'},
 '2026-04-30': {'1. open': '75752.87000000',
  '2. high': '76655.95000000',
  '3. low': '75290.10000000',
  '4. close': '76305.78000000',
  '5. volume': '6282.45727649'},
 '2026-04-29': {'1. open': '76317.99000000',
  '2. high': '77906.84000000',
  '3. low': '74914.00000000',
  '4. close': '75752.88000000',
  '5. volume': '9665.58304734'},
 '2026-04-28': {'1. open': '77364.48000000',
  '2. high': '77478.99000000',
  '3. low': '75646.84000000',
  '4. close': '76317.99000000',
  '5. volume': '6625.83124653'},
 '2026-04-27': {'1. open': '78673.84000000',
  '2. high': '79496.00000000',
  '3. low': '76447.51000000',
  '4. close': '77364.42000000',
  '5. volume': '9288.76247228'},
 '2026-04-26': {'1. open': '77650.72000000',
  '2. high': '78943.00000000',
  '3. low': '77346.44000000',
  '4. close': '78673.83000000',
  '5. volume': '3942.05709744'},
 '2026-04-25': {'1. open': '77461.79000000',
  '2. high': '77911.09000000',
  '3. low': '77179.20000000',
  '4. close': '77650.72000000',
  '5. volume': '2871.67459101'},
 '2026-04-24': {'1. open': '78281.32000000',
  '2. high': '78607.38000000',
  '3. low': '77289.00000000',
  '4. close': '77461.80000000',
  '5. volume': '7766.77212029'},
 '2026-04-23': {'1. open': '78208.52000000',
  '2. high': '78722.96000000',
  '3. low': '76979.99000000',
  '4. close': '78281.32000000',
  '5. volume': '9366.75503457'},
 '2026-04-22': {'1. open': '76355.73000000',
  '2. high': '79523.00000000',
  '3. low': '76145.00000000',
  '4. close': '78208.52000000',
  '5. volume': '11757.91950096'},
 '2026-04-21': {'1. open': '75864.86000000',
  '2. high': '76926.37000000',
  '3. low': '74817.27000000',
  '4. close': '76348.58000000',
  '5. volume': '7556.91793671'},
 '2026-04-20': {'1. open': '73823.27000000',
  '2. high': '76600.00000000',
  '3. low': '73741.53000000',
  '4. close': '75864.86000000',
  '5. volume': '8979.33512634'},
 '2026-04-19': {'1. open': '75736.00000000',
  '2. high': '76278.36000000',
  '3. low': '73777.86000000',
  '4. close': '73823.14000000',
  '5. volume': '5477.34091341'},
 '2026-04-18': {'1. open': '77098.01000000',
  '2. high': '77450.15000000',
  '3. low': '75473.81000000',
  '4. close': '75736.82000000',
  '5. volume': '4245.34274580'},
 '2026-04-17': {'1. open': '75163.09000000',
  '2. high': '78390.00000000',
  '3. low': '74558.21000000',
  '4. close': '77098.01000000',
  '5. volume': '15414.90050977'},
 '2026-04-16': {'1. open': '74839.97000000',
  '2. high': '75539.91000000',
  '3. low': '73298.01000000',
  '4. close': '75163.09000000',
  '5. volume': '8138.95301491'},
 '2026-04-15': {'1. open': '74176.09000000',
  '2. high': '75458.81000000',
  '3. low': '73545.00000000',
  '4. close': '74836.31000000',
  '5. volume': '7732.11670824'},
 '2026-04-14': {'1. open': '74448.00000000',
  '2. high': '76127.18000000',
  '3. low': '73854.50000000',
  '4. close': '74179.04000000',
  '5. volume': '21086.20700901'},
 '2026-04-13': {'1. open': '70755.35000000',
  '2. high': '74936.90000000',
  '3. low': '70576.27000000',
  '4. close': '74446.00000000',
  '5. volume': '17452.66428951'},
 '2026-04-12': {'1. open': '73085.99000000',
  '2. high': '73172.14000000',
  '3. low': '70512.70000000',
  '4. close': '70755.35000000',
  '5. volume': '4443.04188961'},
 '2026-04-11': {'1. open': '72997.88000000',
  '2. high': '73822.95000000',
  '3. low': '72564.35000000',
  '4. close': '73086.00000000',
  '5. volume': '2795.93594516'},
 '2026-04-10': {'1. open': '71798.01000000',
  '2. high': '73477.87000000',
  '3. low': '71431.55000000',
  '4. close': '72997.88000000',
  '5. volume': '10066.64303661'},
 '2026-04-09': {'1. open': '71083.99000000',
  '2. high': '73147.81000000',
  '3. low': '70468.74000000',
  '4. close': '71798.01000000',
  '5. volume': '10707.78813462'},
 '2026-04-08': {'1. open': '71910.21000000',
  '2. high': '72861.38000000',
  '3. low': '70684.65000000',
  '4. close': '71085.99000000',
  '5. volume': '11083.24086941'},
 '2026-04-07': {'1. open': '68853.60000000',
  '2. high': '72753.97000000',
  '3. low': '67710.01000000',
  '4. close': '71910.20000000',
  '5. volume': '11156.72732306'},
 '2026-04-06': {'1. open': '69005.00000000',
  '2. high': '70378.48000000',
  '3. low': '68332.00000000',
  '4. close': '68853.61000000',
  '5. volume': '11182.35365631'},
 '2026-04-05': {'1. open': '67291.72000000',
  '2. high': '69117.60000000',
  '3. low': '66600.00000000',
  '4. close': '69005.00000000',
  '5. volume': '3810.37749315'},
 '2026-04-04': {'1. open': '66959.98000000',
  '2. high': '67535.20000000',
  '3. low': '66770.64000000',
  '4. close': '67291.73000000',
  '5. volume': '2412.86305009'},
 '2026-04-03': {'1. open': '66899.11000000',
  '2. high': '67375.70000000',
  '3. low': '66275.01000000',
  '4. close': '66959.99000000',
  '5. volume': '4181.03967015'},
 '2026-04-02': {'1. open': '68112.34000000',
  '2. high': '68652.00000000',
  '3. low': '65696.96000000',
  '4. close': '66894.48000000',
  '5. volume': '8813.97029196'},
 '2026-04-01': {'1. open': '68221.84000000',
  '2. high': '69285.99000000',
  '3. low': '67525.59000000',
  '4. close': '68112.35000000',
  '5. volume': '9804.65444480'},
 '2026-03-31': {'1. open': '66737.08000000',
  '2. high': '68518.10000000',
  '3. low': '65924.82000000',
  '4. close': '68221.85000000',
  '5. volume': '11831.58350430'},
 '2026-03-30': {'1. open': '65957.95000000',
  '2. high': '68129.33000000',
  '3. low': '65736.63000000',
  '4. close': '66737.18000000',
  '5. volume': '10707.53083699'},
 '2026-03-29': {'1. open': '66320.16000000',
  '2. high': '67076.07000000',
  '3. low': '64938.66000000',
  '4. close': '65956.94000000',
  '5. volume': '4588.31530898'},
 '2026-03-28': {'1. open': '66353.33000000',
  '2. high': '67249.65000000',
  '3. low': '65876.61000000',
  '4. close': '66320.15000000',
  '5. volume': '4011.39625322'},
 '2026-03-27': {'1. open': '68769.02000000',
  '2. high': '69128.75000000',
  '3. low': '65498.75000000',
  '4. close': '66353.34000000',
  '5. volume': '13681.42559929'},
 '2026-03-26': {'1. open': '71301.52000000',
  '2. high': '71414.33000000',
  '3. low': '68102.36000000',
  '4. close': '68769.02000000',
  '5. volume': '8225.19395173'},
 '2026-03-25': {'1. open': '70533.48000000',
  '2. high': '72030.29000000',
  '3. low': '70357.10000000',
  '4. close': '71301.53000000',
  '5. volume': '7665.36824144'},
 '2026-03-24': {'1. open': '70874.22000000',
  '2. high': '71389.00000000',
  '3. low': '68889.00000000',
  '4. close': '70533.49000000',
  '5. volume': '7238.74499869'},
 '2026-03-23': {'1. open': '67844.94000000',
  '2. high': '71811.00000000',
  '3. low': '67425.00000000',
  '4. close': '70874.23000000',
  '5. volume': '10354.71705596'},
 '2026-03-22': {'1. open': '68912.02000000',
  '2. high': '69577.00000000',
  '3. low': '67332.05000000',
  '4. close': '67844.94000000',
  '5. volume': '4889.89870785'},
 '2026-03-21': {'1. open': '70497.01000000',
  '2. high': '71075.92000000',
  '3. low': '68562.13000000',
  '4. close': '68912.02000000',
  '5. volume': '2856.70812643'},
 '2026-03-20': {'1. open': '69917.19000000',
  '2. high': '71384.62000000',
  '3. low': '69360.00000000',
  '4. close': '70497.01000000',
  '5. volume': '7315.89355875'},
 '2026-03-19': {'1. open': '71245.01000000',
  '2. high': '71628.00000000',
  '3. low': '68772.78000000',
  '4. close': '69918.30000000',
  '5. volume': '7794.02546506'},
 '2026-03-18': {'1. open': '73934.11000000',
  '2. high': '74700.00000000',
  '3. low': '70474.83000000',
  '4. close': '71245.02000000',
  '5. volume': '9248.11451050'},
 '2026-03-17': {'1. open': '74886.46000000',
  '2. high': '76022.60000000',
  '3. low': '73400.01000000',
  '4. close': '73934.11000000',
  '5. volume': '11357.85437394'},
 '2026-03-16': {'1. open': '72830.01000000',
  '2. high': '74913.69000000',
  '3. low': '72276.24000000',
  '4. close': '74886.47000000',
  '5. volume': '12657.43153702'},
 '2026-03-15': {'1. open': '71232.01000000',
  '2. high': '73220.80000000',
  '3. low': '70868.41000000',
  '4. close': '72830.01000000',
  '5. volume': '5785.61944649'},
 '2026-03-14': {'1. open': '70944.32000000',
  '2. high': '71316.00000000',
  '3. low': '70236.02000000',
  '4. close': '71232.02000000',
  '5. volume': '3174.08339322'},
 '2026-03-13': {'1. open': '70530.02000000',
  '2. high': '73968.00000000',
  '3. low': '70398.01000000',
  '4. close': '70944.33000000',
  '5. volume': '12304.21633821'},
 '2026-03-12': {'1. open': '70208.03000000',
  '2. high': '70819.84000000',
  '3. low': '69180.01000000',
  '4. close': '70531.56000000',
  '5. volume': '9708.42046678'},
 '2026-03-11': {'1. open': '69960.83000000',
  '2. high': '71358.48000000',
  '3. low': '68980.74000000',
  '4. close': '70208.00000000',
  '5. volume': '9851.72870494'},
 '2026-03-10': {'1. open': '68432.16000000',
  '2. high': '71800.00000000',
  '3. low': '68383.50000000',
  '4. close': '69960.83000000',
  '5. volume': '13322.43399947'},
 '2026-03-09': {'1. open': '65970.56000000',
  '2. high': '69543.00000000',
  '3. low': '65820.93000000',
  '4. close': '68432.17000000',
  '5. volume': '13303.95615379'},
 '2026-03-08': {'1. open': '67259.62000000',
  '2. high': '68201.16000000',
  '3. low': '65618.51000000',
  '4. close': '65970.56000000',
  '5. volume': '5505.17926548'},
 '2026-03-07': {'1. open': '68108.23000000',
  '2. high': '68544.79000000',
  '3. low': '66921.33000000',
  '4. close': '67259.62000000',
  '5. volume': '3245.05107908'},
 '2026-03-06': {'1. open': '70887.61000000',
  '2. high': '71428.40000000',
  '3. low': '67725.14000000',
  '4. close': '68108.24000000',
  '5. volume': '11045.21439575'},
 '2026-03-05': {'1. open': '72683.26000000',
  '2. high': '73588.24000000',
  '3. low': '70639.01000000',
  '4. close': '70887.60000000',
  '5. volume': '10891.71826063'},
 '2026-03-04': {'1. open': '68335.99000000',
  '2. high': '74100.00000000',
  '3. low': '67391.17000000',
  '4. close': '72683.26000000',
  '5. volume': '21142.77079177'},
 '2026-03-03': {'1. open': '68832.00000000',
  '2. high': '69255.36000000',
  '3. low': '66138.20000000',
  '4. close': '68335.99000000',
  '5. volume': '12823.72759460'},
 '2026-03-02': {'1. open': '65771.56000000',
  '2. high': '70128.74000000',
  '3. low': '65250.12000000',
  '4. close': '68832.01000000',
  '5. volume': '17772.46881037'},
 '2026-03-01': {'1. open': '66971.54000000',
  '2. high': '68200.00000000',
  '3. low': '65008.38000000',
  '4. close': '65769.00000000',
  '5. volume': '8511.88788603'},
 '2026-02-28': {'1. open': '65859.93000000',
  '2. high': '67761.55000000',
  '3. low': '63019.60000000',
  '4. close': '66967.85000000',
  '5. volume': '9093.24916408'},
 '2026-02-27': {'1. open': '67490.50000000',
  '2. high': '68223.07000000',
  '3. low': '64942.87000000',
  '4. close': '65859.94000000',
  '5. volume': '10276.79604611'},
 '2026-02-26': {'1. open': '67992.68000000',
  '2. high': '68866.86000000',
  '3. low': '66500.92000000',
  '4. close': '67490.51000000',
  '5. volume': '10678.27331982'},
 '2026-02-25': {'1. open': '64068.33000000',
  '2. high': '70020.00000000',
  '3. low': '63912.25000000',
  '4. close': '67992.68000000',
  '5. volume': '17322.54859823'},
 '2026-02-24': {'1. open': '64625.78000000',
  '2. high': '64988.32000000',
  '3. low': '62534.61000000',
  '4. close': '64068.33000000',
  '5. volume': '12517.40763597'},
 '2026-02-23': {'1. open': '67616.01000000',
  '2. high': '67656.42000000',
  '3. low': '63855.00000000',
  '4. close': '64625.78000000',
  '5. volume': '15198.01176266'},
 '2026-02-22': {'1. open': '67955.78000000',
  '2. high': '68241.40000000',
  '3. low': '67132.81000000',
  '4. close': '67617.98000000',
  '5. volume': '3263.53347230'},
 '2026-02-21': {'1. open': '67984.42000000',
  '2. high': '68683.27000000',
  '3. low': '67516.93000000',
  '4. close': '67955.78000000',
  '5. volume': '3287.06467470'},
 '2026-02-20': {'1. open': '66972.49000000',
  '2. high': '68294.86000000',
  '3. low': '66427.23000000',
  '4. close': '67984.42000000',
  '5. volume': '11349.70677085'},
 '2026-02-19': {'1. open': '66419.78000000',
  '2. high': '67288.22000000',
  '3. low': '65604.63000000',
  '4. close': '66972.50000000',
  '5. volume': '8505.29632895'},
 '2026-02-18': {'1. open': '67466.70000000',
  '2. high': '68438.84000000',
  '3. low': '65812.57000000',
  '4. close': '66419.79000000',
  '5. volume': '9687.16921753'},
 '2026-02-17': {'1. open': '68859.55000000',
  '2. high': '69199.51000000',
  '3. low': '66569.58000000',
  '4. close': '67466.70000000',
  '5. volume': '9122.62622708'},
 '2026-02-16': {'1. open': '68792.00000000',
  '2. high': '70089.99000000',
  '3. low': '67251.81000000',
  '4. close': '68858.13000000',
  '5. volume': '6626.85996745'},
 '2026-02-15': {'1. open': '69786.96000000',
  '2. high': '70941.65000000',
  '3. low': '68020.00000000',
  '4. close': '68792.00000000',
  '5. volume': '5965.51322769'},
 '2026-02-14': {'1. open': '68812.00000000',
  '2. high': '70531.53000000',
  '3. low': '68697.63000000',
  '4. close': '69786.96000000',
  '5. volume': '5586.98146780'},
 '2026-02-13': {'1. open': '66207.99000000',
  '2. high': '69434.20000000',
  '3. low': '65799.71000000',
  '4. close': '68812.00000000',
  '5. volume': '12104.28673482'},
 '2026-02-12': {'1. open': '67032.71000000',
  '2. high': '68382.90000000',
  '3. low': '65065.47000000',

In [39]:
# Step 2: Build DataFrame treating keys as the index rows
df = pd.DataFrame.from_dict(data['Time Series (Digital Currency Daily)'], orient='index')

df

,1. open,2. high,3. low,4. close,5. volume
2026-06-08,63302.03000000,63513.09000000,63114.23000000,63502.17000000,321.37628282
2026-06-07,60850.48000000,64234.45000000,60706.40000000,63302.73000000,9793.17273270
2026-06-06,61031.98000000,61499.41000000,59448.45000000,60850.48000000,9073.41539934
2026-06-05,63806.02000000,63906.02000000,59073.01000000,61032.00000000,28732.71500543
2026-06-04,64039.99000000,64695.00000000,61309.25000000,63806.02000000,25533.58651100
...,...,...,...,...,...
2010-07-21,0.07920000,0.07920000,0.07920000,0.07920000,0.00000000
2010-07-20,0.07470000,0.07470000,0.07470000,0.07470000,0.00000000
2010-07-19,0.08080000,0.08080000,0.08080000,0.08080000,0.00000000
2010-07-18,0.08580000,0.08580000,0.08580000,0.08580000,0.00000000
2010-07-17,0.05000000,0.05000000,0.05000000,0.05000000,0.00000000

In [40]:
# Step 3: Remove Alpha Vantage metadata numbering from column headers
df.columns = [col.split('. ')[1] for col in df.columns]

# Step 4: Map elements into standard floating-point datatypes
df = df.apply(pd.to_numeric)

# Step 5: Enforce official chronological order and label the index
df.index = pd.to_datetime(df.index)
df.index.name = 'date'
df = df.sort_index()

df

                  open        high         low       close        volume
date
2010-07-17      0.0500      0.0500      0.0500      0.0500      0.000000
2010-07-18      0.0858      0.0858      0.0858      0.0858      0.000000
2010-07-19      0.0808      0.0808      0.0808      0.0808      0.000000
2010-07-20      0.0747      0.0747      0.0747      0.0747      0.000000
2010-07-21      0.0792      0.0792      0.0792      0.0792      0.000000
...                ...         ...         ...         ...           ...
2026-06-04  64039.9900  64695.0000  61309.2500  63806.0200  25533.586511
2026-06-05  63806.0200  63906.0200  59073.0100  61032.0000  28732.715005
2026-06-06  61031.9800  61499.4100  59448.4500  60850.4800   9073.415399
2026-06-07  60850.4800  64234.4500  60706.4000  63302.7300   9793.172733
2026-06-08  63302.0300  63513.0900  63114.2300  63502.1700    321.376283

[5806 rows x 5 columns]

# 8) Sentiment

In [41]:
url = (
    "https://www.alphavantage.co/query?"
    "function=NEWS_SENTIMENT"
    "&tickers=AAPL"   # for Apple, 
    "&limit=10"
    f"&apikey={ALPHAADVANTAGE_API_KEY}"
)

data = requests.get(url).json()

In [42]:
data

{'items': '50',
 'sentiment_score_definition': 'x <= -0.35: Bearish; -0.35 < x <= -0.15: Somewhat-Bearish; -0.15 < x < 0.15: Neutral; 0.15 <= x < 0.35: Somewhat_Bullish; x >= 0.35: Bullish',
 'relevance_score_definition': '0 < x <= 1, with a higher score indicating higher relevance.',
 'feed': [{'title': "Top Analyst Eyes 30% Upside On AAPL Stock Ahead Of WWDC: No 'Treadmill Approach' Expected As John Ternus",
   'url': 'https://www.benzinga.com/markets/equities/26/06/53053984/top-analyst-eyes-30-upside-on-aapl-stock-ahead-of-wwdc-no-treadmill-approach-expected-as-john-ternus-prepares-to-take-apple-ceo-baton',
   'time_published': '20260608T113257',
   'authors': ['Rishabh Mishra'],
   'summary': 'Wedbush Securities analyst Dan Ives projects a 30% upside for Apple (AAPL) stock ahead of its Worldwide Developers Conference (WWDC), anticipating a "pivotal moment" with its AI strategy announcement. The event is also expected to mark a foundational milestone for John Ternus, who is slated to take over as CEO from Tim Cook later this year, with Wedbush expecting him to drive new global growth. Apple\'s AI strategy, including revamping Siri with Google\'s Gemini models, is seen as a significant monetization opportunity, potentially adding $15 billion in annual services revenue and $75 to $100 to the stock price.',
   'banner_image': 'https://cdn.benzinga.com/cdn-cgi/image/width=1300,format=auto,quality=85/files/images/story/2025/07/24/article-header-background-image.png',
   'source': 'Benzinga',
   'category_within_source': 'General',
   'source_domain': 'Benzinga',
   'topics': [{'topic': 'financial_markets', 'relevance_score': '0.949870'},
    {'topic': 'technology', 'relevance_score': '0.812710'}],
   'overall_sentiment_score': 0.408455,
   'overall_sentiment_label': 'Bullish',
   'ticker_sentiment': [{'ticker': 'AAPL',
     'relevance_score': '1.000000',
     'ticker_sentiment_score': '0.524478',
     'ticker_sentiment_label': 'Bullish'},
    {'ticker': 'GOOG',
     'relevance_score': '0.619781',
     'ticker_sentiment_score': '0.271184',
     'ticker_sentiment_label': 'Somewhat-Bullish'}]},
  {'title': 'Apple (AAPL) Is A Top Stock In Billionaire Ken Fisher’s Portfolio',
   'url': 'https://uk.finance.yahoo.com/news/apple-aapl-top-stock-billionaire-105404818.html',
   'time_published': '20260608T105357',
   'authors': ['Ramish Cheema'],
   'summary': "Apple Inc. (NASDAQ:AAPL) is a top holding in Billionaire Ken Fisher's portfolio, with its shares increasing 53% over the past year and 14% year-to-date. Analysts like Melius Research and Evercore ISI have raised its price targets due to factors such as growing consumer preference for voice commands, Apple's hardware and software ecosystem, and potential for monetizing AI. However, there are concerns regarding Qualcomm's largest customer relationship being threatened by Apple's in-house modem chip development and US-China trade tensions impacting China revenue exposure.",
   'banner_image': 'https://s.yimg.com/ny/api/res/1.2/PGbIfU4QaipKQ9w2ojLYBA--/YXBwaWQ9aGlnaGxhbmRlcjt3PTk2MDtoPTY0MA--/https://media.zenfs.com/en/insidermonkey.com/81c19848a45a03d67c33dd64ad4242ee',
   'source': 'Yahoo Finance UK',
   'category_within_source': 'General',
   'source_domain': 'Yahoo Finance UK',
   'topics': [{'topic': 'financial_markets', 'relevance_score': '0.903006'},
    {'topic': 'technology', 'relevance_score': '0.812964'},
    {'topic': 'earnings', 'relevance_score': '0.712706'}],
   'overall_sentiment_score': 0.038032,
   'overall_sentiment_label': 'Neutral',
   'ticker_sentiment': [{'ticker': 'AAPL',
     'relevance_score': '0.964469',
     'ticker_sentiment_score': '0.305658',
     'ticker_sentiment_label': 'Somewhat-Bullish'},
    {'ticker': 'QCOM',
     'relevance_score': '0.736498',
     'ticker_sentiment_score': '-0.250899',
     'ticker_sentiment_label': 'Somewhat-Bearish'}]},
  {'title': 'Apple expected to unveil new AI features at last developers conference with CEO Tim Cook',
   'url': 'https://www.nbcchicago.com/news/tech/apple-expected-unveil-new-ai-features/3945317/',
   'time_published': '20260608T092306',
   'authors': ['Barbara Ortutay'],
   'summary': "Apple is expected to announce new artificial intelligence features at its annual Worldwide Developers Conference, which will be CEO Tim Cook's last before John Ternus takes over in September. Analysts anticipate updates to Siri, making it a more conversational AI chatbot capable of managing tasks across Apple devices. This conference comes as Apple aims to catch up with other tech giants in the AI space and transitions leadership during a significant technological shift.",
   'banner_image': 'https://media.nbcchicago.com/2026/04/JOHN-TERNUS.jpg',
   'source': 'NBC 5 Chicago',
   'category_within_source': 'General',
   'source_domain': 'NBC 5 Chicago',
   'topics': [{'topic': 'technology', 'relevance_score': '1.000000'}],
   'overall_sentiment_score': 0.232266,
   'overall_sentiment_label': 'Somewhat-Bullish',
   'ticker_sentiment': [{'ticker': 'AAPL',
     'relevance_score': '0.955845',
     'ticker_sentiment_score': '0.325636',
     'ticker_sentiment_label': 'Somewhat-Bullish'},
    {'ticker': 'GOOG',
     'relevance_score': '0.697354',
     'ticker_sentiment_score': '0.113314',
     'ticker_sentiment_label': 'Neutral'}]},
  {'title': 'Apple expected to unveil new AI features at last developers conference with CEO Tim Cook',
   'url': 'https://www.nbcwashington.com/news/tech/apple-expected-unveil-new-ai-features/4113737/',
   'time_published': '20260608T092300',
   'authors': ['Barbara Ortutay'],
   'summary': 'Apple is expected to unveil new artificial intelligence features at its annual developers conference, which will be the last one featuring CEO Tim Cook before he retires. Analysts anticipate updates to AI features, including its Siri voice assistant, as Apple aims to catch up with other Big Tech companies in the AI space. John Ternus is set to succeed Cook, taking over during a pivotal time for Apple with major shifts in the industry due to AI.',
   'banner_image': 'https://media.nbcwashington.com/2026/04/AP26097538551822.jpg?quality=85&strip=all',
   'source': 'NBC4 Washington',
   'category_within_source': 'General',
   'source_domain': 'NBC4 Washington',
   'topics': [{'topic': 'technology', 'relevance_score': '1.000000'}],
   'overall_sentiment_score': 0.306101,
   'overall_sentiment_label': 'Somewhat-Bullish',
   'ticker_sentiment': [{'ticker': 'AAPL',
     'relevance_score': '1.000000',
     'ticker_sentiment_score': '0.347445',
     'ticker_sentiment_label': 'Somewhat-Bullish'}]},
  {'title': 'Does Arm Holdings Has a crypto coin? What is ARMUSDT and how to trade with WEEX TradFi',
   'url': 'https://www.weex.com/wiki/article/does-arm-holdings-has-a-crypto-coin-what-is-armusdt-and-how-to-trade-with-weex-tradfi-hzpyqtpd1pk7d6xydwv6pfz5',
   'time_published': '20260608T080928',
   'authors': ['WEEX'],
   'summary': 'Arm Holdings does not have an official cryptocurrency. "ARMUSDT" on crypto platforms refers to derivatives or tokenized products that track ARM\'s stock price, allowing traders to gain exposure without owning shares. Platforms like WEEX TradFi offer 24/7 trading of these financial products using USDT as collateral, providing a crypto-native way to speculate on stock price movements.',
   'banner_image': 'https://images-cms.weex.com/medium_4_1b32cac122.png?format=avif',
   'source': 'WEEX',
   'category_within_source': 'General',
   'source_domain': 'WEEX',
   'topics': [{'topic': 'blockchain', 'relevance_score': '1.000000'},
    {'topic': 'financial_markets', 'relevance_score': '0.932283'},
    {'topic': 'technology', 'relevance_score': '0.721494'},
    {'topic': 'finance', 'relevance_score': '0.647849'}],
   'overall_sentiment_score': 0.124752,
   'overall_sentiment_label': 'Neutral',
   'ticker_sentiment': [{'ticker': 'ARM',
     'relevance_score': '1.000000',
     'ticker_sentiment_score': '0.135360',
     'ticker_sentiment_label': 'Neutral'},
    {'ticker': 'GOOGL',
     'relevance_score': '0.632733',
     'ticker_sentiment_score': '0.147426',
     'ticker_sentiment_label': 'Neutral'},
    {'ticker': 'MSFT',
     'relevance_score': '0.642664',
     'ticker_sentiment_score': '0.131272',
     'ticker_sentiment_label': 'Neutral'},
    {'ticker': 'V',
     'relevance_score': '0.620654',
     'ticker_sentiment_score': '0.122622',
     'ticker_sentiment_label': 'Neutral'},
    {'ticker': 'AAPL',
     'relevance_score': '0.601054',
     'ticker_sentiment_score': '0.119764',
     'ticker_sentiment_label': 'Neutral'}]},
  {'title': 'iShares MSCI World ETF Faces a Crucible of Rate Fears, a Dividend Date, and a Landmark Space IPO',
   'url': 'https://www.ad-hoc-news.de/boerse/news/ueberblick/ishares-msci-world-etf-faces-a-crucible-of-rate-fears-a-dividend-date/69498058',
   'time_published': '20260608T033915',
   'authors': [],
   'summary': "The iShares MSCI World ETF is heading into a crucial week, grappling with tech stock selloffs, fears of rising interest rates, a forthcoming dividend announcement, and the landmark SpaceX IPO. The ETF, heavily weighted in technology, is particularly vulnerable to interest rate changes and recent economic data. Additionally, new tariffs on pharmaceuticals and upcoming Fed decisions add further pressure, making the interplay of these factors critical for the fund's short-term direction.",
   'banner_image': 'https://mdb.ad-hoc-news.de/bild/bild-2632135_480_300.webp',
   'source': 'AD HOC NEWS',
   'category_within_source': 'General',
   'source_domain': 'AD HOC NEWS',
   'topics': [{'topic': 'financial_markets', 'relevance_score': '0.903828'},
    {'topic': 'ipo', 'relevance_score': '0.926532'},
    {'topic': 'economy_monetary', 'relevance_score': '0.845582'},
    {'topic': 'technology', 'relevance_score': '0.727557'},
    {'topic': 'earnings', 'relevance_score': '0.728876'}],
   'overall_sentiment_score': -0.180165,
   'overall_sentiment_label': 'Somewhat-Bearish',
   'ticker_sentiment': [{'ticker': 'URTH',
     'relevance_score': '1.000000',
     'ticker_sentiment_score': '-0.218073',
     'ticker_sentiment_label': 'Somewhat-Bearish'},
    {'ticker': 'AVGO',
     'relevance_score': '0.725065',
     'ticker_sentiment_score': '-0.441387',
     'ticker_sentiment_label': 'Bearish'},
    {'ticker': 'MSCI',
     'relevance_score': '0.715433',
     'ticker_sentiment_score': '0.132422',
     'ticker_sentiment_label': 'Neutral'},
    {'ticker': 'AAPL',
     'relevance_score': '0.726852',
     'ticker_sentiment_score': '0.129572',
     'ticker_sentiment_label': 'Neutral'},
    {'ticker': 'NVDA',
     'relevance_score': '0.606958',
     'ticker_sentiment_score': '-0.300453',
     'ticker_sentiment_label': 'Somewhat-Bearish'}]},
  {'title': 'Look back at 50 years of Apple from garage to global icon',
   'url': 'https://www.detroitnews.com/picture-gallery/tech/2026/06/07/look-back-at-50-years-of-apple-from-garage-to-global-icon/90452871007/',
   'time_published': '20260608T020059',
   'authors': [],
   'summary': "This article looks back at 50 years of Apple Inc., tracing its journey from a humble garage startup to becoming a global technology powerhouse. It includes 34 photos illustrating the company's evolution and impact over half a century.",
   'banner_image': None,
   'source': 'The Detroit News',
   'category_within_source': 'General',
   'source_domain': 'The Detroit News',
   'topics': [{'topic': 'technology', 'relevance_score': '0.936323'}],
   'overall_sentiment_score': 0.424261,
   'overall_sentiment_label': 'Bullish',
   'ticker_sentiment': [{'ticker': 'AAPL',
     'relevance_score': '1.000000',
     'ticker_sentiment_score': '0.386953',
     'ticker_sentiment_label': 'Bullish'}]},
  {'title': 'STI Stock Extends Triple-Digit Rally: Solidion Highlights Commercial-Ready Lithium Battery Technology',
   'url': 'https://stocktwits.com/news-articles/markets/equity/sti-stock-extends-triple-digit-rally-solidion-highlights-commercial-ready-lithium-battery-technology/cZ0F0vaReC2',
   'time_published': '20260607T213913',
   'authors': ['Ahmed Farhath'],
   'summary': 'Solidion Technology Inc. (STI) has seen its stock rally significantly after announcing patents for commercial-ready lithium-sulfur, lithium-air, and anodeless lithium metal batteries. These batteries are designed for various applications, from space economy to electric vehicles and drones, addressing the soaring demand for energy driven by AI infrastructure and space exploration. The company\'s stock has more than tripled this year, with retail sentiment remaining "extremely bullish."',
   'banner_image': 'https://news.stocktwits-cdn.com/large_Getty_Images_2191702528_jpg_351037bf42.webp',
   'source': 'Stocktwits',
   'category_within_source': 'General',
   'source_domain': 'Stocktwits',
   'topics': [{'topic': 'technology', 'relevance_score': '0.936377'},
    {'topic': 'financial_markets', 'relevance_score': '0.824622'},
    {'topic': 'energy_transportation', 'relevance_score': '0.712328'},
    {'topic': 'earnings', 'relevance_score': '0.607662'}],
   'overall_sentiment_score': 0.369016,
   'overall_sentiment_label': 'Bullish',
   'ticker_sentiment': [{'ticker': 'STI',
     'relevance_score': '1.000000',
     'ticker_sentiment_score': '0.887818',
     'ticker_sentiment_label': 'Bullish'},
    {'ticker': 'AAPL',
     'relevance_score': '0.743554',
     'ticker_sentiment_score': '0.133879',
     'ticker_sentiment_label': 'Neutral'},
    {'ticker': 'ORCL',
     'relevance_score': '0.621334',
     'ticker_sentiment_score': '0.149316',
     'ticker_sentiment_label': 'Neutral'}]},
  {'title': 'Amazon.com, Inc. (AMZN): Top 10 Stocks That Members of Congress Own',
   'url': 'https://www.insidermonkey.com/blog/amazon-com-inc-amzn-top-10-stocks-that-members-of-congress-own-1776336/',
   'time_published': '20260607T193800',
   'authors': ['Sajjl Nooranne'],
   'summary': "Amazon.com, Inc. (AMZN) is highlighted as one of the top 10 stocks owned by members of Congress, with 353 hedge funds holding stakes in Q1 2026. The article details Amazon's recent acquisition of Apple's 20% stake in Globalstar as part of an $11.6 billion deal, aimed at expanding its satellite communications presence. Additionally, Truist raised Amazon's price target to $320 due to increased long-term Amazon Web Services revenue forecasts, considering significant AI partnerships with Anthropic and OpenAI.",
   'banner_image': 'https://d2w7kw43nye0pi.cloudfront.net/hLNo7D2xCKIngoxoT93E1fdRD2ax2ZlA264lgyidKjg/resize:fit:480:299:0/plain/https://imonkeyblog.s3.us-east-1.amazonaws.com/blog/wp-content/uploads/2015/05/shutterstock_171257771.jpg',
   'source': 'Insider Monkey',
   'category_within_source': 'General',
   'source_domain': 'Insider Monkey',
   'topics': [{'topic': 'mergers_and_acquisitions',
     'relevance_score': '0.832915'},
    {'topic': 'technology', 'relevance_score': '0.943785'},
    {'topic': 'financial_markets', 'relevance_score': '0.727075'}],
   'overall_sentiment_score': 0.2216,
   'overall_sentiment_label': 'Somewhat-Bullish',
   'ticker_sentiment': [{'ticker': 'AMZN',
     'relevance_score': '1.000000',
     'ticker_sentiment_score': '0.330663',
     'ticker_sentiment_label': 'Somewhat-Bullish'},
    {'ticker': 'AAPL',
     'relevance_score': '0.608675',
     'ticker_sentiment_score': '0.129897',
     'ticker_sentiment_label': 'Neutral'}]},
  {'title': 'ProShares S&P 500 Ex-Energy ETF Holdings',
   'url': 'https://www.quiverquant.com/etf/ProShares%20S&P%20500%20Ex-Energy%20ETF',
   'time_published': '20260607T185348',
   'authors': [],
   'summary': "This article details the holdings of the ProShares S&P 500 Ex-Energy ETF (SPXE), which tracks large and mid-cap US stocks excluding the energy sector. It lists the top holdings by estimated value, including technology giants like NVIDIA, Apple, and Microsoft. The report also provides a comprehensive list of recent changes in the ETF's holdings.",
   'banner_image': None,
   'source': 'Quiver Quantitative',
   'category_within_source': 'General',
   'source_domain': 'Quiver Quantitative',
   'topics': [{'topic': 'financial_markets', 'relevance_score': '0.944702'}],
   'overall_sentiment_score': 0.115079,
   'overall_sentiment_label': 'Neutral',
   'ticker_sentiment': [{'ticker': 'SPXE',
     'relevance_score': '1.000000',
     'ticker_sentiment_score': '0.104961',
     'ticker_sentiment_label': 'Neutral'},
    {'ticker': 'NVDA',
     'relevance_score': '0.866116',
     'ticker_sentiment_score': '0.109929',
     'ticker_sentiment_label': 'Neutral'},
    {'ticker': 'AAPL',
     'relevance_score': '0.800919',
     'ticker_sentiment_score': '0.114693',
     'ticker_sentiment_label': 'Neutral'},
    {'ticker': 'MSFT',
     'relevance_score': '0.765880',
     'ticker_sentiment_score': '0.126867',
     'ticker_sentiment_label': 'Neutral'},
    {'ticker': 'AMZN',
     'relevance_score': '0.714570',
     'ticker_sentiment_score': '0.117217',
     'ticker_sentiment_label': 'Neutral'}]},
  {'title': 'XLK vs. SOXX ETF Comparison: Cost, Performance, and Risk Analysis - News and Statistics',
   'url': 'https://www.indexbox.io/blog/xlk-vs-soxx-comparing-two-top-tech-etfs-in-2026/',
   'time_published': '20260607T141000',
   'authors': [],
   'summary': "This article compares two prominent technology-focused ETFs, XLK and SOXX, highlighting their differences in cost, performance, and risk. While XLK offers broader tech exposure with lower expense, SOXX, focused on semiconductors, has shown significantly higher returns over the past year but with greater volatility. The analysis underscores the impact of surging demand for AI chips on SOXX's performance.",
   'banner_image': 'https://www.indexbox.io/landing/img/blog/telegram-fallback/3a1eebe14cf52c29c402be30afb9bfd0.webp',
   'source': 'IndexBox',
   'category_within_source': 'General',
   'source_domain': 'IndexBox',
   'topics': [{'topic': 'financial_markets', 'relevance_score': '0.914087'},
    {'topic': 'technology', 'relevance_score': '0.822218'}],
   'overall_sentiment_score': 0.278826,
   'overall_sentiment_label': 'Somewhat-Bullish',
   'ticker_sentiment': [{'ticker': 'SOXX',
     'relevance_score': '1.000000',
     'ticker_sentiment_score': '0.334870',
     'ticker_sentiment_label': 'Somewhat-Bullish'},
    {'ticker': 'NVDA',
     'relevance_score': '0.621966',
     'ticker_sentiment_score': '0.309202',
     'ticker_sentiment_label': 'Somewhat-Bullish'},
    {'ticker': 'AAPL',
     'relevance_score': '0.584789',
     'ticker_sentiment_score': '0.254530',
     'ticker_sentiment_label': 'Somewhat-Bullish'},
    {'ticker': 'MSFT',
     'relevance_score': '0.572536',
     'ticker_sentiment_score': '0.295664',
     'ticker_sentiment_label': 'Somewhat-Bullish'}]},
  {'title': "Apple's AI Moment, Spacex's $4 Trillion Valuation And More: This Week In Appleverse",
   'url': 'https://www.benzinga.com/markets/tech/26/06/53048720/apples-ai-moment-spacexs-4-trillion-valuation-and-more-this-week-in-appleverse',
   'time_published': '20260607T110656',
   'authors': ['Mohd Haider'],
   'summary': "This article summarizes the top tech news from the past weekend, focusing on Apple's potential AI advancements and the impact of SpaceX's valuation on the market. It also highlights Google's loss of the second market cap spot to Apple and Rivian's prediction about the obsolescence of current car infotainment systems due to AI.",
   'banner_image': 'https://cdn.benzinga.com/cdn-cgi/image/width=1300,format=auto,quality=85/files/images/story/2025/07/24/article-header-background-image.png',
   'source': 'Benzinga',
   'category_within_source': 'General',
   'source_domain': 'Benzinga',
   'topics': [{'topic': 'technology', 'relevance_score': '1.000000'},
    {'topic': 'financial_markets', 'relevance_score': '0.839419'},
    {'topic': 'finance', 'relevance_score': '0.727908'}],
   'overall_sentiment_score': -0.072129,
   'overall_sentiment_label': 'Neutral',

In [71]:
data.keys()

dict_keys(['items', 'sentiment_score_definition', 'relevance_score_definition', 'feed'])

In [72]:
data['items']

'50'

In [73]:
data['sentiment_score_definition']

'x <= -0.35: Bearish; -0.35 < x <= -0.15: Somewhat-Bearish; -0.15 < x < 0.15: Neutral; 0.15 <= x < 0.35: Somewhat_Bullish; x >= 0.35: Bullish'

In [74]:
data['relevance_score_definition']

'0 < x <= 1, with a higher score indicating higher relevance.'

In [75]:
data['feed']

[{'title': 'Apple announces first developer center in Europe ahead of WWDC (AAPL:NASDAQ)',
  'url': 'https://seekingalpha.com/news/4600223-apple-announces-first-developer-center-in-europe-ahead-of-wwdc',
  'time_published': '20260603T124157',
  'authors': ['Chris Ciaccia'],
  'summary': 'Apple announced it will open its first developer center in Europe, located in Berlin, ahead of its annual developer conference next week. This new center aims to provide European developers with enhanced access to Apple experts and various events. The move is expected to support the developer community in Europe.',
  'banner_image': 'https://static.seekingalpha.com/cdn/s3/uploads/getty_images/2260260678/image_2260260678.jpg?io=getty-c-w630',
  'source': 'Seeking Alpha',
  'category_within_source': 'General',
  'source_domain': 'Seeking Alpha',
  'topics': [{'topic': 'technology', 'relevance_score': '1.000000'}],
  'overall_sentiment_score': 0.346226,
  'overall_sentiment_label': 'Somewhat-Bullish',
  'ticker_sentiment': [{'ticker': 'AAPL',
    'relevance_score': '1.000000',
    'ticker_sentiment_score': '0.301480',
    'ticker_sentiment_label': 'Somewhat-Bullish'}]},
 {'title': 'HDV vs. FDVV: One of These High-Dividend ETFs Has a Surprising Secret',
  'url': 'https://www.theglobeandmail.com/investing/markets/markets-news/motley/2280516/hdv-vs-fdvv-one-of-these-high-dividend-etfs-has-a-surprising-secret/',
  'time_published': '20260603T121814',
  'authors': ['Motley Fool', 'Sara Appino'],
  'summary': 'This article compares two high-dividend ETFs, HDV and FDVV, highlighting their differing investment strategies, expense ratios, and performance. While HDV prioritizes defensive stability and established, lower-volatility companies with a focus on consistent income, FDVV incorporates growth-oriented sectors and bets on future dividend growth, leading to higher recent total returns but also greater volatility. The analysis reveals that FDVV\'s "high-dividend" label comes with a surprising secret regarding its top holdings\' actual dividend yields.',
  'banner_image': 'https://barchart-news-media-prod.aws.barchart.com/FC/761147b2d76200c778f6c3ff6c8b5a75/pixel%3Fslug%3Dmotleyfoolgm-2026-6-3-hdv-vs-fdvv-one-of-these-high-dividend-etfs-has-a-surprising-secret',
  'source': 'The Globe and Mail',
  'category_within_source': 'General',
  'source_domain': 'The Globe and Mail',
  'topics': [{'topic': 'finance', 'relevance_score': '0.848099'},
   {'topic': 'financial_markets', 'relevance_score': '0.926783'},
   {'topic': 'technology', 'relevance_score': '0.646991'},
   {'topic': 'energy_transportation', 'relevance_score': '0.636152'},
   {'topic': 'life_sciences', 'relevance_score': '0.647215'}],
  'overall_sentiment_score': 0.311317,
  'overall_sentiment_label': 'Somewhat-Bullish',
  'ticker_sentiment': [{'ticker': 'HDV',
    'relevance_score': '1.000000',
    'ticker_sentiment_score': '0.296770',
    'ticker_sentiment_label': 'Somewhat-Bullish'},
   {'ticker': 'NVDA',
    'relevance_score': '0.645966',
    'ticker_sentiment_score': '0.327313',
    'ticker_sentiment_label': 'Somewhat-Bullish'},
   {'ticker': 'AAPL',
    'relevance_score': '0.609285',
    'ticker_sentiment_score': '0.329965',
    'ticker_sentiment_label': 'Somewhat-Bullish'},
   {'ticker': 'MSFT',
    'relevance_score': '0.602608',
    'ticker_sentiment_score': '0.315632',
    'ticker_sentiment_label': 'Somewhat-Bullish'}]},
 {'title': '5 Reasons Why Customers Avoid Shopping At The Apple Store',
  'url': 'https://www.bgr.com/2183255/reasons-customers-avoid-shopping-apple-store/',
  'time_published': '20260603T121658',
  'authors': ['José Adorno'],
  'summary': 'This article explores five reasons why customers are increasingly avoiding physical Apple Stores. These reasons include often being too busy, the stores prioritizing online pickup orders over walk-in purchases, products being more expensive than at third-party retailers, the geographical inconvenience of not having an Apple Store nearby for many customers, and a shift in employee approach from help-oriented to sales-driven. The article suggests that the original unique customer experience has diminished, pushing many customers towards online shopping.',
  'banner_image': 'https://www.bgr.com/img/gallery/5-reasons-why-customers-avoid-shopping-at-the-apple-store/intro-1779987702.jpg',
  'source': 'BGR',
  'category_within_source': 'General',
  'source_domain': 'BGR',
  'topics': [{'topic': 'retail_wholesale', 'relevance_score': '0.931397'},
   {'topic': 'technology', 'relevance_score': '0.843185'}],
  'overall_sentiment_score': 0.133964,
  'overall_sentiment_label': 'Neutral',
  'ticker_sentiment': [{'ticker': 'AAPL',
    'relevance_score': '1.000000',
    'ticker_sentiment_score': '0.078555',
    'ticker_sentiment_label': 'Neutral'},
   {'ticker': 'AMZN',
    'relevance_score': '0.724628',
    'ticker_sentiment_score': '0.154096',
    'ticker_sentiment_label': 'Somewhat-Bullish'},
   {'ticker': 'BBY',
    'relevance_score': '0.681582',
    'ticker_sentiment_score': '0.165817',
    'ticker_sentiment_label': 'Somewhat-Bullish'},
   {'ticker': 'TGT',
    'relevance_score': '0.689505',
    'ticker_sentiment_score': '0.183346',
    'ticker_sentiment_label': 'Somewhat-Bullish'}]},
 {'title': "Apple Inc. $AAPL is Tranquility Partners LLC's 3rd Largest Position",
  'url': 'https://www.marketbeat.com/instant-alerts/filing-apple-inc-aapl-is-tranquility-partners-llcs-3rd-largest-position-2026-06-03/',
  'time_published': '20260603T105159',
  'authors': ['MarketBeat'],
  'summary': 'Tranquility Partners LLC maintained Apple (NASDAQ:AAPL) as its third-largest holding despite reducing its stake by 6.5% in Q4, valuing its position at approximately $10.5 million. Apple reported strong quarterly earnings of $2.01 per share and $111.18 billion in revenue, surpassing analyst estimates. Wall Street analysts generally hold a "Moderate Buy" consensus rating with a target price of $310.31, anticipating further growth, especially with potential AI feature announcements at WWDC.',
  'banner_image': 'https://www.marketbeat.com/logos/apple-inc-logo-1200x675.png',
  'source': 'MarketBeat',
  'category_within_source': 'General',
  'source_domain': 'MarketBeat',
  'topics': [{'topic': 'earnings', 'relevance_score': '0.919146'},
   {'topic': 'financial_markets', 'relevance_score': '0.907798'},
   {'topic': 'technology', 'relevance_score': '0.846735'},
   {'topic': 'finance', 'relevance_score': '0.721531'}],
  'overall_sentiment_score': 0.395429,
  'overall_sentiment_label': 'Bullish',
  'ticker_sentiment': [{'ticker': 'AAPL',
    'relevance_score': '1.000000',
    'ticker_sentiment_score': '0.429611',
    'ticker_sentiment_label': 'Bullish'}]},
 {'title': 'Apple Reaps AI Benefits Without Capex Burden (Rating Upgrade) (NASDAQ:AAPL)',
  'url': 'https://seekingalpha.com/article/4911334-apple-reaps-ai-benefits-without-capex-burden-rating-upgrade',
  'time_published': '20260603T103959',
  'authors': ['Envision Research'],
  'summary': "Apple Inc. (AAPL) has received an upgrade to buy, driven by its strategic positioning as a trusted AI endpoint for agentic AI applications. The company reported strong FQ2 results with a 21.8% YoY increase in normalized EPS and over $111 billion in sales, achieving this growth with minimal capital expenditure unlike other hyperscalers. Apple's asset-light model and vast active device base uniquely position it to monetize AI without the significant capex burdens faced by many competitors, but risks include its premium valuation and the need for Siri AI upgrades.",
  'banner_image': 'https://static.seekingalpha.com/cdn/s3/uploads/getty_images/2174911519/image_2174911519.jpg?io=getty-c-w630',
  'source': 'Seeking Alpha',
  'category_within_source': 'General',
  'source_domain': 'Seeking Alpha',
  'topics': [{'topic': 'earnings', 'relevance_score': '0.922384'},
   {'topic': 'technology', 'relevance_score': '0.811760'},
   {'topic': 'financial_markets', 'relevance_score': '0.748969'}],
  'overall_sentiment_score': 0.4658,
  'overall_sentiment_label': 'Bullish',
  'ticker_sentiment': [{'ticker': 'AAPL',
    'relevance_score': '1.000000',
    'ticker_sentiment_score': '0.470979',
    'ticker_sentiment_label': 'Bullish'}]},
 {'title': 'Apple Inc. $AAPL Holdings Decreased by Matthew 25 Management Corp',
  'url': 'https://www.marketbeat.com/instant-alerts/filing-apple-inc-aapl-holdings-decreased-by-matthew-25-management-corp-2026-06-03/',
  'time_published': '20260603T084159',
  'authors': ['MarketBeat'],
  'summary': 'Matthew 25 Management Corp reduced its stake in Apple (AAPL) by 6.5% during the fourth quarter, selling 4,000 shares and leaving it with 57,500 shares valued at approximately $15.6 million. Despite this reduction, Apple reported strong quarterly results with EPS of $2.01 and revenue of $111.18 billion, both exceeding estimates, and raised its quarterly dividend to $0.27 per share. Analysts maintain a "Moderate Buy" rating with an average target price of $310.31, indicating continued positive sentiment towards the company.',
  'banner_image': 'https://www.marketbeat.com/logos/apple-inc-logo-1200x675.png',
  'source': 'MarketBeat',
  'category_within_source': 'General',
  'source_domain': 'MarketBeat',
  'topics': [{'topic': 'earnings', 'relevance_score': '0.915040'},
   {'topic': 'technology', 'relevance_score': '0.832674'},
   {'topic': 'financial_markets', 'relevance_score': '0.740497'},
   {'topic': 'finance', 'relevance_score': '0.632790'}],
  'overall_sentiment_score': 0.29382,
  'overall_sentiment_label': 'Somewhat-Bullish',
  'ticker_sentiment': [{'ticker': 'AAPL',
    'relevance_score': '1.000000',
    'ticker_sentiment_score': '0.257313',
    'ticker_sentiment_label': 'Somewhat-Bullish'}]},
 {'title': "Apple Inc. $AAPL is Heartland Bank & Trust Co's 2nd Largest Position",
  'url': 'https://www.marketbeat.com/instant-alerts/filing-apple-inc-aapl-is-heartland-bank-trust-cos-2nd-largest-position-2026-06-03/',
  'time_published': '20260603T084159',
  'authors': ['MarketBeat'],
  'summary': 'Heartland Bank & Trust Co, despite trimming its stake by 3.2% in the fourth quarter, still holds Apple Inc. (NASDAQ:AAPL) as its second-largest position, valued at approximately $18.1 million. This comes after Apple reported strong quarterly results, beating earnings and revenue estimates, and increasing its quarterly dividend. The article also details insider selling activities and analyst price target updates for Apple.',
  'banner_image': 'https://www.marketbeat.com/logos/apple-inc-logo-1200x675.png',
  'source': 'MarketBeat',
  'category_within_source': 'General',
  'source_domain': 'MarketBeat',
  'topics': [{'topic': 'earnings', 'relevance_score': '0.927378'},
   {'topic': 'financial_markets', 'relevance_score': '0.848032'},
   {'topic': 'technology', 'relevance_score': '0.718444'},
   {'topic': 'finance', 'relevance_score': '0.608190'}],
  'overall_sentiment_score': 0.27757,
  'overall_sentiment_label': 'Somewhat-Bullish',
  'ticker_sentiment': [{'ticker': 'AAPL',
    'relevance_score': '1.000000',
    'ticker_sentiment_score': '0.498079',
    'ticker_sentiment_label': 'Bullish'},
   {'ticker': 'NVDA',
    'relevance_score': '0.607599',
    'ticker_sentiment_score': '0.133696',
    'ticker_sentiment_label': 'Neutral'}]},
 {'title': 'SBI Securities Co. Ltd. Trims Stake in Apple Inc. $AAPL',
  'url': 'https://www.marketbeat.com/instant-alerts/filing-sbi-securities-co-ltd-trims-stake-in-apple-inc-aapl-2026-06-03/',
  'time_published': '20260603T084159',
  'authors': ['MarketBeat'],
  'summary': 'SBI Securities Co. Ltd. reduced its stake in Apple Inc. by 3.2% in the fourth quarter, selling 15,476 shares and retaining 472,812 shares valued at approximately $128.5 million. This reduction comes as Apple reported strong quarterly earnings, beating Wall Street expectations with $2.01 EPS and $111.18 billion in revenue, and raised its quarterly dividend to $0.27 per share. Despite the stake reduction by SBI Securities, analysts generally maintain a "Moderate Buy" rating for Apple with an average price target of $310.31.',
  'banner_image': 'https://www.marketbeat.com/logos/apple-inc-logo-1200x675.png',
  'source': 'MarketBeat',
  'category_within_source': 'General',
  'source_domain': 'MarketBeat',
  'topics': [{'topic': 'earnings', 'relevance_score': '0.936895'},
   {'topic': 'financial_markets', 'relevance_score': '0.809138'},
   {'topic': 'technology', 'relevance_score': '0.735866'},
   {'topic': 'finance', 'relevance_score': '0.623082'}],
  'overall_sentiment_score': 0.10739,
  'overall_sentiment_label': 'Neutral',
  'ticker_sentiment': [{'ticker': 'AAPL',
    'relevance_score': '1.000000',
    'ticker_sentiment_score': '0.291281',
    'ticker_sentiment_label': 'Somewhat-Bullish'},
   {'ticker': 'DELL',
    'relevance_score': '0.641702',
    'ticker_sentiment_score': '-0.148472',
    'ticker_sentiment_label': 'Neutral'}]},
 {'title': 'Apple Inc. $AAPL Stock Position Reduced by McIlrath & Eck LLC',
  'url': 'https://www.marketbeat.com/instant-alerts/filing-apple-inc-aapl-stock-position-reduced-by-mcilrath-eck-llc-2026-06-03/',
  'time_published': '20260603T084150',
  'authors': ['MarketBeat'],
  'summary': 'McIlrath & Eck LLC reduced its holdings in Apple (NASDAQ:AAPL) by 3.3% during the fourth quarter, selling 1,802 shares which leaves them with 53,488 shares valued at $14.5 million. Despite this reduction, Apple reported a strong quarter with EPS and revenue beating estimates, and analysts maintain a "Moderate Buy" rating with a consensus price target of $310.31. Institutional investors still own a significant portion of Apple\'s stock, with some increasing their positions substantially.',
  'banner_image': 'https://www.marketbeat.com/logos/apple-inc-logo-1200x675.png',
  'source': 'MarketBeat',
  'category_within_source': 'General',
  'source_domain': 'MarketBeat',
  'topics': [{'topic': 'earnings', 'relevance_score': '0.912473'},
   {'topic': 'financial_markets', 'relevance_score': '0.903035'},
   {'topic': 'technology', 'relevance_score': '0.843267'}],
  'overall_sentiment_score': 0.315098,
  'overall_sentiment_label': 'Somewhat-Bullish',
  'ticker_sentiment': [{'ticker': 'AAPL',
    'relevance_score': '1.000000',
    'ticker_sentiment_score': '0.304329',
    'ticker_sentiment_label': 'Somewhat-Bullish'}]},
 {'title': 'RNC Capital Management LLC Lowers Holdings in Apple Inc. $AAPL',
  'url': 'https://www.marketbeat.com/instant-alerts/filing-rnc-capital-management-llc-lowers-holdings-in-apple-inc-aapl-2026-06-03/',
  'time_published': '20260603T084149',
  'authors': ['MarketBeat'],
  'summary': 'RNC Capital Management LLC reduced its stake in Apple Inc. by 2.7% in the fourth quarter, selling 3,364 shares, though its remaining 120,584 shares are still valued at approximately $32.8 million. Despite this, Apple maintains a "Moderate Buy" consensus rating from analysts, with a target price around $310, driven by anticipation for WWDC and potential AI updates. The company recently surpassed EPS and revenue estimates and increased its dividend, but insider sales and its near 52-week high valuation suggest some caution among investors.',
  'banner_image': 'https://www.marketbeat.com/logos/apple-inc-logo-1200x675.png',
  'source': 'MarketBeat',
  'category_within_source': 'General',
  'source_domain': 'MarketBeat',
  'topics': [{'topic': 'earnings', 'relevance_score': '0.942820'},
   {'topic': 'financial_markets', 'relevance_score': '0.820558'},
   {'topic': 'technology', 'relevance_score': '0.715444'}],
  'overall_sentiment_score': 0.157539,
  'overall_sentiment_label': 'Somewhat-Bullish',
  'ticker_sentiment': [{'ticker': 'AAPL',
    'relevance_score': '0.963238',
    'ticker_sentiment_score': '0.115412',
    'ticker_sentiment_label': 'Neutral'},
   {'ticker': 'DELL',
    'relevance_score': '0.647546',
    'ticker_sentiment_score': '0.346762',
    'ticker_sentiment_label': 'Somewhat-Bullish'},
   {'ticker': 'NVDA',
    'relevance_score': '0.606139',
    'ticker_sentiment_score': '-0.137295',
    'ticker_sentiment_label': 'Neutral'},
   {'ticker': 'MSFT',
    'relevance_score': '0.591347',
    'ticker_sentiment_score': '0.248984',
    'ticker_sentiment_label': 'Somewhat-Bullish'}]},
 {'title': 'Christine Messmer PC Takes Position in Apple Inc. $AAPL',
  'url': 'https://www.marketbeat.com/instant-alerts/filing-christine-messmer-pc-takes-position-in-apple-inc-aapl-2026-06-03/',
  'time_published': '20260603T074408',
  'authors': ['MarketBeat'],
  'summary': 'Christine Messmer PC has disclosed a new fourth-quarter position in Apple Inc. ($AAPL), acquiring 28,619 shares valued at approximately $7.78 million, making it their 5th largest holding. Apple recently reported strong quarterly results with EPS of $2.01 and revenue of $111.18 billion, and raised its quarterly dividend to $0.27 per share. Despite some insider selling, institutional ownership remains high, and analysts have a "Moderate Buy" rating with a consensus target price of $310.31.',
  'banner_image': 'https://www.marketbeat.com/logos/apple-inc-logo-1200x675.png',
  'source': 'MarketBeat',
  'category_within_source': 'General',
  'source_domain': 'MarketBeat',
  'topics': [{'topic': 'earnings', 'relevance_score': '0.927775'},
   {'topic': 'financial_markets', 'relevance_score': '0.841667'},
   {'topic': 'technology', 'relevance_score': '0.744896'}],
  'overall_sentiment_score': 0.401106,
  'overall_sentiment_label': 'Bullish',
  'ticker_sentiment': [{'ticker': 'AAPL',
    'relevance_score': '1.000000',
    'ticker_sentiment_score': '0.424452',
    'ticker_sentiment_label': 'Bullish'}]},
 {'title': 'HCA Healthcare Stock Hands $39 Bil Back – Worth a Look?',
  'url': 'https://www.trefis.com/stock/hca/articles/601200/hca-healthcare-stock-hands-39-bil-back-worth-a-look/2026-06-03?from=artPopin',
  'time_published': '20260603T073927',
  'authors': ['Trefis Team'],
  'summary': "HCA Healthcare has returned $39 billion to shareholders over the past five years through dividends and buybacks, ranking it 45th historically among companies for capital returns. While high capital returns are attractive, the article also advises investors to assess if such returns come at the expense of growth and strong fundamentals, comparing HCA's performance and valuation with the S&P 500 median and its peers. The analysis also emphasizes the importance of staying invested through a diversified portfolio to navigate market volatility and benefit from long-term returns.",
  'banner_image': 'https://www.trefis.com/api/chart/https://s3.amazonaws.com/wp-uploads-trefis/articles/wp-content/uploads/2025/09/30062519/Shareholder-Returns-300x200.png',
  'source': 'Trefis',
  'category_within_source': 'General',
  'source_domain': 'Trefis',
  'topics': [{'topic': 'earnings', 'relevance_score': '0.915713'},
   {'topic': 'financial_markets', 'relevance_score': '0.826494'},
   {'topic': 'life_sciences', 'relevance_score': '0.703065'}],
  'overall_sentiment_score': 0.188477,
  'overall_sentiment_label': 'Somewhat-Bullish',
  'ticker_sentiment': [{'ticker': 'HCA',
    'relevance_score': '0.997269',
    'ticker_sentiment_score': '0.310000',
    'ticker_sentiment_label': 'Somewhat-Bullish'},
   {'ticker': 'MSFT',
    'relevance_score': '0.700057',
    'ticker_sentiment_score': '0.119170',
    'ticker_sentiment_label': 'Neutral'},
   {'ticker': 'GOOGL',
    'relevance_score': '0.604166',
    'ticker_sentiment_score': '0.136712',
    'ticker_sentiment_label': 'Neutral'},
   {'ticker': 'AAPL',
    'relevance_score': '0.628096',
    'ticker_sentiment_score': '0.117542',
    'ticker_sentiment_label': 'Neutral'},
   {'ticker': 'JPM',
    'relevance_score': '0.550662',
    'ticker_sentiment_score': '0.119475',
    'ticker_sentiment_label': 'Neutral'}]},
 {'title': "Rivian's Software Chief Explains Why Apple CarPlay, Android Auto And Even Analogue Buttons Are Destined To Be 'Completely Obsolete'",

In [83]:

# Step 2: Build the core DataFrame
df = pd.DataFrame(data['feed'])

df.head(2)

,title,url,time_published,authors,summary,banner_image,source,category_within_source,source_domain,topics,overall_sentiment_score,overall_sentiment_label,ticker_sentiment
0,Apple announces first developer center in Euro...,https://seekingalpha.com/news/4600223-apple-an...,20260603T124157,[Chris Ciaccia],Apple announced it will open its first develop...,https://static.seekingalpha.com/cdn/s3/uploads...,Seeking Alpha,General,Seeking Alpha,"[{'topic': 'technology', 'relevance_score': '1...",0.346226,Somewhat-Bullish,"[{'ticker': 'AAPL', 'relevance_score': '1.0000..."
1,HDV vs. FDVV: One of These High-Dividend ETFs ...,https://www.theglobeandmail.com/investing/mark...,20260603T121814,"[Motley Fool, Sara Appino]","This article compares two high-dividend ETFs, ...",https://barchart-news-media-prod.aws.barchart....,The Globe and Mail,General,The Globe and Mail,"[{'topic': 'finance', 'relevance_score': '0.84...",0.311317,Somewhat-Bullish,"[{'ticker': 'HDV', 'relevance_score': '1.00000..."

In [82]:
# Step 3: Clean up the published time into standard datetime formats
df['time_published'] = pd.to_datetime(df['time_published'], format='%Y%m%dT%H%M%S')

# Step 4: Extract list formats into clean comma-separated text strings
df['authors'] = df['authors'].apply(lambda x: ', '.join(x) if isinstance(x, list) else x)

print(df[['time_published', 'source', 'title', 'overall_sentiment_score', 'overall_sentiment_label']].head(4))

       time_published              source  \
0 2026-06-03 12:41:57       Seeking Alpha
1 2026-06-03 12:18:14  The Globe and Mail
2 2026-06-03 12:16:58                 BGR
3 2026-06-03 10:51:59          MarketBeat

                                               title  overall_sentiment_score  \
0  Apple announces first developer center in Euro...                 0.346226
1  HDV vs. FDVV: One of These High-Dividend ETFs ...                 0.311317
2  5 Reasons Why Customers Avoid Shopping At The ...                 0.133964
3  Apple Inc. $AAPL is Tranquility Partners LLC's...                 0.395429

  overall_sentiment_label
0        Somewhat-Bullish
1        Somewhat-Bullish
2                 Neutral
3                 Bullish