# Mobile App:

Three stories hidden in this data:
1) Customer JO-10042 started a money transfer and abandoned it — the bank now knows they intended to send money but stopped. Why? Financial hesitation? Wrong account details? This gets flagged for a follow-up push notification.

2) Customer JO-10091 spent 3.5 minutes on the loan calculator in Zarqa, then opened the application form and abandoned it. To the bank's model, this person wants a loan but something stopped them. High-value re-targeting opportunity.

3) Customer JO-10055 checked their balance three times in two minutes at midnight in Irbid. Classic financial stress signal — the bank's model scores this customer as higher risk for the next 30 days.

In [1]:
raw="""
event_id,customer_id,timestamp,action,screen_visited,duration_seconds,location_city,device_type,ip_address,battery_level_pct,completed
1,JO-10042,2024-03-15 08:14:22,app_open,Home Dashboard,45,Amman,Android,185.220.14.7,82,yes
2,JO-10042,2024-03-15 08:14:67,screen_visit,Account Balance,12,Amman,Android,185.220.14.7,82,yes
3,JO-10042,2024-03-15 08:15:21,screen_visit,Transfer Money,87,Amman,Android,185.220.14.7,81,no
4,JO-10042,2024-03-15 08:16:48,abandoned_action,Transfer Money,87,Amman,Android,185.220.14.7,81,no
5,JO-10091,2024-03-15 09:33:10,app_open,Home Dashboard,5,Zarqa,iPhone,46.32.18.221,34,yes
6,JO-10091,2024-03-15 09:33:15,screen_visit,Loan Calculator,210,Zarqa,iPhone,46.32.18.221,33,yes
7,JO-10091,2024-03-15 09:36:45,screen_visit,Personal Loan Apply,30,Zarqa,iPhone,46.32.18.221,32,no
8,JO-10091,2024-03-15 09:37:15,abandoned_action,Personal Loan Apply,30,Zarqa,iPhone,46.32.18.221,32,no
9,JO-10055,2024-03-15 23:47:02,app_open,Home Dashboard,8,Irbid,Android,94.188.22.45,91,yes
10,JO-10055,2024-03-15 23:47:10,screen_visit,Account Balance,62,Irbid,Android,94.188.22.45,90,yes
11,JO-10055,2024-03-15 23:48:12,screen_visit,Account Balance,58,Irbid,Android,94.188.22.45,90,yes
12,JO-10055,2024-03-15 23:49:10,screen_visit,Account Balance,71,Irbid,Android,94.188.22.45,89,yes
13,JO-10078,2024-03-15 11:22:05,app_open,Home Dashboard,15,Amman,iPhone,82.212.99.10,67,yes
14,JO-10078,2024-03-15 11:22:20,screen_visit,Investments,180,Amman,iPhone,82.212.99.10,66,yes
15,JO-10078,2024-03-15 11:25:20,screen_visit,Sukuk Products,240,Amman,iPhone,82.212.99.10,65,yes
"""

In [3]:
import pandas as pd
import io

df = pd.read_csv(io.StringIO(raw))
display(df)

,event_id,customer_id,timestamp,action,screen_visited,duration_seconds,location_city,device_type,ip_address,battery_level_pct,completed
0,1,JO-10042,2024-03-15 08:14:22,app_open,Home Dashboard,45,Amman,Android,185.220.14.7,82,yes
1,2,JO-10042,2024-03-15 08:14:67,screen_visit,Account Balance,12,Amman,Android,185.220.14.7,82,yes
2,3,JO-10042,2024-03-15 08:15:21,screen_visit,Transfer Money,87,Amman,Android,185.220.14.7,81,no
3,4,JO-10042,2024-03-15 08:16:48,abandoned_action,Transfer Money,87,Amman,Android,185.220.14.7,81,no
4,5,JO-10091,2024-03-15 09:33:10,app_open,Home Dashboard,5,Zarqa,iPhone,46.32.18.221,34,yes
5,6,JO-10091,2024-03-15 09:33:15,screen_visit,Loan Calculator,210,Zarqa,iPhone,46.32.18.221,33,yes
6,7,JO-10091,2024-03-15 09:36:45,screen_visit,Personal Loan Apply,30,Zarqa,iPhone,46.32.18.221,32,no
7,8,JO-10091,2024-03-15 09:37:15,abandoned_action,Personal Loan Apply,30,Zarqa,iPhone,46.32.18.221,32,no
8,9,JO-10055,2024-03-15 23:47:02,app_open,Home Dashboard,8,Irbid,Android,94.188.22.45,91,yes
9,10,JO-10055,2024-03-15 23:47:10,screen_visit,Account Balance,62,Irbid,Android,94.188.22.45,90,yes
10,11,JO-10055,2024-03-15 23:48:12,screen_visit,Account Balance,58,Irbid,Android,94.188.22.45,90,yes
11,12,JO-10055,2024-03-15 23:49:10,screen_visit,Account Balance,71,Irbid,Android,94.188.22.45,89,yes
12,13,JO-10078,2024-03-15 11:22:05,app_open,Home Dashboard,15,Amman,iPhone,82.212.99.10,67,yes
13,14,JO-10078,2024-03-15 11:22:20,screen_visit,Investments,180,Amman,iPhone,82.212.99.10,66,yes
14,15,JO-10078,2024-03-15 11:25:20,screen_visit,Sukuk Products,240,Amman,iPhone,82.212.99.10,65,yes

In [4]:
display(df[df['customer_id']=='JO-10091'])

,event_id,customer_id,timestamp,action,screen_visited,duration_seconds,location_city,device_type,ip_address,battery_level_pct,completed
4,5,JO-10091,2024-03-15 09:33:10,app_open,Home Dashboard,5,Zarqa,iPhone,46.32.18.221,34,yes
5,6,JO-10091,2024-03-15 09:33:15,screen_visit,Loan Calculator,210,Zarqa,iPhone,46.32.18.221,33,yes
6,7,JO-10091,2024-03-15 09:36:45,screen_visit,Personal Loan Apply,30,Zarqa,iPhone,46.32.18.221,32,no
7,8,JO-10091,2024-03-15 09:37:15,abandoned_action,Personal Loan Apply,30,Zarqa,iPhone,46.32.18.221,32,no

In [5]:
display(df[df['customer_id']=='JO-10055'])

,event_id,customer_id,timestamp,action,screen_visited,duration_seconds,location_city,device_type,ip_address,battery_level_pct,completed
8,9,JO-10055,2024-03-15 23:47:02,app_open,Home Dashboard,8,Irbid,Android,94.188.22.45,91,yes
9,10,JO-10055,2024-03-15 23:47:10,screen_visit,Account Balance,62,Irbid,Android,94.188.22.45,90,yes
10,11,JO-10055,2024-03-15 23:48:12,screen_visit,Account Balance,58,Irbid,Android,94.188.22.45,90,yes
11,12,JO-10055,2024-03-15 23:49:10,screen_visit,Account Balance,71,Irbid,Android,94.188.22.45,89,yes

# Hidden Sensors

In [7]:
raw = """
event_id,customer_id,timestamp,action,gps_lat,gps_long,location_name,accelerometer_state,screen_viewed,time_on_screen_seconds,scroll_depth_pct,loan_offer_shown,returned_to_offer
1,JO-10033,2024-03-15 12:00:01,app_open,31.9539,35.9106,Abdoun Amman,stationary,Home Dashboard,8,20,no,no
2,JO-10033,2024-03-15 12:00:09,screen_visit,31.9539,35.9106,Abdoun Amman,stationary,Personal Loan Offer,14,15,yes,no
3,JO-10033,2024-03-15 12:00:23,screen_exit,31.9539,35.9106,Abdoun Amman,stationary,Personal Loan Offer,14,15,yes,no
4,JO-10033,2024-03-15 14:22:10,app_open,31.9701,35.8693,Highway Amman-Zarqa,driving,Home Dashboard,4,10,no,no
5,JO-10033,2024-03-15 14:22:14,screen_visit,31.9701,35.8693,Highway Amman-Zarqa,driving,Personal Loan Offer,6,8,yes,no
6,JO-10033,2024-03-15 19:45:33,app_open,31.9512,35.9341,Sweifieh Amman,walking,Home Dashboard,5,12,no,no
7,JO-10033,2024-03-15 19:45:38,screen_visit,31.9512,35.9341,Sweifieh Amman,walking,Personal Loan Offer,11,22,yes,no
8,JO-10033,2024-03-15 22:58:44,app_open,31.9544,35.9110,Abdoun Amman,stationary,Home Dashboard,6,18,no,no
9,JO-10033,2024-03-15 22:58:50,screen_visit,31.9544,35.9110,Abdoun Amman,stationary,Personal Loan Offer,187,98,yes,yes
"""

In [8]:
import pandas as pd
import io

df = pd.read_csv(io.StringIO(raw))
display(df)

,event_id,customer_id,timestamp,action,gps_lat,gps_long,location_name,accelerometer_state,screen_viewed,time_on_screen_seconds,scroll_depth_pct,loan_offer_shown,returned_to_offer
0,1,JO-10033,2024-03-15 12:00:01,app_open,31.9539,35.9106,Abdoun Amman,stationary,Home Dashboard,8,20,no,no
1,2,JO-10033,2024-03-15 12:00:09,screen_visit,31.9539,35.9106,Abdoun Amman,stationary,Personal Loan Offer,14,15,yes,no
2,3,JO-10033,2024-03-15 12:00:23,screen_exit,31.9539,35.9106,Abdoun Amman,stationary,Personal Loan Offer,14,15,yes,no
3,4,JO-10033,2024-03-15 14:22:10,app_open,31.9701,35.8693,Highway Amman-Zarqa,driving,Home Dashboard,4,10,no,no
4,5,JO-10033,2024-03-15 14:22:14,screen_visit,31.9701,35.8693,Highway Amman-Zarqa,driving,Personal Loan Offer,6,8,yes,no
5,6,JO-10033,2024-03-15 19:45:33,app_open,31.9512,35.9341,Sweifieh Amman,walking,Home Dashboard,5,12,no,no
6,7,JO-10033,2024-03-15 19:45:38,screen_visit,31.9512,35.9341,Sweifieh Amman,walking,Personal Loan Offer,11,22,yes,no
7,8,JO-10033,2024-03-15 22:58:44,app_open,31.9544,35.9110,Abdoun Amman,stationary,Home Dashboard,6,18,no,no
8,9,JO-10033,2024-03-15 22:58:50,screen_visit,31.9544,35.9110,Abdoun Amman,stationary,Personal Loan Offer,187,98,yes,yes